### ISSUE TITLE
Ghost co-ordinates

### ISSUE THREAD

**Issue by Clarehonor** [qupath/qupath#416] opened 2020-03-20 09:42 UTC
## IMPORTANT!

**This is only for bug reports - for questions or discussions, please use the forum at [image.sc](https://forum.image.sc/tags/qupath) instead**

## Before we begin...

**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

If not, please do these things first.

Otherwise, please fill in the template below with as much information as possible to help us reproduce the bug & fix it.

## Bug report

**Describe the bug**

There seem to be ghost co-ordinates that are only visible when zooming in and alter the annotations.  The zoom level therefore determines the shape of the annotation.  In a similar way editing an annotation is causing the co-ordinates to move.

We have exported the annotations and jsons and reimported them and there was a bug in our own code that created these lines across the annotations.  

We are wondering whether, the co-ordinates of an original annotation are stored in some way even after editing, rather than being deleted.  For example, if a circle was drawn and then a chunk removed from the edge - would the original circumference details still be retained.

**To Reproduce**

See examples here:

https://www.youtube.com/watch?v=pQmyZTKsUTU - milestone 9

https://www.youtube.com/watch?v=0i0mODbj7Zc - on milestone 7
https://www.youtube.com/watch?v=MQONdCIs4Os - on milestone 7

**Expected behavior**
There would be one set of co-ordinates visible all the time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS, Ubuntu...]. MacOS 10.14.6
 - QuPath Version [e.g. 0.1.2]. Originally discovered problem in QuPath 0.2.0 milestone 7 but have replicated it in milestone 9.

**Additional context**

**Comment by petebankhead** [comment] 2020-03-20 09:55
There is a shape simplification step used when viewing annotations at a lower resolution, to avoid needing to paint all the vertices frequently. I'm not sure why it is failing in this case.

Does the issue occur only when combined with your code, or also when QuPath is used alone?
Can you provide any steps to reproduce, or files containing annotations that exhibit this behavior?

Just in case, note that ROIs are supposed to be immutable - so if any exterior code violates that (e.g. by manipulating private fields with ROIs) then the result would be Bad.

**Comment by petebankhead** [comment] 2020-04-22 13:40
I will close this issue because of a lack of a response, and I haven't been able to replicate it.

Please reopen it again if you are able to replicate it with the latest release (currently v0.2.0-m10) and provide further information.

**Closed by petebankhead** 2020-04-22 13:40 UTC
Labels: bug
