### ISSUE TITLE
Subtracting Brush Annotation

### ISSUE THREAD

**Issue by ClnSchlssr** [qupath/qupath#78] opened 2017-05-19 06:41 UTC
I hope I'm not duplicating because I have a vague memory of reading something along these lines...
Occasionally when subtracting one brush annotation from another which completely encapsulates it, they both disappear and a very tiny rectangle is created in the top left of the image. I haven't been able to figure out if it's a locked/unlocked thing or an order of selection thing.
Additionally, was the software meant to support meant to support multiple subtractions at once? I would imagine that could get a bit tricky, but from just a cursory glance at PathObjectToolsAwt.combineAnnotations it seems like it was meant to process more than just two?

**Comment by petebankhead** [comment] 2017-05-21 09:42
I have seen the tiny rectangle appear whenever I use the brush tool in 'subtract' mode (with the ```Alt``` key down), and remove the entire area.  However, in that case it is just a display thing - and the rectangle quickly disappears.  But based on your post I've just checked and I can reproduce it using *Subtract selected annotations*... in which case the rectangle can hang around for longer.  It still *does* disappear (sometimes...) if I select it, then start drawing a new annotation - but not entirely consistently.

What I think is happening is this:
* Whenever a ROI is effectively removed (either with the brush tool or subtraction), it results in a rectangle at location (0, 0) with zero width and zero height - this is nevertheless still drawn on screen
* When removing with the brush tool, a sanity check is applied to see if the resulting ROI has no area - and if so, the object is removed (e.g. [see here](https://github.com/qupath/qupath/blob/61a382e1e345e671b3fde32da08e03f08f4f7bcf/qupath-gui-fx/src/main/java/qupath/lib/gui/viewer/tools/AbstractPathDraggingROITool.java#L100))
* This sanity check isn't applied with the *Subtract selected annotations* command... so the 'empty' ROI does not result in the object being automatically removed
* Sometimes the sanity check can be triggered later... but it entirely clear when and why

I've flagged this as a bug, since something here is definitely not right and should be fixed.

I do think that there is a broader issue with the usefulness of the commands for combining annotations; these can and should behave more predictably.  It may not be helped by the fact that for a long time (before release) QuPath didn't support multiple objects being selected simultaneously, and much of the original code was written back in those days; as you can imagine, this was quite limiting.

You're completely right about support for subtracting multiple annotations being tricky from a how-to-present-this-to-the-user point of view.  I will give this some more thought.  My preference would be to replace the existing commands to combine annotations with entirely new ones that have more clearly defined purposes and limitations.

In the meantime, since you're already coding, it might be helpful to create your own script/extension to handle your specific needs.  To do this, I'd suggest looking into [PathROIToolsAwt.java](https://github.com/qupath/qupath/blob/a3e9246640f9819701d57c513bb21a0546cff130/qupath-core-awt/src/main/java/qupath/lib/roi/PathROIToolsAwt.java) - specifically ```getArea(ROI roi)``` and ```getShapeROI(...)```

The first of these can convert a QuPath ROI into a [```java.awt.geom.Area```](https://docs.oracle.com/javase/8/docs/api/java/awt/geom/Area.html).  An ```Area``` has methods to add/subtract/intersect with other ```Area``` objects.  Then you can use ```getShapeROI(...)``` to convert the result back into a QuPath ROI and create a new annotation if needed.

**Comment by ClnSchlssr** [comment] 2017-05-23 16:54
Thanks Pete,

 For the time being I've dealt with the multiple subtractions simply by adding all of the areas that need to be subtracted first. When things are passed in the right order things seem to work OK. I haven't looked through the code enough to understand if it's spurious or not yet, but locking also seems to make it more reliable. If it becomes an issue I'll dive a little deeper as you suggest. Besides occasionally having to learn some java-specific construction, I seem to be meandering through the code OK.  

Colin

**Closed** 2019-05-21 12:26 UTC
Labels: bug
