### ISSUE TITLE
"clipped" Max display in 16/32-bit images?

### ISSUE THREAD

**Issue by Mevelo** [qupath/qupath#352] opened 2019-08-13 15:33 UTC
## Bug report

**Describe the bug**
I am not sure if it's a bug or an intended behaviour, but I have a recurrent "problem" with the max display setting of fluorescent channels when viewing them and trying to find the best viewing settings. 
I have 16 bit images (.vsi) scanned on an olympus VS120. When opening them in QuPath, the first thing I usually do is to run a script to set the min and max display:
```
// Get access to the display info for each channel
def viewer = getCurrentViewer()
def channels = viewer.getImageDisplay().availableChannels()

// Set the range for the 4 channels
channels[0].setMinDisplay(500)
channels[0].setMaxDisplay(30000)
channels[1].setMinDisplay(500)
channels[1].setMaxDisplay(30000)
channels[2].setMinDisplay(500)
channels[2].setMaxDisplay(30000)
channels[3].setMinDisplay(500)
channels[3].setMaxDisplay(20000)
```

In theory it should be possible to use a maximum value of 65,536 if I am not mistaken, for 16 bit images. However, if I want to fine tune this setting and open the "Brightness & Contrast" tool, I am not able to go to the maximum theoritical value. 
If I start playing with the "Max display" side of the bar, it automatically "clips" the range to a certain value usually relatively low, making the signal way too strong in most cases (not sure how that value is calculated?), and there is no going back using this "Brightness & Contrast" tool. 
The only way of adjusting this value is to re-use the script. It is fine and can be done, but I was wondering if it would be possible to modify QuPath to prevent the software from this behaviour? I don't remember having such problem when using 8-bit Versa images, but I think I had the same issue using 32-bit vectra images.

**Desktop (please complete the following information):**
 - OS: Windows, macOS
 - QuPath Version 0.2.0m3 (and before too)

**Comment by petebankhead** [comment] 2019-08-13 16:27
It's intended behavior, albeit with room for improvement. You can adjust the settings beyond what the slider permits by double-clicking on the label displaying the min/max display value: https://github.com/qupath/qupath/issues/26

For 8-bit it is straightforward and the range should be 0-255. For 16-bit and 32-bit it is not so straightforward; the actual range of the data can be much less than the range permitted by the bit-depth, and a slider from 0-65,535 would be extremely difficult to adjust with any level of accuracy. Also, for 16-bit images the actual camera may well be 12 or 14-bit - but that information isn't necessarily available in the image metadata.

When an image is being opened, QuPath generates a histogram per channel and the default min/max values are taken from this. For large images, this must be calculated from a lower-resolution image. Because decreasing resolution likely involves smoothing, the maximum of the low-resolution image may well be less than the maximum of the full-resolution image.

**Comment by r-mvl** [comment] 2019-08-20 21:15
Thanks for your reply. It is a bit frustrating to see the slider preventing from using a higher max value that what QuPath has calculated it should be, but I didn't know about the double-clicking and  it's a good workaround.

**Comment by petebankhead** [comment] 2020-05-21 17:33
Closing this because (even if suboptimal) the behavior is as intended, and a workaround exists for fixing the min/max when required.

**Closed by petebankhead** 2020-05-21 17:33 UTC
Labels: bug
