### ISSUE TITLE
Unexpected scaling in intensity plots of multiplex IF images

### ISSUE THREAD

**Issue by amtsak** [qupath/qupath#326] opened 2019-05-31 18:20 UTC
**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

Good, then please fill in the template about the bug...

> For general questions about the software (not bugs) use [image.sc](https://forum.image.sc/tags/qupath)

----

**Describe the bug**
In brightness and contrast menu the x axis of the intensity plot always has min 0 and max 429496729 when 'Keep settings' is enabled. The scaling bars also stop working when this happens. Have seen this with multiplex fluorescent images (multipage tifs) that have the same channels (same names) but in different order. 
EDIT: Happens even if all channels are in consistent order and with just 2-3 images.

**To Reproduce**
1. Open multiple multi-page .tif multiplex fluorescent images in the same project (32-bit).
2. Click on Brightness and contrast menu
3. Change scaling for a single channel and enable 'Keep settings'
4. Repeat for different images
5. After a few images the gets set to min 0 and max 429496729 for all channels, not just the one. This happens in multiple images in the same project. 
6. Different subsets of images (that I've tested so far at least) always produce the same unexpected min and max on the x axis. Don't know the significance of these numbers.
7. Axis scale doesn't return to normal when 'Keep settings' is disabled.

**Expected behavior**
This shouldn't be happening - 'Keep settings' option messes up the intensity plots.

**Screenshots**
![brightnessandcontrastqupath2bug](https://user-images.githubusercontent.com/22013848/58724088-a15bd900-83d3-11e9-97d0-7b0522abd17c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and Mac OS
 - QuPath Version 0.2.0-m2 (doesn't happen in 0.1.3)

**Comment by Svidro** [comment] 2019-05-31 18:34
What image server are you using? I have been playing with the Vectra tiff files exported in a number of different ways and haven't had any problems. Though, you really should be exporting the files in a way that keeps the channels consistent. Otherwise any scripts/classifiers/etc based on channel values won't work for a project!

The max value is that of an image with a bit depth of 32, which I suspect you will see in the Image tab, and is one of the default Vectra exports. If one of your channels is incredibly bright, then as soon as that channel is in a given position (and keep settings is enabled), it should, correctly, lock that as the max value for future images. If the bright channel keeps jumping around because the channel order is not fixed, eventually all of the channels will have those min and max values.

I think.

**Comment by Svidro** [comment] 2019-05-31 18:36
As a side note, I am guessing this is the unprocessed, and therefor not linearly unmixed Vectra component TIFF files?

**Comment by amtsak** [comment] 2019-05-31 19:22
Thanks that was my guess as well about what caused this. However sorry to be the bearer of bad news but I just managed to reproduce this with only 3 images - all with consistent channel ordering.

It seems to occur just by moving many times between the different images with 'Keep settings' enabled.
Also none of the 3 images originally had a max value of 429496729  before enabling 'Keep settings'. 

I've used many such images in the past with version 0.1.3 and never had a problem with scaling - but 'Keep settings' wasn't an option there.

![bug21](https://user-images.githubusercontent.com/22013848/58729439-59dc4980-83e1-11e9-93a8-d47f5932c870.png)

These are images exported from inForm, scanned with Vectra microscope 8 channels. They are the linearly unmixed component data tifs.

**Comment by Svidro** [comment] 2019-05-31 19:42
Oh, interesting. 
I can confirm the behavior, though only on 32 bit depth images. The 8bit versions do not run into the same problem. It seems to be reproducible in about 3 steps. 
Open image with keep settings checked, go to new image, return to first image. First image will then have the 32bit max.
![image](https://user-images.githubusercontent.com/23145209/58730364-c4b96080-83a0-11e9-9c83-2b02d4be8242.png)



This is a bit off topic, but the component data files I was getting from InForm users were not unmixed (though the users thought that they were at first), they could only export those as individual channels and then I had to write a whole macro to recombine them in FIJI. If you have the time, could you explain how you managed the export process? If they are holding out on me... ^_^

**Comment by amtsak** [comment] 2019-06-01 19:26
Thanks for checking that. 

Unless I'm missing something you can export a multi-page tif from inForm directly using the export dialogue (see image below). Each channel in this tif will contain the intensities of a single marker after unmixing. Metadata are saved as well so QuPath can pick up the names of channels automatically making life easier. Sorry you had to manually combine the channels in FIJI, hope this helps from now on.

![inform_export](https://user-images.githubusercontent.com/22013848/58752646-860fcd00-84aa-11e9-8362-0a47482380ac.png)

**Comment by Svidro** [comment] 2019-06-02 02:09
Hmm, maybe the unmixing was failing. I am pretty sure that is what they started with and it looked exactly like the completely unmixed versions of the images.

**Comment by petebankhead** [comment] 2019-07-24 11:28
This should be fixed in [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3).
Please reopen this issue if problems arise.

**Closed by petebankhead** 2019-07-24 11:28 UTC
Labels: bug
