### ISSUE TITLE
Maximum Memory setting not being saved

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#582] opened 2020-08-04 21:56 UTC
**Describe the bug**
In QuPath 0.2.2, the maximum memory setting (Help > Show Setup Options > Maximum Memory) does not save/recall my input. It goes back to half my ram every time, no matter what I type. It loses it after a restart, or even if I open that menu again immediately after hitting Apply. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version 0.2.2, tested on both the .zip and the .msi install

**Comment by camlloyd** [comment] 2020-08-04 22:06
I think I ran into the same issue, but somehow couldn't narrow down the steps to reproduce it (so didn't open an issue).

I think I set the maximum memory to `-1` (default), restarted QuPath, then tried again and it "fixed" it?

**Comment by Svidro** [comment] 2020-08-04 22:15
For me the issue is the line in the config file that reads something like 
```
[JavaOptions]
-Xmx204800M
```
or 
```
[JavaOptions]
-XX:MaxRAMPercentage=50
```
The max percentage 50 prevented me from setting the RAM within QuPath to over 50% of the system total. I could still set it to something lower, though that is rarely desirable. Adjusting the config file manually allowed me to change it as desired. I think manually setting the RAM to something lower than 50% might have changed it from MaxRAM (which did not let me adjust QuPath's RAM usage higher)  to -Xmx which can be reset on the fly by QuPath.

Not 100% sure as this is all anecdotal/from my memory. Which is... well, not great.

**Comment by saramcardle** [comment] 2020-08-04 22:19
I just tried the suggestion to lower the memory and then raise it, and that seemed to work, actually. 

Thanks!!

**Comment by Svidro** [comment] 2020-08-04 22:19
I think that was it, setting it to something lower than 50% (maybe the -1 did this as well), changes the text from the MaxRAM to something specific Xmx.

Once it is Xmx, it can be changed, as there are no longer "prohibited" values.

Just a guess based on behavior, dunno about in the code.

**Comment by petebankhead** [comment] 2020-08-05 07:02
I've just made a pull request that I think resolves this.

The underlying issue is that QuPath has stored the requested maximum memory value from another installation, but this isn't consistent with the cfg file of the current installation. If you request that the max memory is identical to the value stored in the preference, then it isn't updated. Setting it to anything else (higher or lower) should work.

(There is possibly no need to store the memory in a persistent preference at all - this was more relevant in v0.1.2 when memory could be handled differently. The pull request doesn't go quite that far though.)

**Comment by petebankhead** [comment] 2020-08-05 14:31
Fix has been merged to the main repo.

**Closed by petebankhead** 2020-08-05 14:31 UTC
Labels: bug
