### ISSUE TITLE
Human-in-the-loop model training for deep-learning-based extensions

### ISSUE THREAD

**Issue by winglet0996** [qupath/qupath#1702] opened 2024-11-18 03:48 UTC
Deep-learning-based extensions (e.g. Stardist, Instanseg) suffer from the domain shift. I tried your newly released Instanseg extension on my immunochemistry (IHC) data, the segmentation performance is poor. Extensions like [MONAI Label](https://nbviewer.org/github/Project-MONAI/tutorials/blob/main/monailabel/monailabel_pathology_nuclei_segmentation_QuPath.ipynb) support human-in-the-loop model training in GUI to iteratively finetune the model to improve the accuracy on users' dataset (the figure below). I think it would be perfect if Instanseg extension support model finetuning just one click a way.

![image](https://github.com/user-attachments/assets/03b7c84b-f0aa-4ed8-ade8-1e4748157897)

**Comment by petebankhead** [comment] 2024-11-18 11:47
Hi, we already have human-in-the-loop training for pixel and object classifiers based on conventional machine learning. How this might relate to deep learning and InstanSeg specifically is certainly something we're thinking about.

I'll close the issue because it's not a bug or a straightforward development task we can plan for, but thanks for the feature request - good to know it would be of interest.

**Closed by petebankhead** 2024-11-18 11:47 UTC
Labels: enhancement
