### ISSUE TITLE
Error when opening script editor

### ISSUE THREAD

**Issue by r-mvl** [qupath/qupath#349] opened 2019-08-05 13:35 UTC
## Bug report

**Describe the bug**
When I open one of my scripts located in the script directory (directly from the menu) I get the following error messages:

```
INFO: Loading script file C:\***script.groovy
ERROR: QuPath exception
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)
```
I can still use the script editor, just need to close the warning.
I've tried changing directory or resaving the scripts but it didn't change anything...

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version 0.2.0-m3

**Comment by petebankhead** [comment] 2019-08-05 13:40
I'm unable to reproduce this on Windows 10; using _Automate &rarr; Shared scripts &rarr; ..._ my script opens without an error.

**Comment by petebankhead** [comment] 2019-08-05 16:15
It looks like the error occurs rather deep in the JavaFX code [here](https://github.com/javafxports/openjdk-jfx/blob/4f0addff16de7182752bc60541f44baeb0e99d2a/modules/javafx.controls/src/main/java/javafx/scene/control/skin/MenuButtonSkinBase.java#L188).
Does it happen consistently? At first glance it doesn't look like it's something that can be resolved within QuPath.

**Comment by r-mvl** [comment] 2019-08-05 20:33
It does happen constantly. It didn't at first, and then started to appear. I don't know why,... but thought it might be worst reporting in case it had anything to do with QuPath. I might just try to re-install QuPath and see if it comes back.

**Comment by petebankhead** [comment] 2019-08-06 07:53
If you aren't _too_ attached to your custom preferences, I'd try _Edit &rarr; Reset preferences_.
This may have more impact that reinstalling.

**Comment by r-mvl** [comment] 2019-08-06 08:53
Thanks Pete, it was as simple as that, issue solved.

**Comment by petebankhead** [comment] 2019-08-06 08:54
Excellent! I'll close the issue, but if you ever discover what went wrong please do reopen it again.

**Closed by petebankhead** 2019-08-06 08:54 UTC
Labels: bug
