### ISSUE TITLE
Problems with bif images

### ISSUE THREAD

**Issue by elbuckles** [qupath/qupath#323] opened 2019-05-29 19:45 UTC
**You've checked https://qupath.github.io for a new release that might already have fixed the issue, right?**

**And you've searched for related issues here to see if the issues has already been reported?**

Good, then please fill in the template about the bug...

> For general questions about the software (not bugs) use [image.sc](https://forum.image.sc/tags/qupath)

----

**Describe the bug**
When opening .bif images the image edges are irregular

**To Reproduce**
1.Drag .bif image into viewer and look. 

**Expected behavior**
Expected image would not have irregular edges 

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS:Mac OS

![bif issue screenshot](https://user-images.githubusercontent.com/51175473/58586285-bb0ced00-8228-11e9-8524-30c14cc453f8.png)

 - QuPath Version [e.g. 0.1.2 and in beta test version]

**Additional context**

**Comment by Svidro** [comment] 2019-05-29 20:05
Is the Image server listed on the Image tab BioFormats? And if so, have you tested opening the image in FIJI using the BioFormats import? I saw similar issues with 8bit CZI files that had been tiled, and it turned out to be on the BioFormats end.

**Comment by petebankhead** [comment] 2019-05-29 20:30
There's a discussion about .bif images on the _old_* forum: https://groups.google.com/d/msg/qupath-users/e5Fmt7lU43g/yFM8-Y_SBQAJ

As far as I'm aware, .bif images are currently only supported by OpenSlide and not by Bio-Formats. There is a known issue with OpenSlide's .bif support that looks similar to what you describe: https://github.com/openslide/openslide/issues/132

Nevertheless, it looks like there may be a .bif reader in the next version of Bio-Formats: https://github.com/openmicroscopy/bioformats/milestone/70

Either way, QuPath doesn't have its own .bif reader and therefore it isn't caused by a bug in QuPath... if support is added/improved in either OpenSlide or Bio-Formats then the images should work with QuPath, otherwise I'm afraid it sounds like they need to be converted to .tif to be compatible (based on the Google Groups conclusion).

*-Note the one is https://forum.image.sc/tags/qupath

**Comment by petebankhead** [comment] 2019-06-02 11:57
I will close this issue as it does not appear to be a bug in QuPath itself.

**Closed by petebankhead** 2019-06-02 11:57 UTC
Labels: bug, file formats

**Comment by Tato14** [comment] 2020-06-08 14:27
I reopen this again since @petebankhead link this issue in the new 0.2.0 version docs. I am having this exact issue. Also, I opened the same bif file using the openslide-python library and the misaligned tile issue persists so I hope Bio-formats would solve the issue.

"Both OpenSlide and (more recently) Bio-Formats now support BIF images. If you have trouble with one library, you might try reading the images with the other."

How do you force QuPath 0.2.0 to open a bif image using Bio-Formats? I found the way to disable the former in *Preferences* but I am not able to find `openslide` anywhere. I tried to took out `openslide` jar files from `lib` but this make QuPath to crash.

**Comment by petebankhead** [comment] 2020-06-08 14:29
@Tato14 you can specify the image provider when adding the .bif image to a project: https://qupath.readthedocs.io/en/latest/docs/tutorials/projects.html#add-images

You can also change in the preferences whether Bio-Formats always/never is used for a particular extension (there is no comparable option for OpenSlide... but if Bio-Formats is never used, then OpenSlide will be used where possible).

**Comment by Tato14** [comment] 2020-06-08 14:36
Thanks! Both solutions solve the issue :+1:
