### ISSUE TITLE
touch gestures: zooms when moving up/down

### ISSUE THREAD

**Issue by 2010mars2010** [qupath/qupath#188] opened 2018-07-24 12:43 UTC
Hi!
Unfortunately up and down movements on the screen always activates the zoom, even when I activate some of the marking tools. I wasn't able to fix this through tool settings.
If the zoom could be deactivated I could use touchscreen and pen very conveniently for marking the tissue areas.
Does anyone have a solution?
Best,
Marcel

**Comment by Svidro** [comment] 2018-07-24 15:07
I think this is pretty much it.  
https://groups.google.com/forum/#!searchin/qupath-users/touch%7Csort:date/qupath-users/IZSVOOgWZ9E/Hd3QWlQXBAAJ
I am not sure if the changes are in version 1.3 yet, but you could try downloading that.
https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html

**Comment by petebankhead** [comment] 2018-07-24 15:12
As far as I remember, the fix I made is in a different branch and so not in v0.1.3 yet.
But I can confirm that there is no combination of settings in v0.1.2 to work around this, unfortunately... it will require an update to QuPath itself.

**Comment by 2010mars2010** [comment] 2018-07-24 15:17
Thank you Pete for your fast reply!

I am already looking forward to that update!

 

I appreciate your work so much!

 

Best,

Marcel

 

Von: Pete [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. Juli 2018 11:13
An: qupath/qupath
Cc: 2010mars2010; Author
Betreff: Re: [qupath/qupath] touch gestures: zooms when moving up/down (#188)

 

As far as I remember, the fix I made is in a different branch and so not in v0.1.3 yet.
But I can confirm that there is no combination of settings in v0.1.2 to work around this, unfortunately... it will require an update to QuPath itself.

**Comment by petebankhead** [comment] 2018-07-26 09:03
Hi Marcel, if you want to try the version described [here](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html) then hopefully it resolves this issue.  Be sure to fetch the very latest version, as I've only incorporated in the changes in the last few minutes.

I just have one Dell touchscreen to test on (and no pen), but with these changes it certainly behaves a lot more sensibly than it did previously.

**Comment by 2010mars2010** [comment] 2018-07-31 15:00
Hi Pete,

 

thank you so much!

However can you tell me which is the very latest version?

Is it “core-processing-awt” or “gui-fx”? Both were published five days ago.

 

Once again thank you so much for your quick support!

 

Marcel

 

Von: Pete [mailto:notifications@github.com] 
Gesendet: Donnerstag, 26. Juli 2018 05:04
An: qupath/qupath
Cc: 2010mars2010; Author
Betreff: Re: [qupath/qupath] touch gestures: zooms when moving up/down (#188)

 

Hi Marcel, if you want to try the version described here <https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html>  then hopefully it resolves this issue. Be sure to fetch the very latest version, as I've only incorporated in the changes in the last few minutes.

I just have one Dell touchscreen to test on (and no pen), but with these changes it certainly behaves a lot more sensibly than it did previously.

**Comment by petebankhead** [comment] 2018-07-31 15:07
Both are required - you'll need all the code there. If you follow the instructions towards the end of the linked page (starting with _Step by step guide_) you should end up with a runnable version of QuPath, with all the different components and dependencies.

**Comment by 2010mars2010** [comment] 2018-08-06 23:03
Hi Pete,

 

thank you so much for the new versoin, it works perfectly with my hp spectre 360 and the hp tilt pen!

 

I only got one problem: QuPath cannot open any *.svs (scanscope virtual slide) images any more. Do you have a solution for that?

 

Once again thank you so much!

 

Yours,

Marcel

 

Von: Pete [mailto:notifications@github.com] 
Gesendet: Dienstag, 31. Juli 2018 11:10
An: qupath/qupath
Cc: 2010mars2010; Author
Betreff: Re: [qupath/qupath] touch gestures: zooms when moving up/down (#188)

 

Both are required - you'll need all the code there. If you follow the instructions towards the end of the linked page (starting with Step by step guide) you should end up with a runnable version of QuPath, with all the different components and dependencies.

**Comment by petebankhead** [comment] 2018-08-07 07:01
> I only got one problem: QuPath cannot open any *.svs (scanscope virtual slide) images any more. Do you have a solution for that?

I this running on Windows 10, and are there any errors under _View &rarr; Show log_ when you try to open an .svs file?  Does it work with the other version of QuPath on the same machine (v0.1.2)?

My guess is that OpenSlide isn't loading for you, but it's the same version as in v0.1.2... so it one works, then I'd expect the other to work as well.

If you were running QuPath from an IDE (e.g. IntelliJ, eclipse) then paths would also need to be set for OpenSlide to work, and that would be an explanation.  But if instead you follow the [step by step instructions](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#step-by-step-guide) right to the end, it should result in a QuPath.exe file that work if you double-click it without any further effort.

The other option is to install the latest [QuPath Bio-Formats extension](https://github.com/qupath/qupath-bioformats-extension)... but it shouldn't be necessary for standard .svs files.

**Comment by 2010mars2010** [comment] 2018-08-09 03:04
Dear Pete,

 

It is indeed windows 10. This is what log shows:

 

ERROR: Unable to load OpenCV libraries!

    at java.lang.ClassLoader$NativeLibrary.load(Native Method)

    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)

    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)

    at java.lang.Runtime.loadLibrary0(Runtime.java:870)

    at java.lang.System.loadLibrary(System.java:1122)

    at qupath.opencv.OpenCVExtension.loadNativeLibrary(OpenCVExtension.java:59)

    at qupath.opencv.OpenCVExtension.addQuPathCommands(OpenCVExtension.java:72)

    at qupath.opencv.OpenCVExtension.installExtension(OpenCVExtension.java:116)

    at qupath.lib.gui.QuPathGUI.refreshExtensions(QuPathGUI.java:1093)

    at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:637)

    at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:429)

    at qupath.lib.gui.QuPathApp.start(QuPathApp.java:63)

    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)

    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)

    at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)

    at java.security.AccessController.doPrivileged(Native Method)

    at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)

    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)

    at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)

    at java.lang.Thread.run(Thread.java:748)

INFO: Selected style: Modena Light

INFO: Performing update check...

INFO: Starting QuPath with parameters: []

 

I deinstalled the other version but there it did work without any problems.

Is there any way to deinstall qupath so that I can try to install it again?

 

Best,

Marcel

 

 

Von: Pete [mailto:notifications@github.com] 
Gesendet: Dienstag, 7. August 2018 03:02
An: qupath/qupath
Cc: 2010mars2010; Author
Betreff: Re: [qupath/qupath] touch gestures: zooms when moving up/down (#188)

 

I only got one problem: QuPath cannot open any *.svs (scanscope virtual slide) images any more. Do you have a solution for that?

I this running on Windows 10, and are there any errors under View → Show log when you try to open an .svs file? Does it work with the other version of QuPath on the same machine (v0.1.2)?

My guess is that OpenSlide isn't loading for you, but it's the same version as in v0.1.2... so it one works, then I'd expect the other to work as well.

If you were running QuPath from an IDE (e.g. IntelliJ, eclipse) then paths would also need to be set for OpenSlide to work, and that would be an explanation. But if instead you follow the step by step instructions <https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#step-by-step-guide>  right to the end, it should result in a QuPath.exe file that work if you double-click it without any further effort.

The other option is to install the latest QuPath Bio-Formats extension <https://github.com/qupath/qupath-bioformats-extension> ... but it shouldn't be necessary for standard .svs files.

**Comment by petebankhead** [comment] 2018-08-09 04:56
Strange... it suggests the cause is the one that I expected (not being able to load native libraries), but I'm not sure why it's happening here.

You should be able to just delete the directory containing everything downloaded from GitHub; if you want to check where it is, inside GitHub Desktop you can choose _Repository &rarr; Show in Explorer_. 

Then you can start again with https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#building-qupath

**Comment by 2010mars2010** [comment] 2018-08-21 11:55
Dear Pete,

 

Unfortunately it still didn’t work. I noticed  there was an Error during installation (see below), do you know what it means?

 

Best and thank you so much for your support!

Marcel

 

 

Microsoft Windows [Version 10.0.17134.228]

(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

 

C:\Users\marsh\Documents\GitHub\qupath>gradlew.bat jfxNative

Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

 

> Configure project :

I won't try to get the last commit - consider running with '-Prequest-git-tag=true' if you want this next time (assuming Git is installed)

Operating system: Windows 10 10.0 x86

Current Java version: 1.8

Found the packager at C:\Program Files (x86)\Java\jdk1.8.0_181\jre\..\lib\packager.jar

Copying license directories:

  C:\Users\marsh\Documents\GitHub\qupath\qupath-extension-ij\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-extension-opencv\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-extension-openslide\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-extension-pen\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-extension-script-editor\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-gui-fx\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-processing-ij\src\main\resources\licenses

  C:\Users\marsh\Documents\GitHub\qupath\qupath-processing-opencv\src\main\resources\licenses

Extracting native libraries from C:\Users\marsh\Documents\GitHub\qupath\maven\repo\org\openslide\openslide\3.4.1_2\openslide-3.4.1_2-natives-windows.jar

Extracting native libraries from C:\Users\marsh\Documents\GitHub\qupath\maven\repo\net\sourceforge\jpen\jpen\2-150301\jpen-2-150301-natives-windows.jar

Extracting native libraries from C:\Users\marsh\Documents\GitHub\qupath\maven\repo\org\opencv\opencv\3.1.0\opencv-3.1.0-natives-windows.jar

Result application bundle: C:\Users\marsh\Documents\GitHub\qupath\build\jfx\native

  Config files are saved to C:\Users\marsh\AppData\Local\Temp\fxbundler5936450042917729024\windows. Use them to customize package.ve\ij-1.51s.jar has a main class ij.ImageJ that does not match the declared main qupath.QuPath

> :jfxNative=-> 98% EXECUTING [18s]a main class groovy.ui.GroovyMain that does not match the declared main qupath.QuPath

The jar jars\openslide-3.4.1_2.jar has a main class org.openslide.gui.Demo that does not match the declared main qupath.

BUILD SUCCESSFUL in 27sCUTING [18s]

41 actionable tasks: 3 executed, 38 up-to-date181\jre\bin\java, -version]

C:\Users\marsh\Documents\GitHub\qupath>

 

> :jfxNative=-> 98% EXECUTING [18s]al\Temp\iconswap1913588824785848432.exe, C:\Users\marsh\AppData\Local\Temp\fxbundler5

936450042917729024\windows\QuPath.ico, C:\Users\marsh\Documents\GitHub\qupath\build\jfx\native\QuPath\QuPath.exe]

> :jfxNative=-> 98% EXECUTING [18s]ata\Local\Temp\fxbundler5936450042917729024\windows\QuPath.ico

Executable File Name: C:\Users\marsh\Documents\GitHub\qupath\build\jfx\native\QuPath\QuPath.exe

> :jfxNative=-> 98% EXECUTING [18s]

> :jfxNative

 

Von: Pete [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. August 2018 00:57
An: qupath/qupath
Cc: 2010mars2010; Author
Betreff: Re: [qupath/qupath] touch gestures: zooms when moving up/down (#188)

 

Strange... it suggests the cause is the one that I expected (not being able to load native libraries), but I'm not sure why it's happening here.

You should be able to just delete the directory containing everything downloaded from GitHub; if you want to check where it is, inside GitHub Desktop you can choose Repository → Show in Explorer.

Then you can start again with https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#building-qupath

**Comment by petebankhead** [comment] 2018-08-21 12:02
It looks like you're using 32-bit Windows - or, if not, then at least the 32-bit version of the Java JDK.  QuPath needs the 64-bit bit version, unfortunately.

If your Windows supports it, then you could try uninstalling the Java JDK and installing the one on the download page flagged as 'Windows x64' (rather than 'Windows x86').  That might help.

I don't see exactly why it would cause this error (at 98%, so close!), but it's my best guess... I've not seen that error before, but I've only been able to test it on a 64-bit system.

**Comment by 2010mars2010** [comment] 2018-08-21 14:04
Hi Pete,

 

that seems to be the solution! Thank you sooo much!!!!

I still got some weird lines in the command prompt but QuPath is working now, supports all pen functions I was looking for and I am able to open *.svs files again!

 

You are truly the best!

 

Once again thank you so much for your fast reply and great solutions!

Best regards from New York,

Marcel

 

 

 

 

Von: Pete [mailto:notifications@github.com] 
Gesendet: Dienstag, 21. August 2018 08:03
An: qupath/qupath
Cc: 2010mars2010; Author
Betreff: Re: [qupath/qupath] touch gestures: zooms when moving up/down (#188)

 

It looks like you're using 32-bit Windows - or, if not, then at least the 32-bit version of the Java JDK. QuPath needs the 64-bit bit version, unfortunately.

If your Windows supports it, then you could try uninstalling the Java JDK and installing the one on the download page flagged as 'Windows x64' (rather than 'Windows x86'). That might help.

I don't see exactly why it would cause this error (at 98%, so close!), but it's my best guess... I've not seen that error before, but I've only been able to test it on a 64-bit system.

**Comment by bjtho08** [comment] 2019-01-15 23:01
I am experiencing the same issue with a Wacom pen tablet. I don't have the time to test the latest test version, I just want to heaer if there are any plans on releasing a new pre-compiled version in the near future?

**Comment by petebankhead** [comment] 2019-01-16 09:10
They use the standard Java Preferences API so for Windows that is (I believe) the registry.
In the future (and on my build-able fork), classifications will also be maintained in .qpproj files to make it easier to switch between different lists: https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html#classification-lists-are-stored-in-projects

**Comment by bjtho08** [comment] 2019-01-16 10:04
You are correct about the registry, but unfortunately it is not stoered in human-readable format, so I guess I'll just have to wait :)

**Comment by Svidro** [comment] 2019-01-16 19:44
I am not 100% sure I read this all correctly, but one thing to consider is that removing classes from the list does not remove or alter annotations that are classified. I have tons of classes that don't even exist in the annotation list of classes.  Of course, it will still be a pain to remove and re-create them all, but already created annotations should not be a concern.

**Comment by bjtho08** [comment] 2019-04-03 14:14
I want to re-open the original bug that was reported in this thread. It seems the behavior has returned in the latest 0.2.0-m2 milestone version when using a Wacom tablet and pen.

**Comment by petebankhead** [comment] 2019-04-03 14:21
I do not currently have a Wacom tablet to test this. You say 'returned', but you never reported if it was fixed for you in any version, only that you didn't have time to test it at the time I was actively working on it.

If you want a solution, it would be helpful if you could provide much more detailed information about what does/did work, on which operating systems and which versions of QuPath etc. If I knew it works in v0.1.3 but not in v0.2.0-m1 _on the same computer_ that would be a start. Is this the case?

**Comment by bjtho08** [comment] 2019-04-03 14:33
Sorry, I just saw that the bug was marked close and didn't think deeper about it. Yes, the bug was gone in version 0.1.3 on the same computer (Windows 10) and with the same tablet and drivers.
So to specify what was working in 0.1.3:

- Pan (using e.g. spacebar or move tool) would correctly move the viewport in the desired direction. Moving up or down would not result in pan AND zoom
- Pen pressure would change the brush size to mimic the brush strokes of a paint brush and thus making it much more flexible when doing precise annotation at different zoom levels.

By the way, it would be a neat feature if it was possible to rotate images more than +-90 degrees and perhaps even flip them (for when you want to align images in two viewports).

**Comment by Svidro** [comment] 2019-04-03 14:37
https://github.com/qupath/qupath/issues/293

**Comment by petebankhead** [comment] 2019-04-03 14:41
Thanks @Svidro 
@bjtho08 note that v0.2.0-m2 uses a different location for user preferences to avoid conflicting with v0.1.3. Have you checked that the relevant preferences are the same, e.g. those under _tools &rarr; Multi-touch gestures_?

**Comment by petebankhead** [comment] 2019-04-03 14:58
Note that I think the JPen issue is separate, related to an inability to load the native library. The switch to JDK 11 has resulted in some new behavior regarding where native libraries are found.

**Comment by bjtho08** [comment] 2019-04-03 16:55
@petebankhead yes, I did check those settings before posting, so it would seem that you are correct in that it is a result of the switch to JDK 11.

**Comment by petebankhead** [comment] 2019-04-04 09:10
When I run the following script:
```groovy
try {
    System.loadLibrary('jpen-2-3-64')
} catch (Throwable t) {
    print t
}
```
I get an error that it cannot find dependent libraries.  However I see the same error in all versions of QuPath... possibly because I don't have a tablet.

What do you see if you run this script in both working and non-working versions of QuPath?

**Comment by bjtho08** [comment] 2019-04-04 09:25
Update: It appears the lack of pressure sensitivity was actually caused by a recent change in Windows 10 which was fixed by a driver released in mid-march. So We are back to only having trouble with the zooming while moving up/down.

**Comment by petebankhead** [comment] 2019-04-04 09:36
Already loaded sounds like a the right error to see.

I don't encounter any zooming problem when I use my touchscreen (without a pen) and don't recall having made any changes in this regard since v0.1.3. I can use the brush comfortably with the touchscreen & my finger, and it only zooms if I 'swipe' at the end of the gesture - otherwise the image is static.

Is this also what you see? Since it turns out that JPen works after all, I really don't have enough information to know _exactly_ what problem you are reporting, when it occurs, how to reproduce it and with precisely what settings enabled in QuPath.

**Comment by bjtho08** [comment] 2019-04-04 09:41
> it only zooms if I 'swipe' at the end of the gesture

This actually EXACTLY my issue! Avoiding the swipe motion requires very careful handling of the pen which makes it very unhandy for navigating large images and that in turn makes a tablet almost useless for this purpose since I do a lot of navigating while drawing (my tablet is rather small, so I cant draw on a precisely on large area). Is there some way to disable the swipe for zoom or make it switchable?

**Comment by petebankhead** [comment] 2019-04-04 09:44
I don't know, but that is not the same issue as in v0.1.2.
Is the behavior different in v0.1.3?

**Comment by bjtho08** [comment] 2019-04-04 09:48
Yes, in 1.3.0 it does not zoom when swiping It just continues the motion of the canvas in the direction of the swipe as I would expect from a swiping gesture on a canvas larger than the screen.

**Comment by petebankhead** [comment] 2019-04-04 09:57
Ok. Attempted resolution in this commit https://github.com/petebankhead/qupath/commit/c7b07e5919aa76de19a81a71286dd8b434284017
Look out for changes in the next milestone release.

**Comment by bjtho08** [comment] 2019-04-04 10:40
Do you want me to test it out for you? I could try to build a version with that commit and run it right away

**Comment by petebankhead** [comment] 2019-04-04 10:44
As you wish. For me it is not urgent at all, the next milestone will not be the final release version and I need to work on many other things.

**Comment by bjtho08** [comment] 2019-04-04 11:36
That did the trick 😄 Now I can freely navigate with the pen without unexpected behavior (apart from slightly eratic movement if I use the move tool rather than pressing space while having another tool active). I would say you can consider this one solved once more.

**Comment by petebankhead** [comment] 2019-04-04 11:38
Thank you

**Closed by petebankhead** 2019-04-04 11:38 UTC
Labels: bug
