### ISSUE TITLE
Tissue detection using structure information

### ISSUE THREAD

**Issue by kwiechen** [qupath/qupath#657] opened 2021-01-03 14:53 UTC
Hello,

I have tried tissue detection using the "Simple Tissue Detection (deprecated)" and "Create Thresholder" commands. The main problem here are often missing parts of adipose tissue. Is it possible to integrate another algorithm using structure information? Described for example in 
Bug, Daniel, Friedrich Feuerhake, und Dorit Merhof. „Foreground Extraction for Histopathological Whole Slide Imaging“. In Bildverarbeitung für die Medizin 2015, 419–424. Springer, 2015. http://link.springer.com/chapter/10.1007/978-3-662-46224-9_72.

I have added some lines of code for testing to "SimpleTissueDetection2.java". The Laplacian operator was replaced with the Canny edge detector and the floodFill steps by findContours/fillPoly using the OpenCV bindings. 
[patch-tissue-extraction.zip](https://github.com/qupath/qupath/files/5761754/patch-tissue-extraction.zip)

Best regards,

Kai

**Comment by petebankhead** [comment] 2021-01-03 15:34
Hi Kai,

Thanks for the link, I only skimmed the first part of the paper. The method looks very interesting, I'll give some more thought about if/how it could be added to QuPath.

In the meantime, you can already integrate whatever algorithms you like via scripting (in Groovy) or creating a Java extension. Changing/adding core algorithms raises a lot more complications in terms of user expectations and reproducibility (QuPath has thousands of users...), not to mention maintenance, and increasingly we need to think carefully about algorithms that handle images with different numbers of channels.

Note that you can also use [pixel classification](https://qupath.readthedocs.io/en/latest/docs/tutorials/pixel_classification.html), which provides more sophisticated options than simply thresholding.

I'd suggest reimplementing your changes as either a script or extension. Also, since this isn't a bug in QuPath, I will close the issue - the best place to discuss such things is the forum at http://forum.image.sc/tag/qupath

Best wishes,

Pete

**Closed by petebankhead** 2021-01-03 15:34 UTC

**Comment by kwiechen** [comment] 2021-01-03 17:30
Hi Pete,

I have used the code from "Simple Tissue Detection" for demonstration
purposes because I have no experience in Java (and Groovy too) development
at all. The few lines of demo code are simply placed between your ui/image
extraction code and the transformation of the tissue area mask to an
annotation.
Is it possible to reuse this module code and transfer to an extension or a
script?

Best regards,

Kai



Am So., 3. Jan. 2021 um 16:34 Uhr schrieb Pete <notifications@github.com>:

**Comment by petebankhead** [comment] 2021-01-03 18:00
Yes, for example see https://qupath.readthedocs.io/en/latest/docs/scripting/overview.html#working-with-opencv
There are many more scripting discussions on the forum.

**Comment by kwiechen** [comment] 2021-01-03 18:48
I will give it a try - the QuPath script editor is a bit limited. Is there
an alternative with syntax checking/intellisense ....

Am So., 3. Jan. 2021 um 19:01 Uhr schrieb Pete <notifications@github.com>:

**Comment by petebankhead** [comment] 2021-01-03 18:53
https://forum.image.sc/search?q=%22qupath%22%20%22intellij%22

**Comment by kwiechen** [comment] 2021-01-10 18:04
Hello,

I am trying to run the Tissue detection using structure information as a
groovy script ending with a binary downsampled mask. I am struggling
converting the mask information back to a QuPath annotation. Can you please
give me a hint?

Best regards,

Kai

Am So., 3. Jan. 2021 um 19:53 Uhr schrieb Pete <notifications@github.com>:

**Comment by petebankhead** [comment] 2021-01-10 18:21
As I mentioned in my first reply, the best place to discuss questions about QuPath is at http://forum.image.sc/tag/qupath for questions - I suggest posting your script there.

GitHub issues is only intended for bug tracking and we are trying not to have questions in multiple places.
