### ISSUE TITLE
Feature request: Make script editor window non-modal and minimizeable

### ISSUE THREAD

**Issue by skalteis** [qupath/qupath#494] opened 2020-05-21 15:38 UTC
## Bug report

**Describe the bug**
Currently (at least on Windows) the script editor window is quasi-modal which means it does not show up as a separate window in the task bar and minimizing the window is not possible. It's either opened and on top of the main window or completely closed.

I think this is a bit of a workflow hindrance. Personally, I can work around by moving the script editor window to a second monitor but let's assume, someone is working on a script using only one screen and wants to add an annotation to the current image manually: They would have to either close the script editor completely or grab the window and move it out of the way. However, I think the more common UI workflow would be either quickly minimizing the script editor or ALT-TAB-ing between the windows. 

**Expected behavior**
Minimizable and non-modal script editor window

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - QuPath Version 0.2.0-m12

**Comment by petebankhead** [comment] 2020-05-21 16:22
The stage is not modal, but it has an owner (the main QuPath window). If it does not have an owner, then it will often fall behind the main window - which is extremely annoying. If it has `alwaysOnTop(true)` then it appears on top of other applications, which is worse.

We are dependent upon JavaFX for this behavior.
Can you point to a way to achieve the effect that you want with JavaFX?

If not, I would like to close this issue because it is not a bug and it is not something that we can/will address.

**Comment by skalteis** [comment] 2020-05-21 17:57
I am not familiar with JavaFX, I am afraid.
The way you describe it sounds to me that I would prefer a non-main-window-owned script editor window, possibly with automatic rising and focusing when calling "Automate -> Show script editor" if the window is already present and on initial creation.
It would also allow the platform's window manager to do its job.

That said it's of course only a - probably highly subjective - suggestion, so feel free to close. :-)

**Comment by petebankhead** [comment] 2020-05-21 18:10
I admit I don't entirely understand why setting the owner in JavaFX results in the minimize button being disabled... but seemingly it does.

Alas, I have tried it without setting the main window as the owner and I find the disappearing stage much too confusing and infuriating... so I'm afraid I think it has to stay. In particular, I think it would be harder to work with on a single laptop screen if the script editor can fall behind the main window... at least for most users, who might not typically be the Alt-Tab kind.

Also, the script editor in m12 indicates whether or not the script is running... which generally ought to be visible to the user.

**Closed by petebankhead** 2020-05-21 18:10 UTC
