### ISSUE TITLE
Pixel classifier fails with too many features

### ISSUE THREAD

**Issue by MarkZaidi** [qupath/qupath#947] opened 2022-04-07 16:34 UTC
## Bug report

**Describe the bug**
An attempt to train a pixel classifier using 27 channels X 12 features X 2 scales, with annotations spanning over 38 images did not succeed, and threw the following error (see end of post). Reducing either the number of channels, features, or scales would allow the pixel classifier to be trained. Images were non-pyramided, ~1000x1000 pixel, 32 bit floating point IMC data with a total of 37 channels (27 of which to be used in the pixel classifier). Unfortunately, I can't share the exact images that caused this error to occur.

My guess is that this is actually an issue with OpenCV , given the exception `OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\core\src\channels.cpp:141: error: (-215:Assertion failed) i1 >= 0 && j < ndsts && dst[j].depth() == depth in function 'cv::mixChannels'`

OpenCV's mixChannels: https://docs.opencv.org/3.4/d2/de8/group__core__array.html#ga51d768c270a1cdd3497255017c4504be

For now, I've been reducing the number of channels passed, which gives me a training accuracy of ~88%. But it would be great to train on all available data, and see what the variable importance is of each feature and channel.

**To Reproduce**
1. Create a project with ~143 IMC images
2. Annotate structures within ~38 images with 5 different classifications of annotations
3. Open a non-annotated image
4. Attempt to train a pixel classifier using all channels, scales, and features, loading training from other annotated images in the project.
5. Click "Live Preview", note the error at the end of the post.

**Expected behavior**
A pixel classifier should be trained, and a preview should be applied to the currently loaded image

**Desktop (please complete the following information):**
 - OS: Windows 10, 32-thread processor, 127/128 Gb RAM allocated for QuPath, ~500 Gb SSD storage for tile cache
 - QuPath Version 0.3.2

**Additional context**
Error log:
```
12:10:44.040 [JavaFX Application Thread] [INFO ] q.p.g.c.ml.PixelClassifierPane - Creating training data from 38 images
12:10:44.953 [JavaFX Application Thread] [ERROR] q.p.g.c.ml.PixelClassifierTraining - Error requesting features for ImageOp server: ImageData: Other, xxxx___ROI8_ROI_008.ome.tiff - ROI8_ROI_008.ome {"colorTransforms":[{"channelName":"Pr(141)_141-SMA"},{"channelName":"Nd(142)_142Nd-CD19"},{"channelName":"Nd(143)_143Nd-Vimentin"},{"channelName":"Nd(144)_144Nd-cd14"},{"channelName":"Nd(146)_146NdCD16"},{"channelName":"Nd(148)_148-Pan-Ker"},{"channelName":"Sm(149)_149Sm-CD11b"},{"channelName":"Sm(152)_152Sm-CD45"},{"channelName":"Sm(154)_154Sm-CD11c"},{"channelName":"Gd(155)_155Gd-FoxP3"},{"channelName":"Gd(156)_156Gd-CD4"},{"channelName":"Gd(158)_158Gd-E_Cadherin"},{"channelName":"Tb(159)_159Tb-CD68"},{"channelName":"Gd(160)_160Gd-Vista"},{"channelName":"Dy(161)_161Dy-CD20"},{"channelName":"Dy(162)_162Dy-CD8a"},{"channelName":"Er(166)_166Er-CD45RA"},{"channelName":"Er(167)_167Er-GranzymeB"},{"channelName":"Er(168)_168Er-Ki67"},{"channelName":"Tm(169)_169Tmp-CollagenI"},{"channelName":"Er(170)_170Er-CD3"},{"channelName":"Yb(171)_171Yb-HistoneH3"},{"channelName":"Yb(173)_173Yb-CD45RO"},{"channelName":"Yb(174)_174Yb-HLA-DR"},{"channelName":"Lu(175)_175Lu-Beta2M"},{"channelName":"Yb(176)_176Yb-Nak-ATPase"},{"channelName":"Ir(193)_193Ir-NA2"}],"op":{"type":"op.core.split-merge","ops":[{"type":"op.filters.multiscale","features":["GAUSSIAN","LAPLACIAN","WEIGHTED_STD_DEV","GRADIENT_MAGNITUDE","STRUCTURE_TENSOR_EIGENVALUE_MAX","STRUCTURE_TENSOR_EIGENVALUE_MIN","STRUCTURE_TENSOR_COHERENCE","HESSIAN_DETERMINANT","HESSIAN_EIGENVALUE_MAX","HESSIAN_EIGENVALUE_MIN"],"sigmaX":4.0,"sigmaY":4.0},{"type":"op.filters.multiscale","features":["GAUSSIAN","LAPLACIAN","WEIGHTED_STD_DEV","GRADIENT_MAGNITUDE","STRUCTURE_TENSOR_EIGENVALUE_MAX","STRUCTURE_TENSOR_EIGENVALUE_MIN","STRUCTURE_TENSOR_COHERENCE","HESSIAN_DETERMINANT","HESSIAN_EIGENVALUE_MAX","HESSIAN_EIGENVALUE_MIN"],"sigmaX":8.0,"sigmaY":8.0}]}}: x=0, y=0, w=800, h=848, z=0, t=0, downsample=4
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\core\src\channels.cpp:141: error: (-215:Assertion failed) i1 >= 0 && j < ndsts && dst[j].depth() == depth in function 'cv::mixChannels'

        at qupath.lib.images.servers.AbstractTileableImageServer.getTile(AbstractTileableImageServer.java:226)
        at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:287)
        at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:60)
        at qupath.process.gui.commands.ml.PixelClassifierTraining$TileFeatures.ensureFeaturesCalculated(PixelClassifierTraining.java:440)
        at qupath.process.gui.commands.ml.PixelClassifierTraining$TileFeatures.<init>(PixelClassifierTraining.java:429)
        at qupath.process.gui.commands.ml.PixelClassifierTraining.getTileFeatures(PixelClassifierTraining.java:402)
        at qupath.process.gui.commands.ml.PixelClassifierTraining.updateTrainingData(PixelClassifierTraining.java:189)
        at qupath.process.gui.commands.ml.PixelClassifierTraining.createTrainingDataForLabelMap(PixelClassifierTraining.java:343)
        at qupath.process.gui.commands.ml.PixelClassifierTraining.createTrainingData(PixelClassifierTraining.java:332)
        at qupath.process.gui.commands.ml.PixelClassifierPane.doClassification(PixelClassifierPane.java:923)
        at qupath.process.gui.commands.ml.PixelClassifierPane.updateClassifier(PixelClassifierPane.java:813)
        at qupath.process.gui.commands.ml.PixelClassifierPane.updateClassifier(PixelClassifierPane.java:806)
        at qupath.process.gui.commands.ml.PixelClassifierPane.updateFeatureCalculator(PixelClassifierPane.java:731)
        at qupath.process.gui.commands.ml.PixelClassifierPane.lambda$initialize$5(PixelClassifierPane.java:279)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8792)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
        at com.sun.glass.ui.View.notifyMouse(View.java:943)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\core\src\channels.cpp:141: error: (-215:Assertion failed) i1 >= 0 && j < ndsts && dst[j].depth() == depth in function 'cv::mixChannels'

        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
        at qupath.lib.images.servers.AbstractTileableImageServer.getTile(AbstractTileableImageServer.java:222)
        ... 58 common frames omitted
Caused by: java.lang.RuntimeException: OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\core\src\channels.cpp:141: error: (-215:Assertion failed) i1 >= 0 && j < ndsts && dst[j].depth() == depth in function 'cv::mixChannels'

        at org.bytedeco.opencv.global.opencv_core.mixChannels(Native Method)
        at qupath.opencv.tools.OpenCVTools.mergeChannels(OpenCVTools.java:413)
        at qupath.opencv.ops.ImageOps$Core$SplitMergeOp.transformPadded(ImageOps.java:2511)
        at qupath.opencv.ops.ImageOps$Core$SplitMergeOp.apply(ImageOps.java:2470)
        at qupath.opencv.ops.ImageOps$ChannelImageDataOp.apply(ImageOps.java:425)
        at qupath.opencv.ops.ImageOpServer.readTile(ImageOpServer.java:98)
        at qupath.lib.images.servers.AbstractTileableImageServer.lambda$getTile$0(AbstractTileableImageServer.java:213)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at qupath.lib.images.servers.AbstractTileableImageServer.getTile(AbstractTileableImageServer.java:217)
        ... 58 common frames omitted
```

**Comment by MichaelSNelson** [comment] 2022-04-07 16:42
That is a very large classifier. Do you get the same error with both ANN and Decision Trees? When removing one scale?

**Comment by petebankhead** [comment] 2022-04-07 17:40
Hi @MarkZaidi I agree with @MichaelSNelson that that sounds like a very large classifier... large enough that I think it would be reasonable for QuPath not to support it, although ideally it wouldn't fail with an exception.

I can't really feasibly use the 'steps to reproduce'. Is there any chance you can replicate the problem with a more manageable/minimal dataset - preferably of publicly-accessible images?

**Comment by MarkZaidi** [comment] 2022-04-07 17:57
> That is a very large classifier. Do you get the same error with both ANN and Decision Trees? When removing one scale?
Yep, I get the same error for both ANN and Decision Trees. When I drop scales until one succeeds, the other succeeds also.

>Is there any chance you can replicate the problem with a more manageable/minimal dataset - preferably of publicly-accessible images?
Understandable; I'm working on creating a dataset from images that be publicly available regardless at the I2K conference. Will post a link shortly.

**Comment by MichaelSNelson** [comment] 2022-04-07 18:20
This error (and the reduction in variables allowing the classifier to work) brings to mind something I batted around in my head but never formalized as a feature request. Often, many if not most of the features fed into a classifier are nearly unused. How difficult would it be to code the extraction of the top variable combinations (to some N) from the decision trees "rate my variables" list? At the moment, adding in one new scale propogates across all features and channels, even if I knew I only wanted to use a particular low res scale with one marker.

I am not sure how practical coding an option like that might be, but it could streamline classifiers significantly in situations like this one.

**Comment by MarkZaidi** [comment] 2022-04-07 18:23
@MichaelSNelson @petebankhead I've sent you a download link on the forums to a QuPath project and images that I'm able to reproduce the bug with, about 92 Mb in size. To reproduce the error, train a pixel classifier using all scales, features, and channels available, loading training from all 3 images in the project:
![image](https://user-images.githubusercontent.com/52012166/162270961-33456355-318c-403c-8afc-151085a78d94.png)
Thanks again for all your help!

**Comment by MarkZaidi** [comment] 2022-04-07 18:38
> This error (and the reduction in variables allowing the classifier to work) brings to mind something I batted around in my head but never formalized as a feature request. Often, many if not most of the features fed into a classifier are nearly unused. How difficult would it be to code the extraction of the top variable combinations (to some N) from the decision trees "rate my variables" list? At the moment, adding in one new scale propogates across all features and channels, even if I knew I only wanted to use a particular low res scale with one marker.
> 
> I am not sure how practical coding an option like that might be, but it could streamline classifiers significantly in situations like this one.

Under the Advanced Options, there is the ability to perform PCA dimensionality reduction. My understanding is that it computes a PCA variance "score" for each feature (a feature being a unique combination between a scale X convolution X channel), sorts the features by their score, and selects the top _n_ features that account for _m_% of variance, as specified in "PCA Retained Variance". But as you mentioned, there's not really a way to control this feature augmentation to be more heavily weighted on a specific channel.
![image](https://user-images.githubusercontent.com/52012166/162272015-63b7051c-a9b4-4e26-8579-0dc5173cab6c.png)

The other option is to check "Compute Variable Importance" in the classifier parameters, however not all model types have this as an option. Still, I usually use this as a first-pass pruning of what channels to use for training each classifier
![image](https://user-images.githubusercontent.com/52012166/162272798-9a94e40f-eee4-4e43-9dee-9aa2b5480f61.png)

One way of potentially implementing feature scoring across all models would be to compute various descriptive statistics of the feature across each class of an annotated area, and find which features have the greatest variance across classes (or some other metric such as fold change). I've been working on something similar using external object classifiers such as XGBoost, where I can compute the variable importance for each cell measurement, and find the sum importance of all features relating to a specific channel or feature set (e.g. mean cell intensity)

**Comment by MichaelSNelson** [comment] 2022-04-07 19:01
Ah, good call, that is exactly what I was looking for in terms of the Decision trees Compute Variable Importance (had been on my phone and could not look it up), but had not considered the PCA in the Advanced options. For all that I always balance class weights, I had overlooked that option.

**Comment by MichaelSNelson** [comment] 2022-04-07 19:13
It definitely seems to be entirely a result of the length of the variables vector/string/etc. Even reducing the Training Data - Maximum samples to 5, I still get the same error at the same number of variables. 
In the case of the provided data set, that occurs between two and three "Scales" being selected, and it does not matter which scales are selected. 

Attempting to use the PCA option does not change the result, probably because it needs to _start_ with the complete set of different measurements, and fails _there_ rather than after PCA when using the reduced set.

Loading data from a single image also results in the error.

**Comment by petebankhead** [comment] 2022-04-07 19:29
Ok, so I've learned that OpenCV has a maximum number of channels, defined as `CV_CN_MAX`. That's set as 512, so any attempt to exceed that will fail.

The most QuPath can do is provide a more informative error message.

**Comment by MarkZaidi** [comment] 2022-04-07 19:43
> Ok, so I've learned that OpenCV has a maximum number of channels, defined as `CV_CN_MAX`. That's set as 512, so any attempt to exceed that will fail.
> 
> Without a major rewrite of the pixel classifier, the most QuPath can do is provide a more informative error message.

Sounds reasonable, I wouldn't expect most classifiers to benefit from using that many channels, given that they're all derived from a few dozen IHC channels at most.

**Comment by petebankhead** [comment] 2022-04-07 20:01
I'll leave this issue open until either a more informative error is displayed (but that's a little awkward because of where in the code it occurs) and/or the limitation is added to the documentation.

**Comment by saudet** [comment] 2022-04-08 01:23
BTW, the C++ API of PyTorch has no such limitations when it comes to this kind of semantic segmentation, and we can easily use it from Java: https://github.com/bytedeco/javacpp-presets/tree/master/pytorch

There is some sample code in C++ available here: https://github.com/AllentDan/LibtorchSegmentation

@HGuillemet might have some sample code in Java to offer.

However, I don't believe it supports algorithms like logistic regression and SVM...

**Comment by petebankhead** [comment] 2022-04-13 16:54
I'll close this because https://github.com/qupath/qupath/pull/951 should now display a sensible error notification when attempting to use more features than OpenCV can merge.

**Closed by petebankhead** 2022-04-13 16:54 UTC
Labels: wontfix
