### ISSUE TITLE
Issue staring QuPath 0.2.0 m9 or m10

### ISSUE THREAD

**Issue by ajerusalmi** [qupath/qupath#458] opened 2020-04-28 02:19 UTC
getting Failed to launch JVM error.  Can open m8 without problems
Thanks

![image](https://user-images.githubusercontent.com/62674450/80439704-1cc05600-88d5-11ea-95fe-ebbe661cc4ed.png)

**Comment by Svidro** [comment] 2020-04-28 02:29
Have you tried removing the Weka extension causing the error?

**Comment by petebankhead** [comment] 2020-04-28 04:37
@ajerusalmi the error is caused by the old Weka extension being installed. This is compatible with v0.1.2, but not v0.2.0.

Two things you can do:
* delete the Weka extension; to find its location, go to *Edit &rarr; Preferences* and check the 'QuPath user directory'
* use *Edit &rarr; Reset preferences* to reset the location of the user directory in QuPath, so the extension will not be found.

I will close this issue since it is not a bug, however a change has been made for v0.2.0-m11 to enable QuPath to recover better in cases like this, see https://github.com/qupath/qupath/issues/454

**Closed by petebankhead** 2020-04-28 04:37 UTC

**Comment by ajerusalmi** [comment] 2020-04-28 13:18
Thank you

Alan
