### ISSUE TITLE
Images do not open in QuPath 0.2.0-m3

### ISSUE THREAD

**Issue by r-mvl** [qupath/qupath#348] opened 2019-08-04 16:22 UTC
## Bug report

**Describe the bug**
I installed the last version of QuPath (0.2.0-m3) and tried creating a project and feed images to the project. Unfortunately the images do not seem to add to the project and the project remains empty. This was not happening before so I assume it's just a bug... I work with .scn fluorescent images in this case.

**Desktop (please complete the following information):**
 - OS: macOS and windows 
 - QuPath Version 0.2.0-m3

**Comment by petebankhead** [comment] 2019-08-04 16:28
I don't know how to replicate the issue. I have just created a project on Windows in m3, and added the fine.scn image from https://github.com/qupath/qupath/issues/300 without problems.

Have you checked under _View &rarr; Show log_ for further information?

**Comment by r-mvl** [comment] 2019-08-04 17:49
I've repeated the issue several times but not always (I know this doesn't make sense but I don't know how to explain it). Here is an example of error message that I have been getting when it has not worked:

```
INFO: Bio-Formats version 6.2.0
INFO: Loaded extension Bio-Formats server options (Bio-Formats 6.2.0) (17 ms)
INFO: Loaded extension Experimental commands (9 ms)
INFO: Loaded extension ImageJ extension (49 ms)
INFO: Loaded extension JPen extension (15 ms)
INFO: Loaded extension OpenCV extensions (2 ms)
INFO: Loaded extension Rich script editor extension (161 ms)
INFO: OpenSlide version 3.4.1
INFO: Selected style: null
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: Project set to Project: 190804
WARN: Unable to obtain full image format info for file:/C:/pathtoimage***.scn (null)WARN: Unable to open file:/C:/pathtoimage***.scn with OpenSlide: Couldn't locate TIFF directory for quickhash
WARN: Unable to open UriImageSupport (class qupath.lib.images.servers.openslide.OpenslideServerBuilder) support=2.5builders=1
WARN: Unable to open file:/C:/pathtoimage***.scn with OpenSlide: Couldn't locate TIFF directory for quickhash
```

Seems like it tried to open with openslide while it should have used bioformats?

Another weird behaviour (not sure if this is intended) of the new version: if I drag an drop fluorescent images (.scn or .vsi) (not tried with chromogenic) to qupath without having pre-created a project, it only opens the label/macro image without letting me access to higher resolution images....

**Comment by Svidro** [comment] 2019-08-04 18:00
Have you tried forcing it to use BioFormats in Preferences?
Do the exact same images fail in 0.1.2 as 0.2.0m3, or are you just using the same file type?

Some complex and proprietary formats require a project now (m2 and m3 I think), several other posts scattered across here and the forums refer to it.

**Comment by r-mvl** [comment] 2019-08-04 19:24
Yes forcing doesn't really change anything. Something odd going on... I eventually manage to open things and create a project to work on but sometimes it requires several attempts of closing the software and opening it again.. bit random.
I've tried the same files on 0.2.0 m2 and m3. This happens only in m3.

Regarding the projects, would it not be possible for QuPath to create some sort of temporary project automatically when it requires it? which would be deleted if the image gets closed.

**Comment by Svidro** [comment] 2019-08-04 20:20
Only other thought I have regarding intermittent errors is that some people storing image files, especially large ones, on network locations have run into trouble at times. And with active directory, your desktop might be a network location. If all of your files are on your hard drive, I'm out of ideas, good luck!

**Comment by r-mvl** [comment] 2019-08-04 22:17
Yes I originally thought that could be the reason then I moved all images to the hard drive and got similar behaviours... I realise this is not very helpful as I cannot reliably reproduce it myself 100% of the time.

**Comment by Svidro** [comment] 2019-08-04 22:32
Do you pick up any extra information using the debug launcher that comes with m3?
![image](https://user-images.githubusercontent.com/23145209/62430148-1944c900-b6cd-11e9-973f-f1be768ed901.png)

**Comment by petebankhead** [comment] 2019-08-05 07:31
> Another weird behaviour (not sure if this is intended) of the new version: if I drag an drop fluorescent images (.scn or .vsi) (not tried with chromogenic) to qupath without having pre-created a project, it only opens the label/macro image without letting me access to higher resolution images....

There's an explanation [here](https://forum.image.sc/t/third-milestone-on-the-path-to-qupath-v0-2-0/27953/7).

> Yes forcing doesn't really change anything. Something odd going on... I eventually manage to open things and create a project to work on but sometimes it requires several attempts of closing the software and opening it again.. bit random.
I've tried the same files on 0.2.0 m2 and m3. This happens only in m3.

I might have seen similar behavior some weeks ago, but rarely and it hasn't reappeared for me so that I thought it was resolved. Basically, QuPath wasn't using Bio-Formats when it should have been... sometimes.

I haven't managed to find a way to reproduce it, but will keep looking.

In m3, the type of the ImageServer is stored in the project to ensure that the same one is used again in the future (i.e. not OpenSlide once, then Bio-Formats the next time). Therefore if it fails to get the right type the first time, the image won't open the next time either.

> Regarding the projects, would it not be possible for QuPath to create some sort of temporary project automatically when it requires it? which would be deleted if the image gets closed.

I think this has the potential to make things more confusing... in this case, I think a better solution is to present a dialog enabling the image to be selected whenever multiple images are in the same file _and_ a project is not being used (like when the Bio-Formats plugin is used with Fiji). But implementing this takes time I don't currently have.... and I'd rather encourage people to use projects anyway in general (although of course these need to work...).

**Comment by petebankhead** [comment] 2019-08-05 08:07
@r-mvl You could try the following script to investigate
```groovy
import qupath.lib.images.servers.*

FileFormatInfo.cache.clear()

// Directory containing files
def path = 'path/to/scn/files'

// Filter only scn files
def files = new File(path).listFiles().findAll{it.getName().endsWith('.scn')}

// Print available readers
for (builder in ImageServerProvider.getInstalledImageServerBuilders())
    print builder

for (f in files) {
    def uri = f.toURI()
    // Print all possible readers for the current file
    print ImageServerProvider.getServerBuilders(java.awt.image.BufferedImage, uri.toString()).size()
    // Print preferred reader
    print ImageServerProvider.getPreferredUriImageSupport(java.awt.image.BufferedImage, uri.toString())
}
```
I've tried a lot of files this morning and haven't been able to find any that fail... it remains mysterious :/

**Comment by petebankhead** [comment] 2019-08-10 15:01
Is this continuing to be troublesome? I'd still like to understand the cause / resolve the problem.

**Comment by petebankhead** [comment] 2019-08-11 20:07
I _might_ have found the issue! Or at least I found _an_ issue. It is addressed in the latest commit.

Basically, whenever setting the image type during image import, QuPath would generate a .qpdata file for each image _and_ synchronize_ the project. However because this initialization was done in parallel to make it faster, it meant that multiple threads could try to save the .qpproj file at the same time... and then at least one fail due to the file being locked. The outcome was that the image being added in that thread wouldn't be included in the project.

I'm not entirely certain this is the issue you've encountered and I think it should not affect m3 if you don't set the image type. I hope to have m4 online this week.

**Comment by r-mvl** [comment] 2019-08-12 18:56
I happened to me again today and your explanation is sound. It occurs somewhat randomly, and eventually would work after repetitive attempts to put the files in the project... not ideal! For example I had 7 images and it would only load 5 the first time, and then I'd have to add the 2 others subsequently. 
Also, for some reason it seems to never load any file if I do the following steps:
- create directory outside of QuPath (which will become the project directory)
- open qupath, create a project and select the directory just created
- drag and drop the files to the project in qupath
But if I dont "pre-create" the folder and only create it while creating the project, and use the "add images" button, then it seems to accept the files (or more files at a time at least).
I didn't get the chance to try the script you posted but will definitely try m4 when it's available!

**Comment by petebankhead** [comment] 2019-08-13 16:28
Good, I think. I have also seen the issue you describe when creating a new project, and I needed to add images twice.

It may also have been resolved by my recent changes; at least, I couldn't replicate it just now.

**Comment by r-mvl** [comment] 2019-08-20 21:16
I think the issue has been resolved in m4. I will close it and re-open if I notice this odd behaviour again in the future!

**Closed** 2019-08-20 21:16 UTC
Labels: bug

**Comment by reynoldscem** [comment] 2020-05-04 14:14
I appear to be getting this happen in 0.2.0-m11.

**Comment by petebankhead** [comment] 2020-05-04 14:22
@reynoldscem the source of this issue has been fixed. If you have a definite bug, please create an issue [here](https://github.com/qupath/qupath/issues/new?assignees=&labels=bug&template=bug_report.md&title=) following the template.

If you are unsure if you have found a bug or not, please open a discussion on http://forum.image.sc/tag/qupath with clear description fo precisely what you have tried and what happens (including any information from *View &rarr; Show log*).
