### ISSUE TITLE
m12 - Field of view now updated when selecting annotations

### ISSUE THREAD

**Issue by cfmoro** [qupath/qupath#502] opened 2020-05-23 21:15 UTC
Hi,

In previous versions, selecting an annotation on the Annotations panel made the displayed view to be updated (at any given zoom level) so the selected annotation was visible, which is very useful to quickly review them. This is (mostly) not happening in m12.

Best regards,
Carlos

**Comment by petebankhead** [comment] 2020-05-24 08:05
This should now happen if you double-click.

The reason is that the old behavior (automatically moving when the selected annotation changed) was sometimes really problematic.

One example of this was when using multiple viewers are open. When switching between viewers, if an object was selected then this could cause it to jump suddenly - which might even create annotations in the wrong place (depending upon which tool was active at the time).

**Comment by petebankhead** [comment] 2020-05-24 08:14
Does the double-clicking work for you?
Since this is intended behavior, I'd like to close the issue - but could revisit it if there's a better way to help reviewing annotations while avoiding the old problems with multiple viewers (possibly in v0.3.0, if it is a substantial change).

**Comment by cfmoro** [comment] 2020-05-24 09:36
Works perfectly, thanks a lot!

**Closed** 2020-05-24 09:36 UTC
Labels: bug
