### ISSUE TITLE
When running in script mode, runClassifier appears to retrain the classifier instead of loading

### ISSUE THREAD

**Issue by ConnorBarnhill** [qupath/qupath#343] opened 2019-07-25 18:46 UTC
## Bug report

**Describe the bug**
When running QuPath in command line/script mode, runClassifier appears to retrain the RTrees classifier. In the screenshot of logs below, note the 3.5 minute lag in timestamps before "Classifier trained with 281528 samples"

**To Reproduce**
We have a .qpclassifier model saved that is 91M. In the script we run runClassifier(); after cell detection

**Expected behavior**
Relatively fast scoring.

**Screenshots**
![image](https://user-images.githubusercontent.com/7959016/61900030-bdb75600-aeea-11e9-993e-bddfef876da1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - QuPath Version 0.1.3

**Comment by petebankhead** [comment] 2019-07-25 19:05
Yes, this is a known issue and intended behavior... but only because of a bug in OpenCV's Java bindings when QuPath was originally being developed, which meant any attempt to serialize a classifier was doomed to fail badly. Serializing the full training data and parameters required to rebuild the classifier was the only workaround I could find at the time.

This is no longer a blocker thanks to updates in OpenCV and the switch to use JavaCPP. I've started to create entirely separate wrappers to support serializing/deserializing classifiers using JSON in the context of pixel classification.

My proposed/intended fix is to use these with the detection classifier as well, but of course this will break backwards compatibility and I would therefore like to combine it with more thorough changes to how the detection classification works. Also, since the current approach is not critically broken I didn't want to start the task until everything was aligned to see it through to completion. Making the pixel classifier serializable/deserializable is a higher priority.

**Comment by petebankhead** [comment] 2019-07-25 19:08
If you're still at the 'building' stage, under the 'Advanced options' and 'More...' you can try the _Classify project images_ option. From recollection, I believe this doesn't rebuild the classifier per image.

Unfortunately there is no such option with 'Load classifier'. Conceivably it could be scripted to load the classifier once and apply it to all images in a project, but it would take some effort.

**Comment by Svidro** [comment] 2019-07-25 19:34
It's a bit amazing that you remember all of these things. I can barely keep track of scripts.

**Comment by ConnorBarnhill** [comment] 2019-07-26 03:33
@petebankhead Thanks for the quick response! This seems like a major piece of technical debt. Retraining a random forest would lead to a different model each time the classifier is loaded. The expectation as a user is that if I save a model I will have a deterministic result each time that model is loaded. This could have a nontrivial effect on reproducibility of results.

Are all of the classifiers retrained upon reloading, or just random forests?

**Comment by petebankhead** [comment] 2019-07-26 05:00
The bug was in the base class, therefore affected all OpenCV classifiers (see [here](https://stackoverflow.com/questions/42484908/error-while-saving-trained-svm-in-opencv-3-2-0-java) for a mention).

Do you actually find cases where classifiers are different upon reloading, or only expect that would be the case?

This is something I considered at the time and to the best of my knowledge all random number generators involved are seeded when necessary (within QuPath and OpenCV) and the classifiers _are_ reproducible. I have memories of running end-to-end analysis of TMAs via scripts, including reloading classifiers, and obtaining identical results.

If this is not the case that would of course be a more serious issue, but I am not aware of any instances where your expectation as a user would not be met for this reason.

**Comment by petebankhead** [comment] 2020-02-14 21:05
I will close this issue because it is no longer the case with the new object classifier in v0.2.0-m9.

**Closed by petebankhead** 2020-02-14 21:05 UTC
Labels: bug, enhancement
