### ISSUE TITLE
Positive Pixel Detection

### ISSUE THREAD

**Issue by cjpinelli** [qupath/qupath#611] opened 2020-09-30 15:20 UTC
Is it expected that running a positive pixel count on a larger area of interest (28824679 um^2) give the program troubles and essentially freeze up/crash the program? I am running it with an Intel i7 8 core 3GHx processor with 64GB ram.

Is there something I need to modify in the pixel count settings (eg. adjusting the downample factor)? Or is it just the nature of the request/analysis?

Thanks!

Chris

**Comment by melvingelbard** [comment] 2020-09-30 16:34
It all depends on different factors such as the `downsample` used and the size of your image (which might be more helpful if it is in terms of pixels, rather than microns) amongst other things. Also, the `Positive pixel count` is a deprecated command, and was replaced in most recent versions of QuPath, to which we strongly recommend updating. The pixel classifier might just do what you need!

I will close this issue with your permission as it is not a bug. Is that ok?
For questions and help, you can ask on the community forum, where you'll find answers and more guiding: https://forum.image.sc/tag/qupath

**Comment by petebankhead** [comment] 2020-09-30 16:36
@cjpinelli Yes, this is why it's in the 'Deprecated' menu in QuPath v0.2 -- the command doesn't scale well at all. It was originally written mostly for TMAs.

See https://qupath.readthedocs.io/en/latest/docs/tutorials/measuring_areas.html for information on thresholding, which is similar but a lot more flexible.

Apart from that... what @melvingelbard said, he was quicker than me :)

**Comment by cjpinelli** [comment] 2020-09-30 16:38
Thank you both! I will try the classifier instead. Thanks for the quick response!

**Closed** 2020-09-30 16:40 UTC
Labels: question (please use image.sc!)
