### ISSUE TITLE
Image Rotation

### ISSUE THREAD

**Issue by pathy007** [qupath/qupath#293] opened 2019-03-21 15:48 UTC
I use the software for high quality publication images. However, very often the scans are upside down and a 90 degree rotation is not enough to turn it correctly. It would be so helpful if this issue could be fixed.

**Comment by petebankhead** [comment] 2019-03-21 16:31
The current limited rotation is intentional and not a bug. There are several discussions about it, including here: https://forum.image.sc/t/rotating-view-in-qupath/23925

I have changed the label to enhancement as it is really a feature request. I do intend QuPath to support rotating images in 90 degree increments where this is decided at the beginning (i.e. before doing any annotations or creating any objects), as I think this is often needed. I've written most of the code but have a bit more work to do to get it into the user interface as a usable feature.

In the meantime, for publication images you can always rotate the resulting image in other software (e.g. ImageJ).

**Comment by pathy007** [comment] 2019-03-21 16:42
Thank you for all the efforts made!!!
Great software!
Best
Mark

Am 21.03.2019 um 17:31 schrieb Pete <notifications@github.com<mailto:notifications@github.com>>:


The current limited rotation is intentional and not a bug. There are several discussions about it, including here: https://forum.image.sc/t/rotating-view-in-qupath/23925

I have changed the label to enhancement as it is really a feature request. I do intend QuPath to support rotating images in 90 degree increments where this is decided at the beginning (i.e. before doing any annotations or creating any objects), as I think this is often needed. I've written most of the code but have a bit more work to do to get it into the user interface as a usable feature.

In the meantime, for publication images you can always rotate the resulting image in other software (e.g. ImageJ).

**Comment by petebankhead** [comment] 2019-07-24 11:18
This should have been addressed in [v0.2.0-m3](https://github.com/qupath/qupath/releases/tag/v0.2.0-m3)... but unfortunately it seems it wasn't. There's a 'rotate image' option when importing images, but at some point late fixes appear to have broken this.

Targeted again for v0.2.0-m4...

**Comment by petebankhead** [comment] 2019-08-21 11:47
Rotation on import is now included in v0.2.0-m4, see https://petebankhead.github.io/qupath/2019/08/20/fourth-milestone.html#more-options-when-importing-images-to-projects for details

**Closed by petebankhead** 2019-08-21 11:47 UTC
Labels: enhancement

**Comment by pathy007** [comment] 2019-08-21 16:46
Thank you!!!


Am 21.08.2019 um 05:48 schrieb Pete <notifications@github.com<mailto:notifications@github.com>>:


Rotation on import is now included in v0.2.0-m4, see https://petebankhead.github.io/qupath/2019/08/20/fourth-milestone.html#more-options-when-importing-images-to-projects for details
