### ISSUE TITLE
Only three channels can be separated in my mIHC data

### ISSUE THREAD

**Issue by huangzr123** [qupath/qupath#1711] opened 2024-12-01 13:13 UTC
Hello,
I am currently working with a multichannel mIHC dataset in TIFF format, which contains six channels. However, when I attempt to separate the channels in QuPath, I am only able to identify three channels (Green, Blue, and Red). For instance, in the image I am referring to, there is a white signal that is incorrectly categorized as a superposition of these three channels. I am seeking assistance on how to address this issue correctly.

Thank you in advance for your assistance.

Best regards，
Zurui
![微信截图_20241201211254](https://github.com/user-attachments/assets/f5606e8a-da87-4efc-ae2a-c4778613d2c8)

**Comment by petebankhead** [comment] 2024-12-01 14:42
It sounds like your image has been saved in an [RGB (red, green, blue) format](https://bioimagebook.github.io/chapters/1-concepts/4-colors/colors.html#rgb-images), not with the original pixel values.

The solution will probably be to save the image in a different format, or as a TIFF image using different setting. I can't give more specific advice as I don't know what software was used to write the image originally.

Because this is not a bug in QuPath, I will close this issue here - it would be better to discuss it on the forum at https://forum.image.sc/tag/qupath

**Closed by petebankhead** 2024-12-01 14:42 UTC
Labels: bug
