### ISSUE TITLE
Can not change maximum memory

### ISSUE THREAD

**Issue by bpuladi** [qupath/qupath#490] opened 2020-05-19 21:16 UTC
Under QuPath setup, the change of the maximum memory is not changeable. 
I tried to set it from 16 to 32 Gbyte, but nothing happens.

However, editing QuPath-0.2.0-m12.cfg directly works.

**Comment by petebankhead** [comment] 2020-05-19 21:34
What operating system are you using?

**Comment by petebankhead** [comment] 2020-05-20 06:08
I've tested this on two computers and found:

* It works for me on Windows
* It works from me on Mac if I build the code from source... but not if I use the installer

This makes me think it *might* be a permissions issue within the operating system, but I'm not sure. Any more info you can provide would be helpful.

In case it cannot be resolved, I've added documentation on setting the memory manually to
https://qupath.readthedocs.io/en/latest/docs/reference/faqs.html#why-can-i-not-set-the-maximum-memory

**Comment by bpuladi** [comment] 2020-05-20 07:24
A permission issue may be possible. I use Windows 10. 

That is the log output:
INFO: Starting QuPath with parameters: []
INFO: Reading config file C:\Research\Software\QuPath-0.2.0-m12\app\QuPath-0.2.0-m12.cfg
INFO: Setting JVM option to -Xmx28672M

After changing QuPath-0.2.0-m12.cfg manually, it works without any problems. I think it is a permission issue.

**Comment by petebankhead** [comment] 2020-05-20 11:38
Turns out it wasn't permissions - thanks for reporting the problem, it should now be fixed in the final release :)

**Closed by petebankhead** 2020-05-20 11:38 UTC
Labels: bug

**Comment by kaizen89** [comment] 2021-05-07 07:37
I can confirm that it was a permission issue on a MAC. But I was only able to edit the cfg file from the terminal.

**Comment by annamiko123** [comment] 2023-02-14 16:48
> I can confirm that it was a permission issue on a MAC. But I was only able to edit the cfg file from the terminal.

Can I ask how did you edited cfg file in terminal?

**Comment by kaizen89** [comment] 2023-02-14 17:10
> Can I ask how did you edited cfg file in terminal?
First, locate `.cfg` file. On a Mac, you’ll need to right-click on QuPath.app and choose Show package contents.
The config file is inside the Contents/app directory.
Open the terminal, type ` sudo nano pathtoqupath/QuPath-0.2.3.cfg`. Enter password and edit this line at the end:
`java-options=-XX:MaxRAMPercentage=50`. In my case I set it to 85 instead of 50 % of available RAM.

**Comment by annamiko123** [comment] 2023-02-15 16:43
> > Can I ask how did you edited cfg file in terminal?
> 
> First, locate `.cfg` file. On a Mac, you’ll need to right-click on QuPath.app and choose Show package contents. The config file is inside the Contents/app directory. Open the terminal, type ` sudo nano pathtoqupath/QuPath-0.2.3.cfg`. Enter password and edit this line at the end: `java-options=-XX:MaxRAMPercentage=50`. In my case I set it to 85 instead of 50 % of available RAM.

That's great. It worked! Thanks so much :)
