### ISSUE TITLE
Error when labelling with pen

### ISSUE THREAD

**Issue by trasse** [qupath/qupath#372] opened 2019-11-04 16:17 UTC
Dear Pete,

When trying to label a Z-Stack with a Dell Active Pen (MI8AH) everything works fine for 50-100 objects in multiple planes (using the polygon tool).

Then I get this error message:

ERROR: QuPath exception
ERROR: QuPath exception: Too many touch points reported
    at javafx.scene.Scene$ScenePeerListener.touchEventNext(Scene.java:2815)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleNextTouchEvent$26(GlassViewEventHandler.java:1324)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleNextTouchEvent$27(GlassViewEventHandler.java:1287)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleNextTouchEvent(GlassViewEventHandler.java:1286)
    at com.sun.glass.ui.View.handleNextTouchEvent(View.java:580)
    at com.sun.glass.ui.View.notifyNextTouchEvent(View.java:1055)
    at com.sun.glass.ui.TouchInputSupport.notifyNextTouchEvent(TouchInputSupport.java:142)
    at com.sun.glass.ui.win.WinGestureSupport.notifyNextTouchEvent(WinGestureSupport.java:58)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)
ERROR: QuPath exception

There is no crash. No data lost.
QuPath 0.2.0m5 (on Windows 10) "just" refuses to accept new input by my pen.
I can still go on using the mouse.
Thus, it is neither major nor urgent.

I also tested: If I save close & reopen I can continue with the same file and the pen.

Thanks a lot & Kind regards

Tobias

**Comment by petebankhead** [comment] 2019-11-04 16:30
Hi Tobias,

Everything in the stack trace relates to JavaFX - so I don't see anywhere where QuPath would be able to catch the error and do anything about it. A similar error was reported as a JavaFX bug but is apparently resolved [here](https://bugs.openjdk.java.net/browse/JDK-8095826).

I'll leave the issue open for a while in case any new info comes to light, but since I don't have a Dell Active Pen to test with, and it doesn't _seem_ to be a problem in QuPath itself, I'm not sure whether anything can be done about it on the QuPath side.

(If you could write a minimal JavaFX application that replicates the problem then it could be submitted as a JavaFX bug)

**Comment by trasse** [comment] 2019-11-04 17:23
Dear Pete,

Thanks a lot for the fast response!
You are right it seems related to that issue.

As the problem only occurs after labeling for quite a while 
(and is resolved by a new start of QuPath)
i thought QuPath might hand over to Java a variable on when to "forget" old points
or "how many to store". 

If not, I just stick to the two workarounds described above.
I can not write Java, but I guess the problem might be solved in future Java releases.

Thanks again & Kind regards

Tobias

**Comment by petebankhead** [comment] 2019-11-04 22:27
I think the 'points' it is referring to is completely separate from the points (vertices) that make up the shape - because the error seems to occur _before_ the input reaches QuPath.

Although in saying that I'm not entirely sure what it _is_ referring to.

**Comment by petebankhead** [comment] 2020-05-21 17:22
Closing this as I'm afraid I don't see anyway to address it in QuPath, and can't reproduce the problem (but then I don't have the right pen for that).

**Closed by petebankhead** 2020-05-21 17:22 UTC
Labels: bug
