### ISSUE TITLE
Problems using the brush tool to edit existing annotations in Version m10

### ISSUE THREAD

**Issue by lucahla** [qupath/qupath#456] opened 2020-04-25 12:27 UTC
## Bug report

**Describe the bug**
When using the brush tool, I can not add an area to or remove from existing annotations that were created using the „simple tissue detection“ command. This was possible with the same files yesterday when using the m9 version. Creating entirely new annotations with the brush tool does work, as well as using the brush tool to add to/remove from these new annotations. The existing annotations are of course all „unlocked“ and everything is as it was set to in m9.

**To Reproduce**
1. open a project that has an an image with existing annotations that were created using the „simple tissue detection“ command.
2. select one of the existing annotations (if not done already, right click the annotation and set it to „unlocked“ or do so for all annotations by using the annotations tab)
3. click on the brush tool or press „B“
4. try to edit the exisitng annotation while holding down Shift or CMD

**Expected behavior**
The annotations should be editable like this.

**Desktop:**
 - OS: macOS 10.14.6 on MacBook Air 2014, 1.4 GHz i5, 4GB RAM, Intel HD Graphics 5000
 - QuPath Version: 0.2.0-m10

**Comment by petebankhead** [comment] 2020-04-25 12:37
I can't replicate this - on my Mac, if the simple tissue detections have been unlocked then I can edit them using the brush tool as expected.

I am not sure what is the significance of shift/cmd here. Can the annotations be edited if these are not pressed?

**Comment by lucahla** [comment] 2020-04-25 12:45
It‘s really strange. But no, pressing or not pressing shift/cmd does not make any difference.
I just now discovered that this problem is only happening with some annotations but not with others in the same image... I therefore assume that the problem lies in corrupted project files or image files.

**Comment by petebankhead** [comment] 2020-04-25 12:46
Do you see any errors under *View &rarr; Show log*?
Does it happen with annotations that have been generated in m10, or only ones that have been generated earlier?

**Comment by lucahla** [comment] 2020-04-25 12:49
It did show an error message when it first happened, but not since then. The log shows it this way:

ERROR: Error updating ROI
    at org.locationtech.jts.geomgraph.EdgeEndStar.propagateSideLabels(EdgeEndStar.java:286)
    at org.locationtech.jts.geomgraph.EdgeEndStar.computeLabelling(EdgeEndStar.java:122)
    at org.locationtech.jts.operation.relate.RelateComputer.labelNodeEdges(RelateComputer.java:290)
    at org.locationtech.jts.operation.relate.RelateComputer.computeIM(RelateComputer.java:125)
    at org.locationtech.jts.operation.relate.RelateOp.getIntersectionMatrix(RelateOp.java:112)
    at org.locationtech.jts.operation.relate.RelateOp.relate(RelateOp.java:57)
    at org.locationtech.jts.geom.Geometry.relate(Geometry.java:1026)
    at org.locationtech.jts.geom.Geometry.intersects(Geometry.java:758)
    at qupath.lib.gui.viewer.tools.BrushTool.getUpdatedObject(BrushTool.java:340)
    at qupath.lib.gui.viewer.tools.BrushTool.mouseDragged(BrushTool.java:298)
    at qupath.lib.gui.viewer.tools.AbstractPathTool.handle(AbstractPathTool.java:413)
    at qupath.lib.gui.viewer.tools.BrushTool.handle(BrushTool.java:65)
    at qupath.lib.gui.viewer.tools.AbstractPathTool.handle(AbstractPathTool.java:62)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1885)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

The annotations were all created using earlier versions (all of them were created in m9). Annotations that I create in m10 are deitable.

**Comment by petebankhead** [comment] 2020-04-25 13:13
Hmm, not sure but it might have been collateral damage from the other recent ROI/Geometry fixes, eg https://github.com/qupath/qupath/issues/429

I'll look out for it, but I haven't seen the problem myself and would probably need an example of a broken ROI/way to reproduce the error to be able to do anything about it.

**Comment by lucahla** [comment] 2020-04-25 14:22
Okay, I see. No worries, for me personally it is not a big thing bothering me, but I just stumbled over it and thought I would let me know, since you‘re looking for bugs as this before next week‘s new version. Thank you!

**Comment by petebankhead** [comment] 2020-05-21 17:27
I'll close amidst my issue-closing spree ahead of the v0.2.0 release because it traced back to an invalid geometry.

Each new milestone in recent months has tried to reduce the occurrence of these issues, but since they are rather intermittent it is difficult to be sure when they have been fixed or not.

Please reopen (or create a new issue) if you are provide a troublesome example that fails in the latest release.

**Closed by petebankhead** 2020-05-21 17:27 UTC
Labels: bug
