### ISSUE TITLE
Error loading training objects

### ISSUE THREAD

**Issue by michaelmooreny** [qupath/qupath#360] opened 2019-09-11 18:14 UTC
## Bug report

**Describe the bug**
I have saved training points in a QuPath object and when I try to load them into a new classifier at first it shows that the points have been loaded but then when I press the "build and apply" button the number of training object becomes 0.

**To Reproduce**
1. Go to create new classifier
2. Click on load training objects
3. Click build and apply

**Expected behavior**
Have the number of training objects not become 0 and have loaded points become part of new classifier. 

**Screenshots**

![pic1](https://user-images.githubusercontent.com/10617598/64722894-599e2080-d49d-11e9-93d6-cc034db12dfc.png)

![pic2](https://user-images.githubusercontent.com/10617598/64722898-5c991100-d49d-11e9-84a1-61ba0156e232.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - QuPath Version  [0.1.2]

**Comment by petebankhead** [comment] 2019-09-11 18:26
If you want to continue training a classifier using objects across multiple images, be sure to retain the objects when you move from one image to another. QuPath should prompt you when switching images (this may only work in a project).

See https://github.com/qupath/qupath/issues/57 for more information.

I'll close this issue because as far as I can tell it isn't a bug, but rather intended behavior. Please feel free to reopen if you find otherwise.

Note that https://forum.image.sc/tags/qupath is the best place for asking questions about using the software.

**Closed by petebankhead** 2019-09-11 18:26 UTC
Labels: bug

**Comment by Svidro** [comment] 2019-09-11 18:27
When you say load training objects, do you mean the Rebuild Training from Project option under More, or something else?

**Comment by petebankhead** [comment] 2019-09-11 18:38
I missed that, I don't understand the workflow enough and there may be a bug here. But there may also be a workaround through the link I posted.

The medium-term plan is to replace the detection classifier (building on the milestones, not v0.1.2) so if there's a workaround at all for training across images then I would not plan to fix this issue but rather invest the time in developing the improved command (both for reasons outlined in https://github.com/qupath/qupath/issues/343 and to better unify the code with the pixel classifier).

**Comment by michaelmooreny** [comment] 2019-09-11 18:49
@petebankhead in this particular case I am not attempting to use saved training objects from multiple images. These training points that I have saved are from this image but just during a different training session, therefore I do think this is a bug.

I would like to be able to combine multiple training objects from different images in the future, is the best way to go about this the script you gave in https://github.com/qupath/qupath/issues/256 ?

**Comment by petebankhead** [comment] 2019-09-11 18:55
It has been a _very_ long time since I wrote that code, but it _might_ be designed not to use previous training objects if they came from an image with the same name as the image that is open... under the assumption that this could result in duplicating training objects.

I'm really not sure any more. I think there are lots of things not to like about the method of reloading classifiers/training data, which is why I'd rather replace than battle with the old code.

In the meantime, you could indeed try that script, or the _Rebuild training from project_ mentioned in https://github.com/qupath/qupath/issues/57#issuecomment-288491139

**Comment by michaelmooreny** [comment] 2019-09-11 18:59
@petebankhead how are the .qptrain files meant to be used right now? It was my understanding that for a given image you could save training objects and then reload them, is this not the case?

**Comment by petebankhead** [comment] 2019-09-11 19:01
I would need to check the code.... I wrote them, probably for that reason, but I think I haven't used them myself in at least 3 years. I always rebuild the training from the project when I need it.

**Comment by petebankhead** [comment] 2019-09-11 19:04
This is the relevant bit: https://github.com/qupath/qupath/blob/b4a442535b2bd8169aacf16ecf6aac61004971b0/qupath-gui-fx/src/main/java/qupath/lib/gui/panels/classify/ClassifierBuilderPanel.java#L327

From recollection, the `retainedObjectsMap` is exactly what is used whenever interactively training. It overrides whatever is stored for the image that is currently open so that it always reflects the current annotation state for that image.

**Comment by michaelmooreny** [comment] 2019-09-11 19:49
@petebankhead so then it is expected that whenever you load .qptrain objects it they will be overwritten? Doesn't that make them impossible to use? Also I seem to recall being able to do load these saved training points in the past through creating a new detection classifier which is why I am also confused. I do have a feeling this is a bug and not the way the code is written because of that.

**Comment by petebankhead** [comment] 2019-09-11 19:55
> so then it is expected that whenever you load .qptrain objects it they will be overwritten? 
_If_ the image currently open is the same as the one with the old points.

> Doesn't that make them impossible to use?
It shouldn't if the saved annotations are for different images. The logic is: Use the 'retained' objects (from other images), _unless_ the retained objects relate to the image currently opened, in which case use the current objects instead.

That is, as best I recall, the intended behavior.

**Comment by Svidro** [comment] 2019-09-11 19:56
Huh. Learn something new every day. I didn't even realize that file type existed. But really, rebuilding from project is probably the way to go, and it is best to train a classifier across multiple images anyway to account for the most variation you can.

I would also recommend always keeping a classifier "version" of the project (either save the qpdata files or make two projects) so that once you start running scripts, you can always go back to the exact project and objects you were using to create the classifier.

**Comment by petebankhead** [comment] 2019-09-11 20:03
The purpose (as far as I recall) is to handle the case whereby the user wants to continue training a classifier for a project, which can include adding annotations to previously-annotated images (or removing annotations). In this case, annotations must not be double-counted.

But since _Rebuild training from project_ provides an alternative way to achieve the same outcome, the command is no longer very useful.

**Comment by michaelmooreny** [comment] 2019-09-11 20:04
@petebankhead is there any way to work around this so that I can use saved training points on the same image that they were created in. 

@Svidro I agree it does seem after some research like this might be the most reliable method. At the same time however doesn't this make it harder to train on a very large number of images? In order to train on 50 images I would need to create a project with 50 images and save the data in each project. It is my understanding and experience that these large project are much slower than smaller ones and frequently crash.

**Comment by Svidro** [comment] 2019-09-11 20:11
If you wanted to use all of the images. I would generally use either a random sub-selection, or eyeball it and include as much variation as possible. Strongly positive, strongly negative, a few weird ones. Then build the training from that, and save it as a .qpclassifier. Then start a new project for the whole set of images. At that point you only need to use runClassifier("C:\\here is my path\\here is my classifier.qpclassifier) in a script to access the classification. The primary reason to keep the old project separate is in case you decide the classifier needs tweaking or an additional class, or whatever. Then you can go back to the classifier project, add in some new training objects, rebuild training from project, and create another classifier file. Run that file on the "real" project, and compare results.

**Comment by petebankhead** [comment] 2019-09-11 20:15
> @petebankhead is there any way to work around this so that I can use saved training points on the same image that they were created in.

You could try adapting the script linked to above to merge the maps. Note that you'll need to handle duplicate keys.

Or try importing the training points to the same image instead.

>  It is my understanding and experience that these large project are much slower than smaller ones and frequently crash.

This could be because the way your images are converted as described in https://github.com/qupath/qupath/issues/356 is very much _not_ the right way for QuPath.
