### ISSUE TITLE
Script export area image, descendant annotation not exported

### ISSUE THREAD

**Issue by Vir-cn** [qupath/qupath#972] opened 2022-05-30 07:48 UTC
A piece of area is marked, which contains tumor area and matrix area. The tumor area contains matrix area, and the matrix area contains tumor area. When using script export, the exported image does not contain tumor block of matrix area
![image 1](https://user-images.githubusercontent.com/22268342/170943352-23c78448-955c-404d-a215-1570ca4285d0.png)
![image 2](https://user-images.githubusercontent.com/22268342/170943355-54efcab2-eb07-4c41-897f-d888980cc1f1.png)
![image 3](https://user-images.githubusercontent.com/22268342/170943368-49013a60-a8db-46cf-abca-5ac1131d8251.png)

**Comment by petebankhead** [comment] 2022-05-30 09:16
It looks like QuPath is behaving as designed: the order of labels in the script is important, and this specifies that tumor annotations are export first and then stroma on top. You'd need to subtract the tumor region from the stroma, or script the export some other way.

See https://qupath.readthedocs.io/en/stable/docs/advanced/exporting_annotations.html#binary-labeled-images

I'll close the issue because it does not seem to describe a bug, and does not follow the bug report template. The best place for the questions is the forum at https://forum.image.sc/tag/qupath

**Closed by petebankhead** 2022-05-30 09:16 UTC

**Comment by Vir-cn** [comment] 2022-05-31 09:02
Thinks!
