### ISSUE TITLE
'Add intensity features' not working

### ISSUE THREAD

**Issue by GiuseppeAntoniazzi** [qupath/qupath#1290] opened 2023-08-15 07:27 UTC
## Bug report - 'Add intensity features' not working

I am trying to calculate the intensity feature for my image. I selected a ROI and divided it into tiles, trimming the tiles to ROI. then I select the detections (tiles) and I try to run Analyze->Calculate features->Add intensity features. I select the channel of interest and all the features (Mean, Std dev, min max and median), then I run the analysis for the selected objects (tiles). Now, quite often, it is not possible to get the measurement for all my tiles, but only for few initial tiles and then the calculation stops (which I can assess in the 'show detection measurements' table. 

I am running QuPath on a macOS. 

Do you know what I can do to fix this error? 

![Screenshot 2023-08-15 at 09 44 06](https://github.com/qupath/qupath/assets/142295421/d334a749-9599-4d52-bc49-6728835240a6)

**Comment by MichaelSNelson** [comment] 2023-08-15 14:58
Hi @GiuseppeAntoniazzi, as indicated during issue creation, non-bugs are better for the forum. As an aside, it is also far more helpful to post the text of your error messages rather than a screenshot, as screenshots cannot be searched or copied from.
The error itself indicates that you have created objects with negative area and sounds like the sort of thing that happens with Warpy or transforming objects from another image resulting in the objects existing partially outside of the image area. I found [this forum post ](https://forum.image.sc/t/too-many-annotations-gives-me-data-export-error/81659/5?u=mike_nelson)when searching for the error. 

You do seem to have a very large number of tiles, so if your tile size is close to a single pixel, that also might be causing problems.See this forum post.

You do seem to have a very large number of tiles, so if your tile size is close to a single pixel, that also might be causing problems.

Either way, this does not sound like a bug with QuPath, but more specific to your use case, and thus better placed on the forum.

**Comment by petebankhead** [comment] 2023-08-21 07:05
I can't replicate this issue. @GiuseppeAntoniazzi can you provide more detailed step-by-step instructions see the error?

It helps if the error can be reproduced using a publicly-available image, e.g. one from https://qupath.readthedocs.io/en/0.4/docs/intro/acknowledgements.html

If this isn't possible, then it would help to provide the actual objects you are using. These can be exported using *File &rarr; Export objects as GeoJSON*

**Comment by petebankhead** [comment] 2023-08-23 12:17
I'll close this issue because it couldn't replicated. Please reopen if there's more info & steps to reproduce it, thanks.

**Closed by petebankhead** 2023-08-23 12:17 UTC
Labels: bug
