### ISSUE TITLE
Feature request: Make number entry fields w. up-down arrows react to mouse wheel events

### ISSUE THREAD

**Issue by skalteis** [qupath/qupath#495] opened 2020-05-21 15:49 UTC
## Feature request

**Describe the bug**
Some dialogs use a combination of an text entry box and up/down arrows for entering numerical values - the Simple thresholder would be an example. It would be great, if these UI elements would react to mouse wheel events for increments/decrements.

On another note there are a few places where numerical UI entry elements are inconsistent now: The Simple thresholder is using the entry-field-with-up-down-arrows-variant whereas e.g. the positive cell detection does not. I guess it would make sense to use the same type in all these places. ;-)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - QuPath Version 0.2.0-m12

**Comment by petebankhead** [comment] 2020-05-21 16:36
Yes, I understand it would make sense for them to be consistent - but the dialogs are generated in a completely different way (one automatically from a parameter list, one coded 'from scratch'). This is the root cause of the inconsistency. We plan to address it, but amidst the massive changes we have been making for v0.2.0 it has not been a priority...

There has been a feature request for spinner scrollwheel support in JavaFX, but it has not been added: https://bugs.openjdk.java.net/browse/JDK-8092021

I would really rather GitHub issues and bug reports are kept for actual bugs (as described in several places when you press the *New issue* button) to help us prioritise our work -- feature requests are often subjective, and better discussed first on the forum.

**Comment by petebankhead** [comment] 2020-06-09 10:04
Closing this issue after discussion with @melvingelbard... it's not something we plan to do, and would be very apprehensive about including the change even if someone else implemented it.

As I mentioned above, the consistency thing has some (partly historic) reasons. We only started adding spinners recently; the underlying rationale has been that sliders are used when the range is known in advance, spinners are used when it's not... New commands will endeavour to apply this rule more consistently, and old commands will either be either removed or updated.

Regarding spinners and mouse wheel input, I think this really would need to be implemented in JavaFX directly. There are ostensibly easy ways to add support by attaching a scroll listener, in my experience to date this can open a whole can of worms... basically, scroll events can differ a lot depending upon the input device/platform (not to mention 'natural' scrolling in some cases, which can flip the direction). Therefore I think the risk is too high of creating something that inadvertently makes the user experience *worse* for many, and we would have no way to test all the relevant platforms to check this.

I presume the JavaFX developers have reasons for not implementing this directly yet - perhaps related to the reason I give. But in any case, they would have access to potentially more platform-specific information to enable a robust implementation.

For these reasons, I'm afraid I don't think we can/should act on this feature request.

**Closed by petebankhead** 2020-06-09 10:04 UTC
