### ISSUE TITLE
Multi positive cell detections fails + Quapath data file doesn't open + does not save cell counting

### ISSUE THREAD

**Issue by Eline8** [qupath/qupath#112] opened 2017-11-08 11:29 UTC
Hi, 
I'm having some frustrating problems.
My first problem is: I counted cells manual (negative and positive), and then ran the 'positive cell detection' on my ROI. Thereafter, Qupath did not save my negative count but only my positive cells. Why is that? Now I lost a whole morning counting more then 2000 cells for nothing. Really frustrating and time consuming.

Second problem: The program sometimes fails to run the command on both single and multi ROI. My solution was save the file, close Qupath and open it again. However, my third problem came a cross.... It didn't want to open my Qupath data file...  Other files can be opened. I tried to open in by clicking on the file self and by drag and dropping it into qupath. I also tried opening the original file (CZI) and then drag and drop the Qupath file, but without succes.

Does anyone have answers and release me of my frsutrations? or can the bugs be fixed please?

Cheers, 
Eline

**Comment by Svidro** [comment] 2017-11-08 14:54
It would help to see your Workflow script, as I am not really sure what you mean in your first paragraph.  Perhaps you were using the Points Tool?

It also sounds like you might be running into a lack of memory error, but I don't have enough information about your computer to help there either.  QuPath requires significant resources (RAM) to run large scale cell detections and the program is failing to run Positive cell detection might indicate a problem there.  Another possibility is that by default it only runs the cell detection on the ROIs that you have selected.  If you want to run Positive cell detection on everything, you would need to make sure you have either nothing or everything selected.
I'm not sure I can be much more help without your [Workflow](https://github.com/qupath/qupath/wiki/Workflows) or more exact information about the steps you took.

**Comment by petebankhead** [comment] 2017-11-08 19:54
Sorry for your frustrations.  I am also unclear on what exact process you used.  To help, I would need exact steps that I can use to reproduce the problems you are seeing, and any errors messages you see.

I would also suggest:

* Make sure you are working with images in a project.
* Save regularly, and use *File &rarr; Revert* (Ctrl + R) to return to the last saved version.
* Whenever you have performed any lengthy manual steps consider duplicating your entire project folder (or creating a zip file of it) so that you may return to it later.
* If something goes wrong, check out *View &rarr; Show log* for any error messages, and post them here.

**Comment by petebankhead** [comment] 2017-11-08 20:02
Upon further reflection, my understanding is that you likely ran positive cell detection in a ROI that was the 'parent object' for the negative point class - but not the positive class - which is why the negative points only disappeared*.

When you run cell detection with a 'parent object' selected, then any 'child objects' inside it will automatically be deleted, and replaced with the detected cells.  This is *usually* the right/most intuitive thing that should happen, and is not a bug.  If this didn’t happen, then you if ran the cell detection command twice with the same parent selected, you would end up having every cell counted twice - not to mention the strange things that might happen with overlapping objects if you were to run other tiling/superpixel commands.

It's not clear to me what was the purpose of doing manual counts followed by automated counts within the exact same region, but (as you've found) it is something that is not supported.  You *could* do it the opposite way (i.e. automated counts followed by manual counts).  However, if it was my goal to compare manual and automated cell counting then I would do the automatic counts in duplicate project and keep the data separated.

Furthermore, you can do automated counts and then select 'Convert detections to points' within the 'Points tool' to initialize the (manually-editable) points that can subsequently be modified to generate 'semi-automated counts'.

With regard to being unable to reopen a data file, this is something that has been reported some months ago (e.g. #58), but I'm not aware of it being an ongoing problem - or at least not one I have ever been able to reproduce.  If QuPath fails to write a complete data file, then you should find that a '.qpdata.backup' file exits somewhere inside your project/data folder.  If you strip the '.backup' data part from the file name, then it should be possible to recover the last saved version.

> *-Information about the object hierarchy is at https://github.com/qupath/qupath/wiki/Object-hierarchies  But from a quick look it seems that 'point' objects do not behave in the way you might expect, in that it appears that a point object is the child of a region if the *first* point is inside that region - and adding subsequent points (inside or outside the region) doesn't change this relationship.  This is potentially a bug... or at least unintuitive behavior that may well change in a future release.

**Comment by Eline8** [comment] 2017-11-09 17:23
Thank you both for answering! @Svidro and @petebankhead 
I started all over again, so I don't have the workflow anymore. Nevertheless, what I meant was that I used indeed the pointing tool. I had two populations, one negative and one positive. After I ran the positive cell detection, the negative population was gone. And unfortunately, there is no undo button.

My goal was indeed compare the manual counting and the automated counting. For optimization.

I don't know whether the error is the lack of RAM, I checked and i have 3,3GB available. And I only have 4 ROI's in one image. When I run the analysis, I make sure nothing is selected and choose the option 'all annotation'. It might be, but it might be not, because sometimes it also does not analyse only 1 ROI, but other times it does. However, the log it says 'memory error'. the programs that are running on my computer besides Qupaht are google chrome (1tab), one note with an excel file, and file explorer.

![capture](https://user-images.githubusercontent.com/33484227/32604466-0266ac66-c54e-11e7-9a9b-ede61554510b.PNG)
![capture2](https://user-images.githubusercontent.com/33484227/32604472-05d80ef8-c54e-11e7-97d1-b1540f6ee388.PNG)
![capture3](https://user-images.githubusercontent.com/33484227/32604473-07eafa66-c54e-11e7-9aca-94fae7d0e9da.PNG)

I really don't know why sometimes it works or not, but i'll be more careful in what I'll do.
Unfortunately, there was also no backup file in the folder after the failure of saving.

**Comment by Svidro** [comment] 2017-11-09 17:29
The backup will only show up, I think, if you have successfully saved the
file at least once.  It isn't an autosave feature.

Regarding the memory, 3.3 GB is quite low.  For small scale testing I
usually got away with 16GB, and for larger projects 64+.  I am not sure,
but you may be able to circumvent this somewhat by running each of your 4
ROIs in turn, and saving after each.

**Comment by petebankhead** [comment] 2017-11-09 22:13
I'd say 3.3 GB is a perfectly respectable amount of RAM for QuPath (I assume your computer has 8 GB or 12 GB...?).  Personally, I have never had a powerful enough computer to be able to give anywhere close to 64 GB when either developing or using QuPath... and I don't think I ever needed 16 GB either.  Maybe my needs have been modest than @Svidro's but I think that it's not typical to need such huge amounts of memory for most people :)

However, I note that you are using a CZI image.  There are still some lingering issues around QuPath's ability to handle CZI images; depending on the type of image (e.g. TMA/non-TMA, stitched...), I've heard that sometimes it works very well and sometimes there are problems.  It's on my to-do list to investigate why this happens... currently it is a little mysterious for me, and it's not clear if it's something I can resolve within QuPath or which requires more outside help.

Anyway, I don't know if that is the source of your memory woes, but it could be.  Out of curiosity,
* is your image brightfield or fluorescence? (the error suggests brightfield)
* is it a 2D whole slide scan, or an image from a microscope?
* is it a TMA image, large tissue section, or something else?
* does QuPath operate reasonably smoothly, or horribly slowly before the crash?  If you need a comparison, there are some [links on the wiki](https://github.com/qupath/qupath/wiki/Counting-cells) to test data that you might use for comparison.

**Comment by Svidro** [comment] 2017-11-10 00:29
It could be I was thinking of the pre-tiling days for cell detection, or maybe SLICs and subcellular detections on large images?  And yes, I'm probably not typical :)  Never used CZI images, so I have no idea about the effect of those.

Anyway, giving a few things a shot.  One thing I already noticed is that when I zip around an image and cap out the available memory that way, I tend to run into detection problems.

However, as you say, this isn't a hardware memory limit problem, as I can lower the memory cap down to 2GB on a fairly large image (Annotation area 1.3x10^8 um^2) and have it run successfully, but slowly.  If I fill up those 2 GB by looking around the image, though, it failed it's cell detection.  Even on a comparatively small image (2.5x10^6 um^2)  I ran into problems once the memory was filled.  On the other hand, once I bumped the available memory up to 5GB, I stopped running into errors on the smaller image, though it was very difficult to fill the image buffer.  On the larger image I could quite easily cap out the image buffer around 5GB and then sometimes ran into errors.  Although sometimes the program would simply go over the 5GB limit and everything would be fine.  I am afraid I wasn't able to find anything usefully consistent. 


Anyway, the error, whenever I ran into it looks familiar:

> ERROR: Error running plugin: java.lang.OutOfMemoryError: Java heap space
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:242)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:204)
    at qupath.lib.plugins.PluginRunnerFX.runTasks(PluginRunnerFX.java:94)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:134)
    at qupath.lib.plugins.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:163)
    at java.lang.Thread.run(Thread.java:745)
  Caused by Java heap space        at java.util.ArrayDeque.allocateElements(ArrayDeque.java:142)
        at java.util.ArrayDeque.<init>(ArrayDeque.java:198)

**Comment by petebankhead** [comment] 2017-11-10 07:14
One problem I have occasionally seen with CZI is that a request for the *entire* image is made whenever only a small part is needed.  This inevitably causes memory problems, but I have not yet been able to investigate when and why this might happen only for specific images.

In the meantime I'd rather avoid suggesting that a huge amount of memory is required to use QuPath; it shouldn't be.  Certainly with less memory available there may be problems if running something especially intensive (e.g. cell detection, even subcellular detection) across very large regions, but in that case the easiest solution is simply to restrict the analysis to smaller regions.  But yes, if you can spare a few more GB it would be very good to increase what is available to QuPath.  For what it's worth, my laptop has 16 GB RAM and I give about 8 GB to QuPath, although I've also used 4 GB for analysis (or less for just browsing and annotation).

There are also some more memory-related tips at https://github.com/qupath/qupath/wiki/Troubleshooting#setting-memory-limits

It would be good to confirm whether the trouble only occurs when working with cell detection on large regions (at least hundreds of thousands of cells).  My suspicion is that this isn't the case, and it is more likely to be related to the current patchy support for CZI - which is something I hope can be improved within the next few months.  But I could be wrong on this if the behavior is fine whenever only small regions are considered.

**Comment by Eline8** [comment] 2017-11-10 10:07
@petebankhead My computer is indeed 8 RAM. My images are bright field, and 2D whole slide scans and a large tissue (peritoneum of mouse) and therefore are more than 2 GB. Qupath operates fine. It just doens't do anything after the command. 

Just opening CZI files is not a problem, I didn't have this problem yet. 
If it is the RAM, then I'll use another computer to run the analysis. 
But it is still strange that when I run the analysis on all 4 ROI's and I fails that it sometimes also fails for single ROI's, but that's maybe a bug. 

If working with PC I will just do single analysis, hopefully I don't cross the problem again.

cheers

**Comment by Svidro** [comment] 2017-11-10 22:45
If you are still running into problems, I would be interested in whether they also show up with a freshly opened QuPath instance (create ROIs, save and close, open, run cell detection).  The tests in my last post showed that I could run a fairly large cell detection (570k cells) with only 2GB of RAM allowed, as long as it was the first thing I did after opening QuPath.

**Comment by Eline8** [comment] 2017-11-14 09:15
I'm still busy with optimising the parameters for the positive cell detection such as  nucleaus DAB mean/max or cytoplasm or cell. After a serie of runs on single ROI, Qupath fails again with the same 'problem' out of memory. Which is likely to be false 'cause I still have 3.5 gb RAM free and its the only program open. When I close the program and open it, it works a gain, but after a ten-fold runs it 'crashes' again.

**Comment by Eline8** [comment] 2017-11-14 12:49
Qupath did it again, deleting an annotation after running a positive cell analysis.
Don't know what happened, the log doesn't show anything. Luckily, I now now the ctrl+R button
![2017-11-14](https://user-images.githubusercontent.com/33484227/32780738-aa5d356e-c942-11e7-8f5d-780bf2340640.png)

![image](https://user-images.githubusercontent.com/33484227/32780681-78758d44-c942-11e7-9b4c-fa130dcbfe5f.png)

**Comment by petebankhead** [comment] 2017-11-15 08:35
Some assorted responses:

* You say 'QuPath did it again', but it’s not clear if QuPath is actually doing what it is supposed to in deleting objects.  I already described that you should not do automated counts in the same region after manual counting.  Did you read my explanation above?  If it does not describe your situation, please be more specific.  https://github.com/qupath/qupath/issues/112#issuecomment-342941759

* QuPath is written in Java, and is therefore limited by the amount of memory assigned to it on first startup, or under *Help &rarr; Show setup options*.  Additional memory being available on the computer doesn’t change this; QuPath won't use it.

* My best guess remains that the memory problems are related to the handling of CZI images - which is something I will investigate, but I have very little free time currently and it may take a while.  It is not a format I have used much myself, and I have very little relevant data that I can use to test it properly.

* If you want to investigate this yourself, try doing simple processing steps using images in another file format (e.g. Aperio or Hamamatsu - maybe from http://openslide.cs.cmu.edu/download/openslide-testdata/).  If the problem persists then my guess is wrong, and it is not reliant on file format.  But then if you describe your exact steps I may be able to reproduce the issue.

* If you are optimizing positive classification settings, re-running the cell detection would be a horribly slow way to do it.  Running this one-line script and adjusting the values should be *much* faster:
```groovy
setCellIntensityClassifications('Nucleus: DAB OD mean', 0.2)
```

**Comment by petebankhead** [comment] 2018-01-23 18:15
Closing this issue as it has gone quiet - feel free to reopen if there is more information.

The recent [update to the Bio-Formats extension](https://groups.google.com/d/msg/qupath-users/78PpZuu2J1s/su6ZjY0mAgAJ) addresses numerous memory & performance issues, and should help with CZI images.

**Closed by petebankhead** 2018-01-23 18:15 UTC
