### ISSUE TITLE
need a way to adjust bio-formats preferences

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#396] opened 2020-02-04 01:44 UTC
I have CZI files on which I've done some pre-processing in Zen, including messing with the tile stitching. They open naturally in Zen. To open them in ImageJ I have to turn off the bio-formats Autostitch. There does not seem to be a way to do that in QuPath m8? When I ask it to open with the Default (let QuPath decide) ImageProvider, it fails and gives the error below. If I tell it to use Bioformats, nothing happens (no error, no image).  A small cropped example image is here: https://drive.google.com/file/d/1XTnZdoex08mZajcMMjw37U2456tFlV3X/view?usp=sharing

Is there a way (or can you add a way) to turn off Autostitch in the bioformats settings?

```
14:59:04.755 [qupath-shared-1] [WARN ] q.l.i.servers.ImageServerProvider - Unable to open UriImageSupport (class qupath.imagej.images.servers.ImageJServerBuilder) support=1.0, builders=1
14:59:04.755 [qupath-shared-1] [WARN ] q.l.g.c.ProjectImportImagesCommand - Exception adding Image null
java.io.IOException: Unable to build ImageServer for file:/D:/Random%20for%20core/qupath%20to%20csv/2016-08-11%20%2006_Flattened-Create%20Image%20Subset-01.czi (args=[])
        at qupath.lib.images.servers.ImageServerBuilder$DefaultImageServerBuilder.buildOriginal(ImageServerBuilder.java:323)
        at qupath.lib.images.servers.ImageServerBuilder$AbstractServerBuilder.build(ImageServerBuilder.java:147)
        at qupath.lib.gui.commands.ProjectImportImagesCommand.initializeEntry(ProjectImportImagesCommand.java:505)
        at qupath.lib.gui.commands.ProjectImportImagesCommand$1.lambda$call$1(ProjectImportImagesCommand.java:278)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at qupath.lib.gui.commands.ProjectImportImagesCommand$1.call(ProjectImportImagesCommand.java:276)
        at qupath.lib.gui.commands.ProjectImportImagesCommand$1.call(ProjectImportImagesCommand.java:236)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
14:59:04.778 [JavaFX Application Thread] [ERROR] qupath.lib.gui.dialogs.Dialogs - Import images: Failed to load one image.
14:59:04.806 [JavaFX Application Thread] [INFO ] q.l.g.c.ProjectImportImagesCommand -
```

**Comment by petebankhead** [comment] 2020-02-05 07:14
Thanks for this, I can confirm the issue and that it all can work in QuPath if the `zeissczi.autostitch` option is set to false when reading the image.

I suspect the setting needs to be encoded in such a way that it lives on in projects, associated with specific images, rather than a global setting in the software that can be turned on and off... and ideally would support other options for other readers. It'll take a bit more thinking to figure out how to get this into QuPath in a maintainable way.

**Comment by petebankhead** [comment] 2020-02-05 09:43
Well this turned into something rather a lot more complicated than I'd hoped...

Attempted fix in https://github.com/petebankhead/qupath/commit/c331ba1a79223311f31e82d33482dc3102f99480

What *should* happen is that behavior remains the same, however unbeknown to most the Bio-Formats server now accepts arguments of the form `["--bfOptions" "key=value"]` that will be passed to the reader.

The 'easy' (sort of) way to access these is via the following script:
```groovy
def bfOptions = qupath.lib.images.servers.bioformats.BioFormatsServerOptions.getInstance()
bfOptions.setReaderOptions(["zeissczi.autostitch": "false"])
```
This will set the option for the current QuPath session; to reset it, either restart QuPath or call `options.clearReaderOptions()`.

The necessary autostitching flag should then be retained if the image is added to a project. Because this happens regardless of whether the flag is relevant (e.g. it's for a totally different file type) it's best to clear the options when they aren't needed.

If you can build QuPath from the same branch as the commit, please let me know if you find any problems.

> Sidenote: Thanks to @melvingelbard you should also see a Bio-Formats series chooser when opening images even outside a project.

**Comment by saramcardle** [comment] 2020-02-05 17:43
Thank you! I will try this and will tell you how it goes.

**Comment by petebankhead** [comment] 2020-02-14 20:59
I'll close this issue because v0.2.0-m9 is now available - please reopen if you find it doesn't solve the problem.

**Closed by petebankhead** 2020-02-14 20:59 UTC
Labels: bug, enhancement

**Comment by subanookala** [comment] 2021-04-26 03:34
Can anyone help me with any suggestions, please? I am not able to open the images although the project file is opening   I am getting an error message:  Caused by Unable to build ImageServer for file. Thank you,

**Comment by petebankhead** [comment] 2021-04-26 06:07
@subanookala Please post questions on the forum at http://forum.image.sc/tag/qupath and provide more detail (you may find a more complete error message under *View &rarr; Show log*).

**Comment by subanookala** [comment] 2021-04-27 13:33
Pete,
Sorry, I am still learning how to post my queries in the forum, This was my
message. Can you advise please? Thank you very much, suba
Hello, I am able to load the images from the Qupath project, however, when
I double-click on the whole slide, I am getting an error message : **Unable
to build Image server: (view log below) for all the images but one that was
added recently to the project.  Can anyone please suggest how to restore my
data please? Thank you, Suba
INFO: Initializing type adapters
INFO: Bio-Formats version 6.5.1
INFO: Loaded extension Bio-Formats options (Bio-Formats 6.5.1) (17 ms)
INFO: Loaded extension Experimental extension (1 ms)
INFO: Loaded extension ImageJ extension (44 ms)
INFO: Loaded extension JPen extension (19 ms)
INFO: Loaded extension Processing extension (28 ms)
INFO: Loaded extension Rich script editor extension (235 ms)
INFO: Loaded extension SVG export extension (1 ms)
INFO: OpenSlide version 3.4.1
INFO: Starting QuPath with parameters: []
INFO: Trying to load project Z:\Kotb Lab\General\ALL INFECT and INFECT
images\INF 69 DR3 DR4 repeat for Ganesh manuscript Qupath data\dr3 gfap new
042121\project.qpproj
INFO: Project set to Project: dr3 gfap new 042121-project
INFO: Image data set to ImageData: Brightfield (H-DAB), PR301S1 2021-04-23
07.49.55.ndpi
WARN: Unable to open file://
undmed-files.med.und.edu/Basic%20Sciences/Kotb%20Lab/General/ALL%20INFECT%20and%20INFECT%20images/INF%2069%20DR3%20DR4%20repeat%20for%20Ganesh%20manuscript%20Qupath%20data/dr3%20gfap%20new%20042121/PR287S8%20-%202021-04-12%2009.52.58.ndpi
with OpenSlide: URI has an authority component
ERROR: Load ImageData: Unable to build ImageServer for file://
undmed-files.med.und.edu/Basic%20Sciences/Kotb%20Lab/General/ALL%20INFECT%20and%20INFECT%20images/INF%2069%20DR3%20DR4%20repeat%20for%20Ganesh%20manuscript%20Qupath%20data/dr3%20gfap%20new%20042121/PR287S8%20-%202021-04-12%2009.52.58.ndpi
(args=[]) with requested provider
qupath.lib.images.servers.openslide.OpenslideServerBuilder
ERROR: Load ImageData
    at
qupath.lib.images.servers.ImageServerBuilder$DefaultImageServerBuilder.buildOriginal(ImageServerBuilder.java:341)
    at
qupath.lib.images.servers.ImageServerBuilder$AbstractServerBuilder.build(ImageServerBuilder.java:152)
    at
qupath.lib.projects.DefaultProject$DefaultProjectImageEntry.readImageData(DefaultProject.java:718)
    at qupath.lib.gui.QuPathGUI.openImageEntry(QuPathGUI.java:2695)
    at
qupath.lib.gui.panes.ProjectBrowser.lambda$new$3(ProjectBrowser.java:190)
    at
com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at
com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at
com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at
com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at
com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at
com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3597)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3899)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1885)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
    at
com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at
com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at
com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at
com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at
com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at
com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)
