### ISSUE TITLE
Working in script editor and failing on command line for QuPath 0.2.0-m10 and greater

### ISSUE THREAD

**Issue by codybum** [qupath/qupath#511] opened 2020-06-02 14:48 UTC
**Describe the bug**
Starting with m10, when the new command line was introduced, the "getCurrentImageData()" function returns NULL.  Prior to 0.2.0-m10 (m4 -> m9 confirmed working) the following command could be used to run a script on the (MacOS) command line "QuPath-0.2.0-m9 -image myimage.svs -script myscript.groovy".  The arguments "-image" identifited the image and "-script" identified the script.  On execution you would see QuPath output (e.g. qupath.QuPath - Launching QuPath with args), then the script would be executed.  In versions after 0.2.0-m10, including the 0.2.0 release, I am trying to use the command "QuPath-0.2.0 -i=myimage script myscript.groovy", but this fails with NullPointerException related to a null returned by "getCurrentImageData()".  The exact same script works just fine using the script editor in all versions.  

I am possibly using the new command line interface incorrectly.     

**To Reproduce**
1. Create any script that needs to reference the current image, without using a project.  The following script "myscript.groovy" demonstrates the issue:
```
import static qupath.lib.gui.scripting.QPEx.*

def imageData = getCurrentImageData()

if(imageData == null) {
    println "imageData == Null"
} else {
    println "imageData != Null"
}

def server = imageData.getServer()
```
2. Run the script referencing an image on the command line: 
```
./QuPath-0.2.0 -i=myimage.svs script myscript.groovy
```
3. See error:
imageData == Null
NullPointerException at line 11: Cannot invoke method getServer() on null object

**Expected behavior**
I would expect that if the command line arguments were changed to the new format the script processing would work the same as 0.2.0-m9 and earlier.  The script editor seems to work just fine.  Example working output from 0.2.0-m9 is shown below: 

10:23:10.593 [main] [INFO ] qupath.QuPath - Launching QuPath with args: -image, myimage.svs, -script, myscript.groovy
10:23:11.387 [main] [WARN ] q.l.i.s.b.BioFormatsImageServer - Temp memoization directory created at /var/folders/9_/b0xrdp2d1bsbzlmwp3xff2g00000gn/T/qupath-memo-8955966830564346412
10:23:11.388 [main] [WARN ] q.l.i.s.b.BioFormatsImageServer - If you want to avoid this warning, either disable Bio-Formats memoization in the preferences or specify a directory to use
10:23:11.563 [main] [WARN ] q.l.i.s.ImageServerMetadata$ImageResolutionLevel - Calculated downsample values differ for x & y for level 4: x=70.0 and y=70.10548523206751 - will use value 70.05274261603375
10:23:11.573 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Applications/QuPath-0.2.0-m9.app/Contents/app/groovy-2.5.9.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
imageData != Null

**Desktop (please complete the following information):**
 - OS: [macOS]
 - QuPath Version [0.2.0-m10 and greater]

**Additional context**

**Comment by melvingelbard** [comment] 2020-06-02 15:41
Hi @codybum,
Your problem should be fixed by simply changing the order or your args like this:
`./QuPath-0.2.0 script --image myimage.svs --script myscript.groovy`

So this shouldn't be a bug - though it might be worth adding that the CLI is somewhat strict with the argument order to the docs. As a rule of thumb and to avoid future problems, I would always call the command first, followed by all the desired options/parameters (called with their identification). 
E.g. `QuPath-0.2.0 [command-name] [-option1=<option1>] [-option2=<option2>]`

I'll close this for now as it's not a bug if you don't mind. Feel free to open a new thread on the [forum](https://forum.image.sc/tag/qupath) if you have a question regarding the CLI and its use (or open a new issue here if you find a bug!).

**Closed by melvingelbard** 2020-06-02 15:41 UTC
Labels: bug
