### ISSUE TITLE
Zoom In and Zoom Out

### ISSUE THREAD

**Issue by kayyee** [qupath/qupath#518] opened 2020-06-08 16:24 UTC
The standard for zooming in is to obtain a higher magnification image and a smaller field of view. The standard for zooming out is to obtain a lower magnification and a larger field of view. In Qupath, is seems that the action associated with these terms is reversed.

**Comment by petebankhead** [comment] 2020-06-08 17:10
This looks like a simple bug, albeit one that has existed for some months at least - weirdly without being reported before. Should be fixed in the next minor release, but I first need to check it in more detail.

**Comment by kayyee** [comment] 2020-06-08 17:12
Thank you Pete.

Kathy

**Comment by Svidro** [comment] 2020-06-08 17:54
I haven't noticed any changes with this behavior recently on Win10; I just tested with the 3 kinds of image servers I normally use. 

0.2.0 release. Is this happening on a particular OS? I take it Pete is seeing it on his end.

I am seeing the magnification get smaller as I zoom out, and larger as I zoom in.

**Comment by petebankhead** [comment] 2020-06-08 17:56
I understand the issue is with the specific commands under *View &rarr; Zoom... &rarr; Zoom in/out* (I've tested only on a Mac, but assume the unexpected behavior is common across platforms - it was also weird in m10, but not v0.1.2... I didn't check any others).

**Comment by kayyee** [comment] 2020-06-08 18:00
Yes, under the View → Zoom... → Zoom in/out is where I encountered the reverse behavior.
I am working on a Mac.

**Comment by Svidro** [comment] 2020-06-08 18:04
Oh, wow, yes, confirmed. I have never used that function.

**Comment by Svidro** [comment] 2020-06-08 18:07
Correct. I also noticed that in windows there are + and - keys that appear to be associated with those commands in the View menu, but the + and - keys do not seem to do anything. Am I reading that wrong or is this expected?

**Comment by Svidro** [comment] 2020-06-08 18:17
And I'm guessing it doesn't matter a huge deal, but M9 is one of the versions I have had to keep active for another side project, and in that version the Zoom direction is correct, so it sounds like it was between 9 and 10.

The keybinding issue is the same in M9, however.

**Comment by petebankhead** [comment] 2020-06-08 18:18
The `-` key works for me. The `+` does not because on my keyboard it requires a shift, and this seems to thwart things... do you have a number pad to check if this makes any difference?

**Comment by Svidro** [comment] 2020-06-08 18:26
Right, that was the first part, sorry for lack of clarity. Num lock on or off has no impact.

"The + and - keys no the num pad do nothing when I use them."

**Comment by kayyee** [comment] 2020-06-08 18:34
The minus key on my main keyboard and the minus key on my number pad both cause
zooming-in / increased magnification.  Both of my + keys don’t do anything.

**Comment by petebankhead** [comment] 2020-06-08 18:51
Just made a change that seems to resolve the non-functioning + (which I'd previously noticed, but had been unable to fix).

Missed the edits that changed the earlier posts to refer to the num pad. But I don't have a num pad anyway, so no idea what will happen with that.

**Comment by petebankhead** [comment] 2020-06-09 16:50
I'll close this issue, v0.2.1 should be available next week containing this and some other minor fixes.

**Closed by petebankhead** 2020-06-09 16:50 UTC
Labels: bug

**Comment by kayyee** [comment] 2020-06-09 16:51
Okay.  Will look forward to the new version.
Thank you for your help, Pete.

Best regards,
Kathy Yee
