### ISSUE TITLE
High initial latency before image starts moving using the pan tool

### ISSUE THREAD

**Issue by skalteis** [qupath/qupath#440] opened 2020-04-15 15:45 UTC
## Bug report
The pan tool has a high initial latency when working with large images with many detections. It takes a few seconds until the image starts to follow the mouse pointer after the initial click.
After overcoming this lag, the panning itself is sufficiently smooth, though.
The phenomenon is not influenced by zoom level or the display status of annotations or detections.
I don't think this is related to hardware ressources, CPU/GPU utilization bareley changes during this - and the computer should be sufficiently powerful

**To Reproduce**
Load NDPI (approx. 30x30 MP in size)
Draw ROIs (in this case generated from pixel classifications and smoothed)
Use positive cell detection, resulting in about 152,000 detected nuclei
Try using the pan tool

**Expected behavior**
More or less immediate pan action

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit. HP Z840 dual Xeon E5-2667v3, 128 GB RAM, Nvidia Quadro K6000
 - QuPath Version 0.2.0-m9 (set to use 64 GB of RAM)

Thank you for this great piece of software! :-)

**Comment by petebankhead** [comment] 2020-04-15 16:33
From your description I don't think this is a bug. QuPath generates markup images on demand, and then caches these for performance. A lot of the functionality depends upon this ability (e.g. measurement maps, the ability to quickly fill/unfill detections), but it does mean that there can be a short delay when generating the markup tiles each time the delay changes significantly. This delay increases with the number of detections. Working with a static markup image would be a lot faster... but also a lot more restrictive.

I don't know what you mean with 'high initial latency', but a second or two is to be expected. 10-20 seconds isn't.

If this is the explanation you should find the latency returns if (for example) you press 'f' to fill/unfill the detections - but goes away again after a few seconds, once the new tiles have been cached.

There is a performance issue with v0.2.0-m9 when it comes to drawing annotations (under some circumstances) on an image with a large number of annotations already present, but this will be fixed in the next release.

**Comment by skalteis** [comment] 2020-04-15 16:49
Hi Pete,
thanks for your reply!

The latency is about 3 seconds, maybe this is to be expected. :-)

If I understand you correctly then the cached tiles don't have to be regenerated on each pan action but will be if I toggle annotations, detections, etc., right?

I've attached a gif animation of the behavior.

![latency-demo](https://user-images.githubusercontent.com/4951046/79364460-ad984880-7f49-11ea-8d93-1c529efe4d56.gif)

**Comment by petebankhead** [comment] 2020-04-15 16:58
Yes, the cached tiles will be generated only when needed - but at different magnifications (so different tiles may be required based upon the field of view and zoom level).

But assuming that when the circle appears in the GIF that means your mouse is pressed, I haven't seen this behavior before and I haven't been able to replicate it on my (much less powerful) computer.

**Comment by petebankhead** [comment] 2020-04-15 17:00
If you can provide more information about when it does/doesn't happen that would be helpful. Also if you have seen it across different versions of the software and different methods of generating detections (e.g. using the built-in cell detection instead).

And also if it persists after restarting QuPath. Since you mention pixel classification, I wonder if it is still active in the background.

(When v0.2.0-m10 becomes available you will be able to use VisualVM to profile it and see what might be causing slowdowns... but it doesn't work easily with v0.2.0-m9)

**Comment by skalteis** [comment] 2020-04-15 17:30
It seems to be related to extremly detailed ROIs such as those that can be generated from very messy pixel classifiers!

With the extreme test case below I managed to stall QuPath for about half a minute.

So it's maybe just a case of me not cleaning up properly after autogenerating ROIs. :-)
![messy-ROIs](https://user-images.githubusercontent.com/4951046/79368383-93f9ff80-7f4f-11ea-9290-bceda372b2b4.png)

**Comment by skalteis** [comment] 2020-04-17 14:08
After some more testing, I noted that there's something weird going on.
Yesterday, I was using a few ROIs of no particular complexity, put the Computer in standby, started to work on it just now and the latency now depends on zoom level! On 1% zoom, the latency (about 3 seconds) is there on *each* click-drag-operation although the whole slide just occupies a small part of the entire view. At 100% it is working fine.

I just closed qupath and recreated the setup and now... the latency is gone at 1% zoom.

Could this be a memory leak somewhere that only surfaces after a while? Very very puzzling...

**Comment by petebankhead** [comment] 2020-04-17 14:27
You can use the built-in memory monitor to investigate this (and also to reclaim memory), although best would be to build m10-SNAPSHOT from the `dev` branch and see if the issue remains there. With m10 you'll also be able to use [VisualVM](https://visualvm.github.io) for profiling.

**Comment by skalteis** [comment] 2020-04-17 14:32
I set up an experiment to check for memory leaks - I'll leave qupath on with my ROIs and check the memory monitor (took a screenshot at the start), let's see what happens tomorrow. :-)

I have built qupath dev branch versions before but only on Linux, not on Windows. I'll have at look at it. :-)
Thanks for your support!

**Comment by skalteis** [comment] 2020-04-17 15:41
Ok, I have a second test setup in parallel using m10-SNAPSHOT, VisualVM is running, sampling and I have taken a snapshot at the start. Anything else to help with debugging? ;-)

**Comment by petebankhead** [comment] 2020-04-17 15:47
It doesn't/shouldn't matter if the memory climbs, but falls again when the garbage collector runs (e.g. by pressing *Reclaim memory* in QuPath or creating a heap dump in VisualVM). But if you can reproduce the laggy behavior, I'd be very interested to know what is happening during three seconds according to the CPU sampler in VisualVM.... and indeed if garbage collection has any effect on it.

And/or if you can give me step-by-step instructions to reproduce the behavior.

**Comment by petebankhead** [comment] 2020-04-22 11:56
@skalteis any updates? v0.2.0-m10 is now available, and should be capable of working with VisualVM directly.

**Comment by skalteis** [comment] 2020-04-22 13:30
strangely and unfortunately I could not reproduce the bug on the weekend - neither on m9 nor m10-SNAPSHOT.
I'll be using -m10 now and as soon as I see it again, I'll fire up VisualVM and have a look at it!

I don't know whether that is related but I noticed a sawtooth pattern in heap usage in -m10-SNAPSHOT.
![Capture-M10-snapshot-no_interaction_minimized](https://user-images.githubusercontent.com/4951046/79987843-3107eb80-84ae-11ea-946b-94aa9785a4fd.PNG)

Thank you for your help!

**Comment by petebankhead** [comment] 2020-04-22 13:39
Not too unfortunate from my side, hope it doesn't resurface :)

I've seen the sawtooth thing a lot, memory increases until the garbage collection is triggered - but it can also be decreased back to the baseline at any time by calling the garbage collector explicitly. I don't really know the exact reason (quite possibly has a connection with profiling..?), but as far as I can tell it is normal.

I'll close this issue then, please reopen if you have more information.

**Closed by petebankhead** 2020-04-22 13:39 UTC
Labels: bug
