### ISSUE TITLE
Cell Detection Failing and Corrupting Data Files

### ISSUE THREAD

**Issue by dougzy** [qupath/qupath#174] opened 2018-05-18 11:58 UTC
Hi everyone. I'm running into problems with QuPath I first noticed when running positive cell detection on a bunch of TMAs. When I reviewed the results, the annotations were missing from a number of them. I was able to restore most from a backup, but following this positive cell detection has been erratic. 

At the moment, positive cell detection will run, but will cut out before completing. There will be cores which work, but the majority do not. Once completed, the others can be manually selected and run through cell detection, which appears to work. The next problem arises once that file is saved, and another TMA is selected. If I then return to the original TMA I was working on, all the annotations will be missing, and the data file no longer opens (and appears to shrink to about half its previous size) suggesting it has been corrupted in some way. 

This wasn't happening at the start of my project, so I'm not quite sure what's going on. 

Any help would be greatly appreciated. Here's the log of the issue:

INFO: Refreshing extensions in C:\Program Files\QuPath\app\qupath
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-core-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-core-awt-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-core-processing-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-core-processing-awt-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-ij-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-input-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-opencv-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-openslide-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-pen-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-script-editor-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-xl-0.0.1-SNAPSHOT.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-extension-xml-0.0.1-SNAPSHOT.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-gui-fx-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-processing-ij-0.1.2.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\qupath-processing-opencv-0.1.2.jar
INFO: Refreshing extensions in C:\Program Files\QuPath\app\qupath\sources
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-core-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-core-awt-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-core-processing-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-core-processing-awt-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-extension-ij-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-extension-input-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-extension-opencv-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-extension-openslide-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-extension-pen-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-extension-script-editor-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-gui-fx-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-processing-ij-0.1.2-sources.jar
INFO: Added extension: C:\Program Files\QuPath\app\qupath\sources\qupath-processing-opencv-0.1.2-sources.jar
INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: Trying to load project C:\Qupath Project\LungAdeno\project.qpproj
INFO: Project set to Project: LungAdeno
INFO: Returning server: PathXL for http://accelerator-is.med.qub.ac.uk:80/E:/CCRCB Digital Pathology Archive 2017/RESEARCH/2015/NIB15-0168/2017-06-06 TMAS VARIOUS/LUNG TMAS/LUNG ADENO TMA 1L/CD4 LUNG ADENO TMA 1L.svs
INFO: Estimating H-DAB staining
INFO: Image data set to ImageData: Brightfield (H-DAB), CD4 LUNG ADENO TMA 1L.svs
INFO: Reading data from CD4 LUNG ADENO TMA 1L.svs.qpdata...
INFO: Hierarchy with 499965 object(s) read from C:\Qupath Project\LungAdeno\data\CD4 LUNG ADENO TMA 1L.svs.qpdata in 3.25 seconds
INFO: 4125 nuclei detected (processing time: 18.97 seconds)
INFO: 3471 nuclei detected (processing time: 20.17 seconds)
INFO: 3938 nuclei detected (processing time: 21.79 seconds)
INFO: 3489 nuclei detected (processing time: 27.79 seconds)
INFO: 5005 nuclei detected (processing time: 28.24 seconds)
INFO: 5422 nuclei detected (processing time: 30.49 seconds)
INFO: 8611 nuclei detected (processing time: 33.50 seconds)
INFO: 8457 nuclei detected (processing time: 34.45 seconds)
INFO: 3712 nuclei detected (processing time: 16.38 seconds)
INFO: 3333 nuclei detected (processing time: 19.22 seconds)
INFO: 8037 nuclei detected (processing time: 20.23 seconds)
INFO: 2288 nuclei detected (processing time: 15.90 seconds)
INFO: 1855 nuclei detected (processing time: 16.48 seconds)
INFO: 4705 nuclei detected (processing time: 14.55 seconds)
INFO: 4012 nuclei detected (processing time: 14.33 seconds)
INFO: 3772 nuclei detected (processing time: 15.84 seconds)
INFO: 771 nuclei detected (processing time: 4.80 seconds)
INFO: 6919 nuclei detected (processing time: 15.36 seconds)
INFO: 511 nuclei detected (processing time: 4.46 seconds)
INFO: 598 nuclei detected (processing time: 4.36 seconds)
INFO: 753 nuclei detected (processing time: 5.28 seconds)
INFO: 6815 nuclei detected (processing time: 20.65 seconds)
INFO: 3426 nuclei detected (processing time: 19.85 seconds)
INFO: 3996 nuclei detected (processing time: 16.86 seconds)
INFO: 5154 nuclei detected (processing time: 17.78 seconds)
INFO: 6323 nuclei detected (processing time: 21.51 seconds)
INFO: 4385 nuclei detected (processing time: 13.01 seconds)
INFO: 4557 nuclei detected (processing time: 12.97 seconds)
INFO: 3526 nuclei detected (processing time: 15.51 seconds)
INFO: 0 nuclei detected (processing time: 0.15 seconds)
INFO: 5943 nuclei detected (processing time: 18.99 seconds)
INFO: 7753 nuclei detected (processing time: 18.88 seconds)
INFO: 6433 nuclei detected (processing time: 17.41 seconds)
INFO: 7855 nuclei detected (processing time: 19.67 seconds)
INFO: 5142 nuclei detected (processing time: 16.46 seconds)
INFO: 9036 nuclei detected (processing time: 20.64 seconds)
INFO: 0 nuclei detected (processing time: 0.26 seconds)
INFO: 3833 nuclei detected (processing time: 16.78 seconds)
INFO: 4 nuclei detected (processing time: 0.11 seconds)
INFO: 7621 nuclei detected (processing time: 19.00 seconds)
INFO: 4084 nuclei detected (processing time: 15.32 seconds)
INFO: 3922 nuclei detected (processing time: 16.92 seconds)
INFO: 0 nuclei detected (processing time: 0.27 seconds)
INFO: 5801 nuclei detected (processing time: 15.96 seconds)
INFO: 3188 nuclei detected (processing time: 16.83 seconds)
ERROR: Unable to read image from http://accelerator-is.med.qub.ac.uk:80/E:/CCRCB%20Digital%20Pathology%20Archive%202017/RESEARCH/2015/NIB15-0168/2017-06-06%20TMAS%20VARIOUS/LUNG%20TMAS/LUNG%20ADENO%20TMA%201L/CD4%20LUNG%20ADENO%20TMA%201L.svs?GetImage?x=38411&y=15229&width=20&height=7&focus=0&zoom=2.000000&compression=80: Could not read http://accelerator-is.med.qub.ac.uk:80/E:/CCRCB%20Digital%20Pathology%20Archive%202017/RESEARCH/2015/NIB15-0168/2017-06-06%20TMAS%20VARIOUS/LUNG%20TMAS/LUNG%20ADENO%20TMA%201L/CD4%20LUNG%20ADENO%20TMA%201L.svs: x=76821, y=30458, w=40, h=14, z=0, t=0, downsample=2
ERROR: Error running plugin: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:242)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:204)
    at qupath.lib.plugins.PluginRunnerFX.runTasks(PluginRunnerFX.java:94)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:134)
    at qupath.lib.plugins.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:163)
    at java.lang.Thread.run(Thread.java:745)
  Caused by null        at qupath.imagej.images.servers.BufferedImagePlusServer.readImagePlusRegion(BufferedImagePlusServer.java:211)
        at qupath.imagej.objects.PathImagePlus.getImage(PathImagePlus.java:167)
        at qupath.imagej.objects.PathImagePlus.getImage(PathImagePlus.java:126)
        at qupath.imagej.objects.PathImagePlus.getImage(PathImagePlus.java:50)
        at qupath.imagej.detect.nuclei.WatershedCellDetection$CellDetector.runDetection(WatershedCellDetection.java:263)
        at qupath.imagej.detect.nuclei.PositiveCellDetection$DetectorWrapper.runDetection(PositiveCellDetection.java:87)
        at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:120)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO: Processing complete in 98.30 seconds
INFO: Completed with error java.lang.NullPointerException
INFO: 
qupath.imagej.detect.nuclei.PositiveCellDetection  {"detectionImageBrightfield": "Hematoxylin OD",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": false,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true,  "thresholdCompartment": "Nucleus: DAB OD mean",  "thresholdPositive1": 0.35,  "thresholdPositive2": 0.5,  "thresholdPositive3": 0.7,  "singleThreshold": true}
INFO: 0 nuclei detected (processing time: 4.73 seconds)
INFO: 4832 nuclei detected (processing time: 15.50 seconds)
INFO: 4258 nuclei detected (processing time: 13.35 seconds)
INFO: 0 nuclei detected (processing time: 13.61 seconds)
INFO: 0 nuclei detected (processing time: 8.55 seconds)
INFO: 2470 nuclei detected (processing time: 8.96 seconds)
INFO: 2482 nuclei detected (processing time: 10.48 seconds)
INFO: 4344 nuclei detected (processing time: 12.86 seconds)

**Comment by petebankhead** [comment] 2018-05-18 12:07
Hi Adam, the problem is access to the images - for which I can see you're using a custom extension, and not something that's part of QuPath itself.

I got an email about this issue a while back; the conclusion then was that if you can access the .svs image files directly, rather than via the extension, the problem should go away.

I'll close the issue here because it isn't really within QuPath itself.  If you can send me an email (or track me down on ResearchGate, LinkedIn, Twitter or elsewhere) then I can discuss it further there.

The missing annotations thing is a bit of a mystery, and may or may not be connected.  If you can find a way to reproduce it please let me know.

**Closed by petebankhead** 2018-05-18 12:07 UTC
