### ISSUE TITLE
Cannot open project file

### ISSUE THREAD

**Issue by cjpinelli** [qupath/qupath#613] opened 2020-10-14 16:16 UTC
All of a sudden, a project that I am currently working on will not open in QuPath via different methods. I am running Windows 10, and when I:

- When I try to double click on the project file in file explorer, nothing happens.

- When I try to open the project within QuPath, I get a "Could not read project from project.qpproj" error

- When I try to drag the project file from file explorer to the QuPath window (I'm not sure if this is even a valid way to open a project?), I get a "java.lang.NullPointerException" error

Thanks in advance!!

Chris

**Comment by petebankhead** [comment] 2020-10-14 16:26
We'd also need to know the version of QuPath you're using, and any other changes that could be relevant (e.g. installing a new version, moving files).

**Comment by cjpinelli** [comment] 2020-10-14 16:29
Currently running QuPath 0.2.3

ERROR: Project error: java.lang.NullPointerException
ERROR: Project error
    at qupath.lib.projects.DefaultProject.loadProject(DefaultProject.java:1094)
    at qupath.lib.projects.DefaultProject.loadFromFile(DefaultProject.java:171)
    at qupath.lib.projects.ProjectIO.loadProject(ProjectIO.java:97)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDropImpl(DragDropFileImportListener.java:248)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDrop(DragDropFileImportListener.java:158)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:126)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:3057)
    at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3283)
    at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2997)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(GlassSceneDnDEventHandler.java:108)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:104)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(GlassViewEventHandler.java:766)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:765)
    at com.sun.glass.ui.View.handleDragDrop(View.java:713)
    at com.sun.glass.ui.View.notifyDragDrop(View.java:1042)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by null        at qupath.lib.projects.DefaultProject.loadPathClasses(DefaultProject.java:1130)
        at qupath.lib.projects.DefaultProject.loadProject(DefaultProject.java:1086)
        at qupath.lib.projects.DefaultProject.loadFromFile(DefaultProject.java:171)
        at qupath.lib.projects.ProjectIO.loadProject(ProjectIO.java:97)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDropImpl(DragDropFileImportListener.java:248)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDrop(DragDropFileImportListener.java:158)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:126)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:64)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:3057)
        at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3283)
        at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2997)
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(GlassSceneDnDEventHandler.java:108)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:104)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(GlassViewEventHandler.java:766)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:765)
        at com.sun.glass.ui.View.handleDragDrop(View.java:713)
        at com.sun.glass.ui.View.notifyDragDrop(View.java:1042)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Svidro** [comment] 2020-10-14 16:29
Any chance there is a backup file you could rename and use?
![image](https://user-images.githubusercontent.com/23145209/96018084-acb07880-0dff-11eb-982f-a0a3d782d95f.png)
Add a .bak to the end of the primary project.qpproj file and remove the .backup from the backup.

**Comment by petebankhead** [comment] 2020-10-14 16:35
It looks like the exception is coming from the attempt to load the classifications (the ones that appear under the 'Annotations' tab). These are stored in the project under *classifiers/classes.json*.

Something has gone wrong with that file; you can try simply deleting it (if it exists) or replacing the corresponding file from another project.

**Comment by cjpinelli** [comment] 2020-10-14 16:40
> Any chance there is a backup file you could rename and use?
> ![image](https://user-images.githubusercontent.com/23145209/96018084-acb07880-0dff-11eb-982f-a0a3d782d95f.png)
> Add a .bak to the end of the primary project.qpproj file and remove the .backup from the backup.

I tried this and it didn't work... I will try Pete's suggestion next!

**Comment by cjpinelli** [comment] 2020-10-14 16:42
> It looks like the exception is coming from the attempt to load the classifications (the ones that appear under the 'Annotations' tab). These are stored in the project under _classifiers/classes.json_.
> 
> Something has gone wrong with that file; you can try simply deleting it (if it exists) or replacing the corresponding file from another project.

Deleting the classes.jon file worked! Is there something that I did wrong to create the issue that I can avoid in the future?

**Comment by petebankhead** [comment] 2020-10-14 16:44
Good! I don't know - QuPath shouldn't really allow this to happen, so I'm not sure how it did... I'll close the issue now, but if you can find steps to reproduce it please let me know and we can try to fix it to avoid the trouble in the future.

**Closed by petebankhead** 2020-10-14 16:44 UTC

**Comment by cjpinelli** [comment] 2020-10-14 16:57
Will do, thanks so much!
