### ISSUE TITLE
Syncronize viewers and (temporary) move tool bugged

### ISSUE THREAD

**Issue by bjtho08** [qupath/qupath#302] opened 2019-04-08 17:40 UTC
**Describe the bug**
When using multiple syncronized viewers, trying to move using the spacebar does not work.

**To Reproduce**
1. Open a .tif image
2. Right click -> multi-view -> add column
3. Select new viewer
4. Open a .tif image in new viewer
5. press and hold spacebar
6. while holding spacebar, click and drag in any viewer
7. First attempt might be succesful and ten give the error
8. any subsequent attempt fails with the error below

```
ERROR: QuPath exception
    at qupath.lib.gui.viewer.QuPathViewer.setSpaceDown(QuPathViewer.java:963)
    at qupath.lib.gui.QuPathGUI.lambda$new$4(QuPathGUI.java:690)
    ...
```

[qplog.txt](https://github.com/qupath/qupath/files/3055606/qplog.txt)

**Expected behavior**
Both images should move together.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath: every version (tested on 0.1.2, 0.1.3, 0.2.0-m1, 0.2.0-m2, 0.2.0-m3-SNAPSHOT [april 4])

**Additional context**
Attached log file containing error

**Comment by petebankhead** [comment] 2019-04-08 17:43
Duplicate of https://github.com/qupath/qupath/issues/288

**Closed** 2019-08-05 08:15 UTC
Labels: bug, duplicate
