### ISSUE TITLE
5plex .czi files not opening 

### ISSUE THREAD

**Issue by MustafaElshani** [qupath/qupath#145] opened 2018-02-07 15:26 UTC
Hi Guys

I am trying to open a .czi file which has 5 channel Multiplexing, this does not open at all with the logs shown below, however, the 4 plex scans open fine and we can do analysis on them.

I have attached the file here https://drive.google.com/file/d/1kvqmxDA5n4Bq29FSrg8b6o_j5S--ZHp5/view?usp=sharing 

Any help would very much be appreciated

Kindest of Regards 

Mustafa

`INFO: Refreshing extensions in W:\Images\QuPath Extensions
INFO: Added extension: W:\Images\QuPath Extensions\bioformats_package.jar
INFO: Added extension: W:\Images\QuPath Extensions\qupath-extension-bioformats.jar
INFO: Added extension: W:\Images\QuPath Extensions\qupath-weka-extension.jar
INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
WARN: Unable to open W:\Images\David\HW_5plex test\2018_02_02__4525.czi with OpenSlide: W:\Images\David\HW_5plex test\2018_02_02__4525.czi: Not a file that OpenSlide can recognize
WARN: Error opening W:\Images\David\HW_5plex test\2018_02_02__4525.czi with ImageJ: Could not open W:\Images\David\HW_5plex test\2018_02_02__4525.czi with ImageJ
WARN: QuPath Bio-Formats extension is in beta!  Be watchful for bugs...
INFO: ZeissCZIReader initializing W:\Images\David\HW_5plex test\2018_02_02__4525.czi
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
INFO: Returning server: Bio-Formats for W:\Images\David\HW_5plex test\2018_02_02__4525.czi
INFO: ZeissCZIReader initializing W:\Images\David\HW_5plex test\2018_02_02__4525.czi
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
INFO: ZeissCZIReader initializing W:\Images\David\HW_5plex test\2018_02_02__4525.czi
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
WARN: Unknown IlluminationType value 'Fluorescence' will be stored as "Other"
ERROR: QuPath exception
    at qupath.lib.display.ImageDisplay.setChannelSelected(ImageDisplay.java:313)
    at qupath.lib.gui.commands.BrightnessContrastCommand.updateDisplay(BrightnessContrastCommand.java:541)
    at qupath.lib.gui.commands.BrightnessContrastCommand.createDialog(BrightnessContrastCommand.java:446)
    at qupath.lib.gui.commands.BrightnessContrastCommand.run(BrightnessContrastCommand.java:586)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$46(QuPathGUI.java:3122)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8413)
    at javafx.scene.control.Button.fire(Button.java:185)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
`

**Comment by Svidro** [comment] 2018-02-07 15:41
Hi!  I just wanted to quickly verify that you are using Pete's newest Bioformats extension (updated 20 days ago) and Bioformats 5.7.3.  

I suspect everything is up to date since the 4plex works, but I had some problems a few weeks ago, and realized I had not updated Bioformats (separately from the extension) in a while, which turned out to be my problem.  And being sure you have both of those may help Pete troubleshoot the problem.

**Comment by petebankhead** [comment] 2018-02-07 17:20
I can confirm that the problem occurs with the latest version of everything.  I see where the problem is and will have a try at fixing it.

**Comment by petebankhead** [comment] 2018-02-07 21:53
This problem should be fixed in the next release, alongside a few other changes to help give more control over performance-related options.

**Comment by MustafaElshani** [comment] 2018-02-08 10:47
Yes, I can also confirm this is the latest version of bioformats and qupath extension 

Again Thank you for all of your hard work in addressing issues

Mustafa

**Comment by petebankhead** [comment] 2018-02-08 13:58
This should now be fixed in [v0.0.5](https://github.com/qupath/qupath-bioformats-extension).

Also improved the preferences, and added descriptions to the `ReadMe` on the main page.

**Closed** 2018-04-21 07:28 UTC
