### ISSUE TITLE
Enter coordinates for ROI rectangle and file name to run cell detection from command line

### ISSUE THREAD

**Issue by aditsanghvi94** [qupath/qupath#90] opened 2017-08-04 19:24 UTC
Hi,
I want to test basic cell detection in QuPath, from the command line. 
Is it possible to enter coordinates (from a user) and a specified image, and then have QuPath run any script on that image?

eg. groovy detect.groovy -x 2,2 -y 3,3 ~/image.svc

This should open up image.svc, draw a rectangle from 2,3 to 2,3 and run the following code. It's default cell detection code from QuPath.

`//setImageType('BRIGHTFIELD_H_DAB');
//
//setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
//createSelectAllObject(true);
//runPlugin('qupath.imagej.detect.nuclei.WatershedCellMembraneDetection', '{"detectionImageBrightfield": "Hematoxylin",  "requestedPixelSizeMicrons": 1.0,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 40.0,  "maxAreaMicrons": 300.0,  "threshold": 0.2,  "maxBackground": 2.0,  "watershedPostProcess": true,  "excludeDAB": true,  "cellExpansionMicrons": 15.0,  "limitExpansionByNucleusSize": false,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}');
//selectObjectsByMeasurement("Nucleus/Cell area ratio < .13")
//clearSelectedObjects(true);
//clearSelectedObjects();
//saveDetectionMeasurements('~', )`

I've seen some posts on creating a ROI from coordinates, but how do I run this from the command lane and not the QuPath script GUI?  Should I include the QuPath code in the same code that handles parsing of command line arguments?

In essence, how do I link up the command line and QuPath?

**Comment by petebankhead** [comment] 2017-08-05 09:01
Closing this issue, as it is a duplicate of the discussion [here](https://groups.google.com/d/msg/qupath-users/pyHMY6-O0DM/zXF2m-COBAAJ).

**Closed** 2017-08-05 09:04 UTC
