### ISSUE TITLE
severe cell detection error - hard to reproduce

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#153] opened 2018-03-05 11:40 UTC
Hi, 

I discovered by accident, that cell detections are copied from the top right into  the bottom left area of JPG images, using watershed in fluorescence image type setting. 
It happened while analysing by script workflow and I can not reproduce it!

Here is a screenshot. The problematic areas are shown by red polygon: 
![grafik](https://user-images.githubusercontent.com/16352785/36973101-df059924-2071-11e8-9ca8-558335596f0f.png)
![grafik](https://user-images.githubusercontent.com/16352785/36973240-712c0586-2072-11e8-8f7a-2e4732aaa2a6.png)

Pete, if you need the qpddata file, it has 15 MB and can not be uploaded here. I can directly send it. 
 

Best
David

**Comment by petebankhead** [comment] 2018-03-05 12:04
The title of this issue is issue looks quite dramatic, but I don't understand what the error is at all.

Can you explain further?  Was cell detection applied to a brightfield image with the image type set to 'Fluorescence'?

**Comment by DavidMHaumann** [comment] 2018-03-05 12:10
Hi Pete, 
it happend two more times and I found in the log file, that the chosen channel 4 does not offer information for celldetection. After that QuPath switches automatically into channel 1. But Cell detection errors happen. Maybe because the switch is to slow?

You can see the nature of the cell detection errors in the screenshots. It happens, that QuPath copies celldetections form one part of the image into another one. I marked that in the screenshot above with the red polygons. 

I changed the script using directly channel 1 instead of channel 4. 
Now it seems like not to happen anymore. I keep you updated. Since I changed the channel, I analysed only two more images. 

The script uses fluorescence type on a DAB only stained jpg image for watershed cell detection. 
That seems to make no sence in the first place. But I found out by accident, that it allows cell detection in white areas if nuclei are not stained at all. 
This is very useful for many applications. 

Is there any argument against this way for image processing of a brightfield image?

**Comment by DavidMHaumann** [comment] 2018-03-05 12:58
Also after switching to channel 1 it still happens. I can repeat the same script. Sometimes I get the right cell distribution, sometimes cell detections from other parts of the image are randomly copied to places where they do absolutely not fit to the behind image content.  I could not find a pattern yet, that the phenomen might follow.

**Comment by petebankhead** [comment] 2018-03-05 13:02
Ah, now I understand.  This is a duplicate of #74 

Methods to workaround it are also described there.

**Comment by DavidMHaumann** [comment] 2018-03-05 13:03
ah ok. I look that up. Thank you.

**Closed** 2018-03-06 09:37 UTC
