### ISSUE TITLE
handshake_failure using QuPath with default AdoptOpenJDK

### ISSUE THREAD

**Issue by arvgord** [qupath/qupath#436] opened 2020-04-13 15:09 UTC
## Bug report

I've got handshake_failure using QuPath v0.2.0-m5 with default AdoptOpenJDK. It happens when I try to login to Google using [qupath-chcapi-extension](https://github.com/GoogleCloudPlatform/qupath-chcapi-extension).

**To Reproduce**
1. Add `-Djavax.net.debug=ssl:handshake:verbose` to QuPath-0.2.0-m5.cfg
2. Run QuPath using a console
2. Add qupath-chcapi-extension.
3. Click login

**Expected behavior**
When I use Amazon Corretto or OpenJDK I can log in without any issue. My understanding is AdoptOpenJDK doesn't have some cipher suites for TLSv1.2.

**Logs**
```
21:28:52.141 [Thread-9] DEBUG com.quantumsoft.qupathcloud.oauth20.OAuth20 - Login user
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.210 NOVT|null:-1|Signature algorithm, ed25519, is not supported by the underlying providers
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.210 NOVT|null:-1|Signature algorithm, ed448, is not supported by the underlying providers
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.211 NOVT|null:-1|Signature algorithm, SHA256withECDSA, is not supported by the underlying providers
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.211 NOVT|null:-1|Signature algorithm, SHA384withECDSA, is not supported by the underlying providers
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.211 NOVT|null:-1|Signature algorithm, SHA512withECDSA, is not supported by the underlying providers
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.213 NOVT|null:-1|Signature algorithm, SHA224withECDSA, is not supported by the underlying providers
javax.net.ssl|WARNING|29|Thread-9|2020-04-13 21:28:52.213 NOVT|null:-1|Signature algorithm, SHA1withECDSA, is not supported by the underlying providers
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.297 NOVT|null:-1|the previous server name in SNI (type=host_name (0), value=oauth2.googleapis.com) was replaced with (type=host_name (0), value=oauth2.googleapis.com)
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.299 NOVT|null:-1|Ignore unsupported cipher suite: TLS_AES_256_GCM_SHA384 for TLS12
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.299 NOVT|null:-1|Ignore unsupported cipher suite: TLS_AES_128_GCM_SHA256 for TLS12
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.299 NOVT|null:-1|Ignore unsupported cipher suite: TLS_CHACHA20_POLY1305_SHA256 for TLS12
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.302 NOVT|null:-1|Ignore unsupported cipher suite: TLS_AES_256_GCM_SHA384 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.302 NOVT|null:-1|Ignore unsupported cipher suite: TLS_AES_128_GCM_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.302 NOVT|null:-1|Ignore unsupported cipher suite: TLS_CHACHA20_POLY1305_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.302 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.302 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.302 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLS11
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_AES_256_GCM_SHA384 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_AES_128_GCM_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_CHACHA20_POLY1305_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.303 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.304 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.304 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.304 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.304 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.304 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 for TLS10
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.304 NOVT|null:-1|Ignore unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 for TLS10
javax.net.ssl|ALL|29|Thread-9|2020-04-13 21:28:52.313 NOVT|null:-1|Ignore disabled signature scheme: rsa_md5
javax.net.ssl|INFO|29|Thread-9|2020-04-13 21:28:52.313 NOVT|null:-1|No available application protocols
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.313 NOVT|null:-1|Ignore, context unavailable extension: application_layer_protocol_negotiation
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.314 NOVT|null:-1|Stateless resumption not supported
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.314 NOVT|null:-1|Ignore, context unavailable extension: session_ticket
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.314 NOVT|null:-1|Ignore, context unavailable extension: cookie
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.339 NOVT|null:-1|Ignore, context unavailable extension: renegotiation_info
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.340 NOVT|null:-1|No session to resume.
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.340 NOVT|null:-1|Ignore, context unavailable extension: pre_shared_key
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.344 NOVT|null:-1|Produced ClientHello handshake message (
"ClientHello": {
  "client version"      : "TLSv1.2",
  "random"              : "4B 4E DC CF 93 2D BE 6E 48 26 E6 67 92 6A 38 69 8A 4C B3 A9 2E 4A D3 A8 D3 38 FF 7D 6D E8 5F F1",
  "session id"          : "3C BA 77 B5 81 84 45 01 FV CA 61 54 15 24 DC 65 2B DD 00 37 73 1F D8 9C 83 25 73 BB 10 EF 68 42",
  "cipher suites"       : "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCAA), TLS_DHE_DSS_WITH_AES_256_GCM_SHA384(0x00A3), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_DHE_DSS_WITH_AES_128_GCM_SHA256(0x00A2), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_DSS_WITH_AES_256_CBC_SHA256(0x006A), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_DHE_DSS_WITH_AES_128_CBC_SHA256(0x0040), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_DSS_WITH_AES_256_CBC_SHA(0x0038), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_DHE_DSS_WITH_AES_128_CBC_SHA(0x0032), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]",
  "compression methods" : "00",
  "extensions"          : [
    "server_name (0)": {
      type=host_name (0), value=oauth2.googleapis.com
    },
    "status_request (5)": {
      "certificate status type": ocsp
      "OCSP status request": {
        "responder_id": <empty>
        "request extensions": {
          <empty>
        }
      }
    },
    "supported_groups (10)": {
      "versions": [ffdhe2048, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192]
    },
    "ec_point_formats (11)": {
      "formats": [uncompressed]
    },
    "signature_algorithms (13)": {
      "signature schemes": [rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, dsa_sha256, rsa_sha224, dsa_sha224, rsa_pkcs1_sha1, dsa_sha1]
    },
    "signature_algorithms_cert (50)": {
      "signature schemes": [rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, dsa_sha256, rsa_sha224, dsa_sha224, rsa_pkcs1_sha1, dsa_sha1]
    },
    "status_request_v2 (17)": {
      "cert status request": {
        "certificate status type": ocsp_multi
        "OCSP status request": {
          "responder_id": <empty>
          "request extensions": {
            <empty>
          }
        }
      }
    },
    "extended_master_secret (23)": {
      <empty>
    },
    "supported_versions (43)": {
      "versions": [TLSv1.3, TLSv1.2, TLSv1.1, TLSv1]
    },
    "psk_key_exchange_modes (45)": {
      "ke_modes": [psk_dhe_ke]
    },
    "key_share (51)": {
      "client_shares": [  
        {
          "named group": ffdhe2048
          "key_exchange": {
            0000: 5A 82 F4 1B 76 97 99 EF   78 C0 FC C3 7B 7F 05 B2  Z...v...x.......
            0010: 50 B4 7A AD 65 C5 33 1C   68 9F E6 8C 04 C0 E6 BA  P.z.e.3.h.......
            0020: F0 10 C3 D1 97 0C 4C 87   CE 46 11 7B F5 7F C7 3C  ......L..F.....<
            0030: 45 AF 60 E8 EE 08 D7 86   AE 76 B4 75 CD EE 3E EC  E.`......v.u..>.
            0040: 11 DB 07 14 D1 4E 25 8F   7A 7B 76 34 C5 D9 AF 77  .....N%.z.v4...w
            0050: A0 07 CF 41 65 BF 48 66   72 67 87 1B 9C EB E9 E9  ...Ae.Hfrg......
            0060: B8 97 38 09 02 E8 70 93   16 C4 EF 35 5D 83 74 76  ..8...p....5].tv
            00F0: 83 18 85 B2 3D 20 EC 45   98 AB 54 21 0C B7 B0 2F  ..t.= .E..T!.../
            0070: 8D 96 F8 01 E0 AD 3C 0F   18 07 0B 00 77 F3 32 E2  ......<.....w.2.
            0080: DC 68 9D F2 67 77 DF 1E   6D 06 82 66 F6 F7 8E 2B  .h..gw..m..f...+
            0090: 35 9A 85 F6 09 72 7C 5B   3C CC 87 59 84 CF 96 68  5....r.[<..Y...h
            00A0: 6B D5 81 4C 74 B9 A7 91   98 49 0B 12 3F 8C E1 52  k..Lt....I..?..R
            00B0: E3 B3 53 B9 78 ED 29 56   82 E3 13 31 16 C0 6A A7  ..S.x.)V...1..j.
            00C0: F8 5A 8F FE 94 77 14 0A   22 0D 51 66 A1 55 BD 6B  .Z......".Qf...k
            00D0: D9 2E 4A 4F 9B 78 15 9B   53 1D 03 91 48 A0 92 D2  ..JO.x..S...H...
            00E0: 0A 26 24 32 18 15 C1 2B   1E 00 64 37 CE D4 34 29  .&$2...+..d7..4(
            
          }
        },
      ]
    }
  ]
}
)
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.416 NOVT|null:-1|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
javax.net.ssl|ERROR|29|Thread-9|2020-04-13 21:28:52.417 NOVT|null:-1|Fatal (HANDSHAKE_FAILURE): Received fatal alert: handshake_failure (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
  	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
  	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
  	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
  	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
  	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
  	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
  	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
  	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
  	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
  	at shaded.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
  	at shaded.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
  	at shaded.com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
  	at shaded.com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
  	at shaded.com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:576)
  	at shaded.com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:493)
  	at com.quantumsoft.qupathcloud.oauth20.OAuth20.getCredential(OAuth20.java:84)
  	at com.quantumsoft.qupathcloud.dao.CloudDaoImpl.createRequestForObjectList(CloudDaoImpl.java:352)
  	at com.quantumsoft.qupathcloud.dao.CloudDaoImpl.getProjects(CloudDaoImpl.java:124)
  	at com.quantumsoft.qupathcloud.gui.windows.CloudWindow.lambda$authorizationPage$4(CloudWindow.java:184)
  	at java.base/java.lang.Thread.run(Unknown Source)}

)
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.417 NOVT|null:-1|close the underlying socket
javax.net.ssl|DEBUG|29|Thread-9|2020-04-13 21:28:52.417 NOVT|null:-1|close the SSL connection (initiative)
```

**Desktop**
 - OS:Ubuntu - 18.04 LTS
 - QuPath Version - v0.2.0-m5

Also, I tested it using v0.2.0-m9 and got the same issue.

**Comment by petebankhead** [comment] 2020-04-13 15:41
I have seen the same error before, but not since updating to JDK 14 (which will be a minimum requirement for v0.2.0, since it greatly simplifies building by including jpackage).

To avoid the error with JDK 11-13, I think you'd need to change the build script to include more modules with jlink.

**Comment by arvgord** [comment] 2020-04-13 16:03
As a workaround, I launch QuPath with installed JAVA on my PC(e.g. OpenJDK or Amazon Corretto). Do you have a plan to fix this issue in QuPath?

**Comment by petebankhead** [comment] 2020-04-13 16:07
Not for earlier releases; https://github.com/qupath/qupath/commit/857d7670007e31631a97e7a854aba098ebc70d34 + JDK 14 fixes any handshake errors I have seen and will be in future releases.

**Comment by sdvillal** [comment] 2020-04-13 20:29
xref: https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/issues/33

Thanks for looking into this @arvgord. I can confirm that using a full-blown runtime gets me past the handshake - I quickly tried with a self-compiled qupath version from master, the precompiled cloud extension v2.0.5 and a complete adoptopenjdk 14 runtime - all this trouble because it actually was for me the easiest thing to quickly try. I have some other problems now, but that might just be because of compiling everything from source. I will check in the next few days and report when needed.

I guess it would be wise to recommend using a complete runtime whenever plugins come into the picture, or even build alternative qupath packages with "fat runtimes"?

**Comment by petebankhead** [comment] 2020-04-14 06:25
Yes, that may be necessary. Until now it has not been an issue, but I recently updated `build.gradle` on the dev branch to optionally include all modules to make this easier:
```
./gradlew clean build test createPackage -PjreModules=all
```

**Comment by petebankhead** [comment] 2020-04-22 11:57
v0.2.0-m10 is now available. Please let me know if is has the same problem, or if the issue can be closed.

**Comment by sdvillal** [comment] 2020-04-23 06:26
I'm waiting for the extension to be adapted to the new APIs (see https://github.com/GoogleCloudPlatform/qupath-chcapi-extension/issues/35). I will close once I confirm that works. Otherwise, I think allowing to ship all JRE modules is already a great step solving these issues, and just wonder if it would be worth releasing also these "fat versions".

**Comment by petebankhead** [comment] 2020-04-23 06:31
V0.2.0-m10 uses the `--bind-services` option with jlink, which I think is a reasonable compromise - along with a build option to include everything.

**Comment by sdvillal** [comment] 2020-04-29 20:39
Fixed indeed, thanks Pete!

**Closed** 2020-04-30 04:41 UTC
Labels: bug

**Comment by dridk** [comment] 2025-03-05 16:00
> As a workaround, I launch QuPath with installed JAVA on my PC(e.g. OpenJDK or Amazon Corretto). Do you have a plan to fix this issue in QuPath?

How do you run with your own version ?
