### ISSUE TITLE
slide label not showing in 0.2.3

### ISSUE THREAD

**Issue by oharismendy** [qupath/qupath#643] opened 2020-11-20 18:53 UTC
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [ x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [ x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x ] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [ x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
The slide label does not show when selecting View > Slide Label: the image is empty

**To Reproduce**
1. Go to 'View'
2. Click on 'Show Slide Label'
3. See error

**Expected behavior**
A window opens displaying the slide label. It worked find in 0.1.2 using the same SVS file, but for some reason no longer shows the slide label image in 0.2.3. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - QuPath Version 0.2.3

**Additional context**
images as in SVS format and I know the slide labelled was scanned as it is visible in version 0.1.2

**Comment by melvingelbard** [comment] 2020-11-20 19:13
Hi @oharismendy,

I've tried on some of my svs images but it seems to work fine.
What error message does QuPath show whenever you try to open the slide label?

**Comment by Svidro** [comment] 2020-11-20 19:41
@oharismendy,
Can you confirm that you are doing this within a Project?

**Comment by oharismendy** [comment] 2020-11-20 19:51
There is no error message. Just "No Slide label available" in the slide label viewer. I know there is a slide label in the file as I can see it in version 0.1.2. I am doing this within a project indeed.

**Comment by Svidro** [comment] 2020-11-20 22:59
But does the Macro image show anything? Or is it there?

**Comment by oharismendy** [comment] 2020-11-20 23:29
> But does the Macro image show anything? Or is it there?

Thanks. I can indeed see it under the Image tab under "Series 1 (label)" (I did not know about this). But access from the pull down menu and label pop-up viewer is not working, which remains an issue.

**Comment by petebankhead** [comment] 2020-11-23 11:06
@oharismendy it sounds like in v0.2 the image is being opened with Bio-Formats. In v0.1.2 OpenSlide would have been used by default (unless you installed the Bio-Formats extension), and this flags specific images as label for a few formats (including .svs).

You can choose the image reader when importing an image to a project: https://qupath.readthedocs.io/en/latest/docs/tutorials/projects.html#add-images

Because QuPath relies upon open source image readers that support a wide range of formats, it's difficult/impossible to *know* in all cases whether an image stored within a file as intended a 'full' image for analysis, label or macro image... particularly since different vendors write images in different ways, and we don't have specifications for the formats. It may be necessary for us to remove the label pop-up in the future, since it will inevitably fail to find a label sometimes sometimes.

Misassigning a full image as a label is a big problem, since QuPath doesn't support any analysis on labels - therefore we need to err on the side of caution.

If you can share an example image along with details of how it was written (e.g. software/scanner) then we might be able to add some logic to handle this specific case but otherwise we can only guess what a fix might be.

**Comment by oharismendy** [comment] 2020-11-23 17:43
> @oharismendy it sounds like in v0.2 the image is being opened with Bio-Formats. In v0.1.2 OpenSlide would have been used by default (unless you installed the Bio-Formats extension), and this flags specific images as label for a few formats (including .svs).
> 
> You can choose the image reader when importing an image to a project: https://qupath.readthedocs.io/en/latest/docs/tutorials/projects.html#add-images
> 
> Because QuPath relies upon open source image readers that support a wide range of formats, it's difficult/impossible to _know_ in all cases whether an image stored within a file as intended a 'full' image for analysis, label or macro image... particularly since different vendors write images in different ways, and we don't have specifications for the formats. It may be necessary for us to remove the label pop-up in the future, since it will inevitably fail to find a label sometimes sometimes.
> 
> Misassigning a full image as a label is a big problem, since QuPath doesn't support any analysis on labels - therefore we need to err on the side of caution.
> 
> If you can share an example image along with details of how it was written (e.g. software/scanner) then we might be able to add some logic to handle this specific case but otherwise we can only guess what a fix might be.

Thanks. It makes perfect sense. I think dropping the pop-up and clarifying this label image is available under master is likely a safer way to go. Unless my issue is very rare.

**Comment by petebankhead** [comment] 2021-04-08 18:41
Closing this, because the logic to try to identify a slide label has been improved. The changes will be in v0.3.

**Closed by petebankhead** 2021-04-08 18:41 UTC
