### ISSUE TITLE
QuPath won't open vips produced tiled tiff pyramid

### ISSUE THREAD

**Issue by yliu7366** [qupath/qupath#967] opened 2022-05-11 14:59 UTC
**Describe the bug**
Used vips 8.11 to produce tiled tiff pyramid image with jpeg compression. QuPath 0.3.2 won’t open it and says the image file is not a tiled pyramid. Changed my image file extension to .svs, QuPath will load it but shows a blank (black) window. Checked with tiffinfo that my image file is indeed tiled pyramid image with jpeg compression. Feel confused QuPath does open Aperio SVS files with jpeg compression but won’t open vips produced tiled tiff pyramid files with jpeg compression.

**Desktop (please complete the following information):**
 - OS: macOS
 - QuPath Version 0.3.2

**Comment by petebankhead** [comment] 2022-05-11 15:55
Hi, I see you've also posted this at https://forum.image.sc/t/qupath-0-3-2-shows-blank-black-image-for-vips-8-11-produced-tiled-tiff-pyramid-image/66896

QuPath [depends on Bio-Formats and OpenSlide](https://qupath.readthedocs.io/en/stable/docs/intro/formats.html) to read pyramidal images, so if the image doesn't display properly then it's likely because your image isn't supported by either of them. If needed, you can [specify which library reads the image during import to a project](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html#add-images).

See also https://www.libvips.org/2020/06/18/What%27s-new-in-8.10.html#pyramids

The forum is a better place to discuss it, because it's (probably) not a bug in QuPath - so I'll close this issue to prevent parallel discussions.

**Closed by petebankhead** 2022-05-11 15:55 UTC
