### ISSUE TITLE
SCN file open only in low magnification

### ISSUE THREAD

**Issue by rgranit** [qupath/qupath#278] opened 2019-03-11 14:33 UTC
Hi All,

I'm attempting to open SCN files, I could get the image open but only in low magnification (x1.25).. any suggestions how to resolve this?

Thanks!

* Running Qupath 0.1.2 on Mac Os 10.14.3 with bioformats 6.0 and

**Comment by petebankhead** [comment] 2019-03-11 15:57
According to this - https://github.com/qupath/qupath/issues/270 - the issue may already be resolved in the latest milestone release. See https://qupath.github.io/QuPath-v0.2.0

Also potential duplicate of the (somewhat vague...) https://github.com/qupath/qupath/issues/273

**Comment by rgranit** [comment] 2019-03-11 16:02
Thanks, I will attempt to upgrade and report if it helps (I admit I was afraid to upgrade so not to introduce new bugs 😄 )

**Comment by petebankhead** [comment] 2019-03-11 16:05
Sounds like a healthy & commendable fear :) But there will be no more updates to v0.1.2, so any fix (if not already there) will be through that path.

**Comment by rgranit** [comment] 2019-03-11 16:20
Thanks @petebankhead following the upgrade it works like charm 👍

**Closed** 2019-03-14 18:55 UTC
Labels: bug

**Comment by One-sixth** [comment] 2022-03-18 09:19
@petebankhead
I also had issues with low magnification for SCN files. 
My QuPath verison is 0.3.2
And I can't open the first series, if I open the first series it will get stuck.
![blur1](https://user-images.githubusercontent.com/23693633/158974003-f65081f3-e368-403f-b86d-baed82ca34a2.png)
![blur2](https://user-images.githubusercontent.com/23693633/158974056-11df2ac2-3fbe-4465-a0e2-db87b2521a88.png)
![blur3](https://user-images.githubusercontent.com/23693633/158974186-56780db2-1bf1-429a-8d48-d96cc187ea3b.png)

**Comment by petebankhead** [comment] 2022-03-18 09:54
@One-sixth this sounds like a duplicate of https://github.com/qupath/qupath/issues/904

The underlying bug has been fixed, but needs a new QuPath release. In the meantime, you can [add your images to a project](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html) to open them.

**Comment by One-sixth** [comment] 2022-03-18 10:57
> @One-sixth this sounds like a duplicate of #904
> 
> The underlying bug has been fixed, but needs a new QuPath release. In the meantime, you can [add your images to a project](https://qupath.readthedocs.io/en/stable/docs/tutorials/projects.html) to open them.

Thanks a lot, problem solved.
