### ISSUE TITLE
QuPath Viewer Hangs on Ubuntu 22.04 Due to OpenSlide Library Loading Issue When Opening .tiff Images"

### ISSUE THREAD

**Issue by naveensweth** [qupath/qupath#1491] opened 2024-04-02 13:33 UTC
I am encountering an issue with the QuPath Viewer while attempting to load a .tiff image. When I click on the image to view it in the viewer, the QuPath UI hangs, and it appears that the OpenSlide library is not loading correctly.

I have attempted to resolve this by installing the OpenSlide library using the package manager, but the problem persists. The logs indicate that OpenSlide is loaded successfully, yet an error is thrown stating “No OpenSlide search path supplied and failed to load OpenSlide.”

It’s worth noting that I have created a project and added the .tiff image to the project using a Groovy script. I am invoking QuPath through the command line.

Note: I have successfully loaded a .tiff image in QuPath Viewer using a script without any issues on the Windows platform(openslide installed with qupath binary). However, on Linux, I encountered a problem where OpenSlide is not installed by default with QuPath binaries. Even after installing OpenSlide separately using a package manager, the issue persists.

Any insights or suggestions on resolving this issue would be greatly appreciated.

qupath_exe=“/opt/QuPath/bin/QuPath”
“$qupath_exe” script /usr/addImages.groovy --args “$volumeDataDir” --args “$QupathProjDir”
“$qupath_exe” -q -p “$QupathProjDir”/QuPathProject/project.qpproj

OS : Ubuntu :22.04

![image](https://github.com/qupath/qupath/assets/6927393/5bc64744-cde9-4e11-8261-dc2c401727f4)
![image](https://github.com/qupath/qupath/assets/6927393/cad90c79-ef22-4339-8068-e50407028b6c)

**Comment by petebankhead** [comment] 2024-04-02 15:05
This seems to be a duplicate of https://forum.image.sc/t/qupath-viewer-hangs-on-ubuntu-22-04-due-to-openslide-library-loading-issue-when-opening-tiff-images/94325

**Comment by petebankhead** [comment] 2024-04-17 06:43
I will close this because the main discussion is on image.sc, and it remains unclear if there is anything to fix on the QuPath side.

**Closed by petebankhead** 2024-04-17 06:43 UTC
Labels: bug
