### ISSUE TITLE
convert annotations into detections. Counting in the annotations TAB is wrong

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#259] opened 2019-01-25 18:46 UTC
Hi, 

if manually drawn annotations are converted into detections with the following script, they will be correctly counted in the annotation measurements. 
But the Annotation TAB at the left side will count only "now detections minus one!"
Why is that?

import qupath.lib.objects.PathTileObject
import qupath.lib.roi.RectangleROI
import qupath.lib.scripting.QP

selectObjects { p -> p.getPathClass() == null && p.isAnnotation() && p.getROI().getArea() < 4000 }
annotations = getSelectedObjects()
// Create corresponding detections (name this however you like)
def classification = getPathClass('NAME')
def detections = annotations.collect {
    new qupath.lib.objects.PathDetectionObject(it.getROI(), classification)
}

// Remove ellipse annotations & replace with detections
removeObjects(annotations , true)
addObjects(detections)
fireHierarchyUpdate()

**Comment by Svidro** [comment] 2019-01-25 18:57
Could you clarify with what you are seeing?  Everything looks normal to me:
![image](https://user-images.githubusercontent.com/23145209/51766569-bb855380-208f-11e9-923a-3df87546b933.png)

![image](https://user-images.githubusercontent.com/23145209/51766611-db1c7c00-208f-11e9-9003-426a97e2e8f6.png)

I would expect to find 4 sub-objects that are smaller than the size cutoff.

**Comment by Svidro** [comment] 2019-01-25 19:01
Though that was using version 1.2! I have not checked 1.3

**Comment by DavidMHaumann** [comment] 2019-01-25 19:54
before script: I added 4 annotation ROIs by hand with brush tool (in Version 0.12)
![grafik](https://user-images.githubusercontent.com/16352785/51768744-7427b300-20e1-11e9-9e41-c3cfb1c98a2c.png)
![grafik](https://user-images.githubusercontent.com/16352785/51769252-e9e04e80-20e2-11e9-8e0f-1458d9bc175a.png)
Only 3 of the four are counted. The Rectangle shows 42 objects - 39 of them are cells. 

After conversion: it shows only 41 objects inside the Rectangle. 
![grafik](https://user-images.githubusercontent.com/16352785/51769369-2ad86300-20e3-11e9-85bc-501de1b8a154.png)

two of the manually drawn cells show a thinner boarder: 
![grafik](https://user-images.githubusercontent.com/16352785/51769423-45aad780-20e3-11e9-93e9-769c7dbd5451.png)
They are the ones that are not counted. 

The annotation measurement shows the correct 43 cells: 
![grafik](https://user-images.githubusercontent.com/16352785/51769458-65420000-20e3-11e9-95d3-0dbd6214d743.png)

**Comment by petebankhead** [comment] 2019-01-25 20:00
Did that happen once or does it happen reproducibly?  My first guess is that somehow the detections with thinner lines are inside (duplicated) detections.  I don't know why.

**Comment by Svidro** [comment] 2019-01-25 20:02
Yeah, I was wondering what the Hierarchy tab looks like. Does anything there have any child objects?

**Comment by DavidMHaumann** [comment] 2019-01-25 20:42
in the hierarchy tab are indeed two area AWT even after conversion into cells: 
![grafik](https://user-images.githubusercontent.com/16352785/51771661-0633b980-20ea-11e9-83ba-889d94c3508a.png)

what does that mean?

**Comment by DavidMHaumann** [comment] 2019-01-25 20:42
yes - the problem is reproducible. 
Until now I was aware of one lacking cell. This time it was two cells lacking.

**Comment by DavidMHaumann** [comment] 2019-01-25 20:44
oh i have to correct myself: 
![grafik](https://user-images.githubusercontent.com/16352785/51771740-4abf5500-20ea-11e9-8d11-d6c99115509f.png)

![grafik](https://user-images.githubusercontent.com/16352785/51771750-5743ad80-20ea-11e9-9005-f9a4318c9058.png)

there is a doublicated cell!
But it is not counted twice?

**Comment by Svidro** [comment] 2019-01-25 20:45
Yep, that looks right. Two cells are inside other objects, which matches up with the 41 count and the 43 count. The only one that doesn't make sense is the 42 count.

41 is the number of child objects for the rectangle. Then two of those child objects have their own child objects.

**Comment by DavidMHaumann** [comment] 2019-01-25 20:47
i counted manually. 43 cells is correct. If the 2 strange cells with doublicated cells would be counted twice, there would be 45. 
Annotation measurments shows the desired 43 cells. The rectangle in annotations tab shows 41 "objects".

**Comment by Svidro** [comment] 2019-01-25 20:48
I think all of those things may be correct.
If you collapse the rectangle in the Hierarchy tab, do you see two cells "outside" of the rectangle (although they are are mostly inside of it?

**Comment by DavidMHaumann** [comment] 2019-01-25 20:52
Hiere is the awt in the upper hierarchy: 
![grafik](https://user-images.githubusercontent.com/16352785/51772100-6ecf6600-20eb-11e9-9ac1-17b5abf6640c.png)

then the one in the lower hierarchy: 
![grafik](https://user-images.githubusercontent.com/16352785/51772113-7abb2800-20eb-11e9-982e-384d7b814a1b.png)


seems like the strange cell became a descendent cell/object from the normal cell.  Is that the desired behavior?

**Comment by Svidro** [comment] 2019-01-25 20:53
Nope, that looks weird!

**Comment by DavidMHaumann** [comment] 2019-01-25 20:55
the rectangle is rotated. Maybe that is connected to that?
But I restricted the cores to 1. no parallelization.

**Comment by Svidro** [comment] 2019-01-25 20:55
If you delete the parent rectangle and re-create it, does it fix the hierarchy?  (first unrotated, then rotate it)

**Comment by DavidMHaumann** [comment] 2019-01-25 20:55
i mean- it is a jpg. So it could have been connected to the parallelization issue. But it is not.

**Comment by DavidMHaumann** [comment] 2019-01-25 20:56
recreated - unrotated. Same error again: 
![grafik](https://user-images.githubusercontent.com/16352785/51772368-1ea4d380-20ec-11e9-9bea-87a6acf1fdd6.png)

**Comment by DavidMHaumann** [comment] 2019-01-25 20:57
rotation does also not have any effect: 
![grafik](https://user-images.githubusercontent.com/16352785/51772415-39774800-20ec-11e9-9fbc-ff25fc071531.png)

**Comment by Svidro** [comment] 2019-01-25 20:59
That is really weird. I have no idea!

Ok, this is not likely to help but I am just curious, what happens if you draw a really small annotation around the two cells that are "wrong?"

**Comment by DavidMHaumann** [comment] 2019-01-25 21:02
nothing - but it is counting the new annotation?
![grafik](https://user-images.githubusercontent.com/16352785/51772698-f2d61d80-20ec-11e9-940a-9e8ba2568ab5.png)

**Comment by DavidMHaumann** [comment] 2019-01-25 21:05
thats interesting: the two cells do not become a descendent from the new annotation: 
![grafik](https://user-images.githubusercontent.com/16352785/51772785-3761b900-20ed-11e9-92da-9a7472b247e0.png)

if i draw an annotation around a normal cell - it becomes a daughter of the new ROI. 
fireHierarchyUpdate() does not change anything.

**Comment by Svidro** [comment] 2019-01-25 21:08
Huh, I just started looking around some JPEG files I have from another user and it looks like the Centroids listed for all objects are NaN, NaN.  I have no idea how QuPath is even keeping track of what is inside of what in this case!

If it is some kind of relative position tracking, I am wondering if somehow the rotation or translation of your parent rectangle altered their saved coordinates.  I don't have much experience working in JPEGs though...

**Comment by petebankhead** [comment] 2019-01-25 21:14
> yes - the problem is reproducible.
Until now I was aware of one lacking cell. This time it was two cells lacking.

Things like this make me think of parallelization and the threads of the GUI.  Not certain this is the issue, but rather than
```groovy
selectObjects { p -> p.getPathClass() == null && p.isAnnotation() && p.getROI().getArea() < 4000 }
annotations = getSelectedObjects()
```
I'd suggest trying something like:
```groovy
getAnnotationObjects().findAll { p -> p.getPathClass() == null && p.isAnnotation() && p.getROI().getArea() < 4000 }
```
As has occurred before, weird things can happen when modifying the hierarchy too quickly after selections within scripts that are run interactively in the GUI (since the GUI elements may not have completed processing before the later lines of the script have run).

If this is correct, the trouble shouldn't arise if 
1. you can avoid selecting/deselecting objects, or 
2. run the script in batch mode via _Run &rarr; Run for project_

Out of curiosity, what happens if you select one of the weird-behaving cells and run the following:
```groovy
def selected = getSelectedObject()
def parent = selected.getParent()
print selected
print parent
print selected == parent
```

**Comment by Svidro** [comment] 2019-01-25 21:15
Oh wait, I am guessing it's tracking them in pixel space, and NaN centroids are due to the conversion being unknown. My mistake.

**Comment by petebankhead** [comment] 2019-01-25 21:15
> Huh, I just started looking around some JPEG files I have from another user and it looks like the Centroids listed for all objects are NaN, NaN. I have no idea how QuPath is even keeping track of what is inside of what in this case!

I remember that being reported, should be fixed now...

**Comment by Svidro** [comment] 2019-01-25 21:16
This comp is using 1.2 still so... might be fixed in 1.3?

**Comment by DavidMHaumann** [comment] 2019-01-25 21:30
@ Pete: the result from 
def selected = getSelectedObject()
def parent = selected.getParent()
print selected
print parent
print selected == parent

is

INFO: Starting script at Fri Jan 25 22:30:05 CET 2019
INFO: Area (AWT) (Sinneszelle)
INFO: Polygon (Sinneszelle)
INFO: false

**Comment by DavidMHaumann** [comment] 2019-01-25 21:32
i also ran 
getAnnotationObjects().findAll { p -> p.getPathClass() == null && p.isAnnotation() && p.getROI().getArea() < 4000 }

the result was even more strange cells: 
![grafik](https://user-images.githubusercontent.com/16352785/51774030-23b85180-20f1-11e9-841c-f7fa7ce75aa6.png)

**Comment by DavidMHaumann** [comment] 2019-01-25 21:40
even without rotated rectangles it happens

**Comment by petebankhead** [comment] 2019-01-25 21:45
I tried to replicate it with v0.1.2 and the current code I am working on and could not.

**Comment by petebankhead** [comment] 2019-01-26 09:41
For the existing 'true' cells, check if the annotations fall inside the full cell boundary (assuming that in this case you're only displaying the nuclei, but actually both the nucleus and cytoplasm regions exist).

(If this is correct, it highlights that the `toString` method used for QuPath objects isn't very good... knowing that the parent object has a polygon ROI [which the script I posted above reveals] has limited use - it would help if printing out the object also told you if it was an annotation, detection, cell or whatever.  I will make this change...)

**Comment by DavidMHaumann** [comment] 2019-01-26 18:18
hi Pete. I did not really understand the meaning of that. 
But i made the test to put points into the cytoplasm of existing cells and a point outside the cytoplasm of existing cells. 
The result was: all points (that i converted into cells with Mikes new script) that were inside existing cells were not counted as objects inside the annotations tab. But counted in the measurments. 
It corresponds with the thickness of the boundary: 
![grafik](https://user-images.githubusercontent.com/16352785/51791164-1a85be00-219f-11e9-8116-9384b0c09ab4.png)

**Comment by petebankhead** [comment] 2019-01-26 18:33
If I understand correctly, then everything is actually behaving as it is supposed to... adding a new object that is inside an existing one (even a cell) gets positioned 'below' it.  So... it might not be what you wanted, but it is correct - right?

If you don't need the cell boundaries (or associated measurements) then by reducing the 'cell expansion' parameter to zero during detection you can create a 'nucleus detector' only, which may help avoid confusion.

**Comment by Svidro** [comment] 2019-01-26 18:51
Yep, just counting the direct children, one level below the annotation.
![image](https://user-images.githubusercontent.com/23145209/51791450-15e9e700-2158-11e9-9eb8-18eb6b59e11e.png)

Kinda shows it as well. Almost every annotation has one child annotation. Except one of the lowest ones, and some of those have 0 children. It doesn't matter if the objects are cells, it just counts direct child objects. Which is nice, since it prevents subcellular detections from being counted! That could get crazy.

**Comment by petebankhead** [comment] 2019-01-26 18:58
> Which is nice, since it prevents subcellular detections from being counted! That could get crazy.

Yes, I have some distant memory that that was the reason... and also detections inside other detections need (progressively) thinner lines, giving a visual clue.

**Closed** 2019-05-21 12:34 UTC
Labels: question
