### ISSUE TITLE
Ability to specify tile size in micrometers when creating sparse image

### ISSUE THREAD

**Issue by MarkZaidi** [qupath/qupath#1407] opened 2023-10-27 18:02 UTC
**Is your feature request related to a problem? Please describe.**
When creating annotations via the `specify annotation` command, there's an option to specify the tile size in micrometers instead of pixels. However, there is no option to specify the preferred image width in micrometers, of a sparse image created through `create training image`
![image](https://github.com/qupath/qupath/assets/52012166/fed6a046-2e7c-49ce-b972-950f707df108)

**Describe the solution you'd like**
A `Use um` checkbox should be present in the `create training image` window.

**Describe alternatives you've considered**
Manually calculating what the preferred image width would be by converting micrometers to pixels.

**Additional information**

There are a few tools that also only support specifying sizes in pixels instead of um, such as `split annotations by lines`.
![image](https://github.com/qupath/qupath/assets/52012166/1c8d6ad3-5c70-4751-933f-49a0ba02f3e0)

 It's somewhat cumbersome to convert micrometers to pixels for tools that lack this option, and makes it harder to apply workflows on subsequent batches of images acquired at different resolutions

**Comment by petebankhead** [comment] 2023-10-28 11:21
When splitting annotations by lines, my expectation is that the thickness will usually be 0. Supporting different units risks increasing the code complexity considerably, because the command must also be scriptable and then somehow the units need to incorporated into any script.

Additionally, QuPath is moving towards greater generality. It is increasingly used for images where µm is an inappropriate unit, so I'm reluctant to add additional code that assumes µm as the only alternative to pixels. And a properly generic system will take a lot more effort to develop (not helped by the fact that Java has no built-in support for converting units... it's a recurring theme, e.g. [here](https://jcp.org/en/jsr/detail?id=385), but as far as I'm aware there are a multiple implementations and it's not clear which, if any, we should use).

This also affects the sparse image server: at the point the dialog is shown, we don't know if the pixel size is available in µm for the regions that will be required to generate the server. Furthermore, the dialog itself is [auto-generated from a `ParameterList`](https://github.com/qupath/qupath/blob/main/qupath-extension-processing/src/main/java/qupath/process/gui/commands/CreateTrainingImageCommand.java#L90), which limits the ability to toggle between units.

Added to that, I'm not terribly happy with the generation of 'dynamic' training images generally; the code is really complex (since the images can be quite heterogeneous), and performance can be poor whenever many images need to be accessed to create the final result. Therefore I wonder if creating a new command that defaults to writing the image as a new file would be preferable anyway.

I'll leave this open for a while in case there are further comments, but my feeling is that the development-and-maintainence-time-to-benefit ratio isn't favorable enough to work on this in the core QuPath software; there are too many higher priorities, and if I'd rather focus efforts on simplicity, maintainability and generalizability in the code.

Anyone else can create a new extension to provide an alternative implementation for any of the commands if they want to.

**Comment by MarkZaidi** [comment] 2023-10-28 21:50
Fair enough, this was also an issue with Definiens back when they were porting their platform from their geospatial analysis predecessor [eCognition](https://geospatial.trimble.com/en/products/software/trimble-ecognition). Much of the backend had hardcoded units of km, which broke a lot when transitioning to a um default. I imagine this would also be an issue if QuPath was applied for the analysis of macroscopic data such as geospatial analysis.

> Therefore I wonder if creating a new command that defaults to writing the image as a new file would be preferable anyway.

That would be useful, as I've noticed a substantially increased image load time when opening a sparse image consisting of images hosted on a NAS. One idea would be to write an ome.tiff of the sparse image inside the QuPath project on the first instance that the sparse image is loaded, and each subsequent time it's opened, it'll read that image. If the image is removed, it'll be regenerated the next time it's corresponding project entry is opened (i.e. if you want to reduce file size when sending it to a collaborator).

Tangentially related, but many scripts will break when running it on a sparse image with an empty region:
![image](https://github.com/qupath/qupath/assets/52012166/e8f61447-87a5-4e31-8c9d-377c6182ccdf)
(0.5.0-rc2)

**Comment by petebankhead** [comment] 2023-11-26 11:12
> One idea would be to write an ome.tiff of the sparse image inside the QuPath project on the first instance that the sparse image is loaded, and each subsequent time it's opened, it'll read that image.

It's tempting, but OME-TIFF can take a long time to write, and that requires some decisions to be made regarding compression (which could impact pixel classifiers). Therefore I think writing any image needs to be explicitly triggered by the user to avoid unwelcome surprises.

> Tangentially related, but many scripts will break when running it on a sparse image with an empty region:

I tried but couldn't replicate this.

Given the intention to revisit sparse images generally, I wouldn't plan to spend time fixing it unless it is shown to be problematic in a normal workflow, with a reproducible failing example (which would really belong in a separate issue).

**Closed by petebankhead** 2023-11-26 11:12 UTC
Labels: enhancement
