### ISSUE TITLE
Saved Annotations

### ISSUE THREAD

**Issue by HMReid** [qupath/qupath#71] opened 2017-05-04 09:05 UTC
To whom it may concern,

I made a number of line measurements on an IHC image and at the end of the session, closed QuPath, saving the file with the annotations.  However, when opening the image again the measurements have all changed where one point of each line has moved to the top left hand corner of the image.  I have tried locking the annotation but this has not helped.  Is there a way round this or something I'm missing in the preferences?

Regards
Helen

**Comment by petebankhead** [comment] 2017-05-04 17:27
Hi Helen,

Thanks very much for reporting this.  I looked into it and unfortunately there is a bug in the code that reads the lines.  I hadn't heard of the problem before or noticed it myself (I guess lines are not used as widely as other shapes, which don't have this problem...).

Fortunately, the lines appear to actually be *stored* correctly.  This makes it possible to get them back and have them appear properly in a later version of QuPath.

In the meantime, you could try opening one of your previously-annotated images and going to *Automate &rarr; Show script editor*.  Then paste in the following code:

```groovy
getAnnotationObjects().each {
    roi = it.getROI()
    if (roi instanceof qupath.lib.roi.LineROI) {
        roi.x2 += roi.x
        roi.y2 += roi.y
    }
}
fireHierarchyUpdate()
```
and go to *Run &rarr; Run* to run the script.

Hopefully this will correct the lines for you.

I suggest running the script as the first thing you do each time you open an image with lines on it.  If you are working with a project, it might help if you save the script into a subdirectory of your project called 'scripts'.  Then it should appear automatically inside QuPath’s menus every time you open that project, under *Automate &rarr; Project scripts…*
(Alternatively, you can save the script anywhere and just drag it on top of QuPath to open it quickly.)

Pete

**Comment by HMReid** [comment] 2017-05-05 09:12
Hi Pete,

Thanks for your prompt reply.  I tried the script out, it appears to work for most of the line measurements made.  

For one of my images, it required a couple of runs, perhaps due to the fact that when I first came across the problem, I corrected each line individually in an attempt to correct the issue.  Also, in this image, some of the lines were corrected on the first attempt but then when I re-ran the script to correct others, they changed such that one end of the lines moved to the bottom, right corner.  These latter lines were added later to the image.  Would there be a way of correcting these, e.g., with a minor adjustment to the script?

Regards
Helen

**Comment by petebankhead** [comment] 2017-05-06 07:56
I hadn't seen the problem where some lines require multiple corrections, but from your explanation I think I understand what has happened.

The issue should be predictable and reproducible; here's the background:

* When a line is drawn, it is represented inside QuPath by the coordinates of its end points, ```(x1,y1)``` and ```(x2,y2)```
* When the line is saved, these coordinates are written (correctly) into the ```.qpdata``` file
* When the ```.qpdata``` file is loaded again later, the first thing QuPath does is read the coordinates and convert them into ```(x1, y1)``` and ```(x2-x1, y2-y1)```.

This last step is a bug; there is no need to subtract the first coordinates from the second.  It happens because, long ago (and before being released), QuPath stored its lines differently (with the first coordinate and then displacement).... and this bit of the code was not updated when it should have been, and lines were used rarely enough for it to go unnoticed.

With that in mind, the error can be cumulative; if you open a ```.qpdata``` file and the lines display wrongly, and then you save it again, QuPath will now save the wrong coordinates... and, when reading them, make them even more wrong, i.e. ```(x2-x1-x1, y2-y1-y1)```.  You'd have to run the script twice to fix such lines.

Therefore it is important to have all your lines corrected before you save, and then run the script to fix them immediately after opening the image.  This avoids having a combination of correct and incorrect lines on the image at the same time.

The purpose of the script is to go through and fix the second coordinate for all your lines by adding the first coordinate.  It does this for all lines, regardless of whether or not they are correct.  If you want to change only some of the lines then @Svidro's idea is great - select the lines you want to change (e.g. in the list at the top of the *Annotations* tab on the left of the screen) and run this script instead:

```groovy
getSelectedObjects().each {
    roi = it.getROI()
    if (roi instanceof qupath.lib.roi.LineROI) {
        roi.x2 += roi.x
        roi.y2 += roi.y
    }
}
fireHierarchyUpdate()
```

This will fix the selected lines, and leave the others unchanged.

**Comment by HMReid** [comment] 2017-05-08 10:14
Hi Pete (& @Svidro),

Thanks for all your help & suggestions, the problems with lines have now been resolved and I have saved the script in the project.

Thanks
Helen

**Comment by petebankhead** [comment] 2018-03-19 12:47
At long last this issue should be resolved without need for an extra script if you use the version of QuPath described in [this blog post](https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html).

**Comment by petebankhead** [comment] 2019-03-09 06:44
This should be fixed in the latest milestone release https://github.com/qupath/qupath/commit/6be3e55afa7e36cb3543ee3c06df56209ee913d1

**Closed by petebankhead** 2019-03-09 06:44 UTC
Labels: bug
