### ISSUE TITLE
getTileObjects() not getting tile objects

### ISSUE THREAD

**Issue by yau-lim** [qupath/qupath#1065] opened 2022-09-28 16:25 UTC
## IMPORTANT!

This section is **only** for bug reports, which **must** follow the template below.

Please post any other questions to the official QuPath forum at https://forum.image.sc/tags/qupath

If in doubt, use [image.sc](https://forum.image.sc/tags/qupath). This helps us keep things organized.

## Before we begin...

Before submitting your bug report, please check the following:

* [x] I've definitely found a bug (it you're not sure, please use [image.sc](https://forum.image.sc/tags/qupath) instead)
* [x] I've checked https://qupath.github.io for a new release that might already have fixed the issue
* [x] I've checked the [Changelog](https://github.com/qupath/qupath/blob/master/CHANGELOG.md) to see if the bug has already been fixed in the next release
* [x] I've checked for existing GitHub issues describing the same problem

## Bug report

**Describe the bug**
Trying to get tile objects using `getTileObjects()` will result in an error:
```
ERROR: MissingMethodException at line 19: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getTileObjects() is applicable for argument types: () values: []

ERROR: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:404)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.access$100(GroovyScriptEngineImpl.java:90)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl$3.invokeMethod(GroovyScriptEngineImpl.java:303)
    org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:73)
    org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
    org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
    org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
    Script8.run(Script8.groovy:20)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
    org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:982)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:914)
    qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:829)
    qupath.lib.gui.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1345)
    java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
```
import qupath.lib.roi.RoiTools
import qupath.lib.geom.ImmutableDimension

createSelectAllObject(true);
def parentAnno = getSelectedObject()

int tileSizePreferred = 100
int tileSizeMax = tileSizePreferred*1.1
def sizePreferred = ImmutableDimension.getInstance(tileSizePreferred, tileSizePreferred)
def sizeMax = ImmutableDimension.getInstance(tileSizeMax, tileSizeMax)
boolean fixedSize = false
int overlap = tileSizePreferred*0.1

def tilesRoi = RoiTools.computeTiledROIs(parentAnno.getROI(), sizePreferred, sizeMax, fixedSize, overlap)
def tilesObj = tilesRoi.collect{ return PathObjects.createTileObject(it) }
addObjects(tilesObj)

println getDetectionObjects().findAll{it.isTile()}
println getTileObjects()
```

**Expected behavior**
The expected behaviour can be obtained by an alternative method:
`getDetectionObjects().findAll{it.isTile()}`

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version: 0.3.2

**Comment by MichaelSNelson** [comment] 2022-09-28 16:30
Quick note, an alternate fix is
`tiles = getCurrentHierarchy().getTileObjects()`

**Comment by petebankhead** [comment] 2022-09-28 16:33
There is no method `getTileObjects()` in [QP](https://qupath.github.io/javadoc/docs/qupath/lib/scripting/QP.html), but I agree there probably should be.

**Comment by yau-lim** [comment] 2022-09-28 16:35
> tiles = getCurrentHierarchy().getTileObjects()

Can confirm, this works but I was expecting `getTileObjects()` to work like `getDetectionObjects()` or `getAnnotationObjects()`

**Comment by MichaelSNelson** [comment] 2022-09-28 16:45
Yep, I was hoping that might narrow down the cause for Pete.

**Comment by petebankhead** [comment] 2022-10-18 08:05
This should now be fixed by https://github.com/qupath/qupath/pull/1078

**Closed** 2022-10-18 08:04 UTC
Labels: bug
