### ISSUE TITLE
Strange stain channels visualization

### ISSUE THREAD

**Issue by cfmoro** [qupath/qupath#464] opened 2020-04-30 21:00 UTC
Hi,

After setting the stain vectors with script in QuPath (noticed in m9 and m10), sometimes (kind of randomly, difficult to reproduce consistently) when examining the views for the different stain channels (by pressing '1', '2', etc), these are shown in a 'strange', hypersaturated way, attached example below. Usually I end up restarting QuPath until suddenly they appear normally. Don't know if it is only a visualization issue or if it can affect image analysis. The stain vectors in Image information are the same in both cases.

[QuPath_feedback_stain_vectors.pdf](https://github.com/qupath/qupath/files/4561177/QuPath_feedback_stain_vectors.pdf)

Best wishes,
Carlos

**Comment by Svidro** [comment] 2020-04-30 21:16
Visualization. If you want to change it, you can adjust the min-max in the Brightness/Contrast settings.

**Comment by cfmoro** [comment] 2020-04-30 21:26
Thank you. Would be possibly useful that the stain channels are consistently visualized in the "normal" way, the other can be confusing for users, especially when assessing for correct stain separation.

Best wishes,
Carlos

**Comment by petebankhead** [comment] 2020-05-01 04:43
Hi,

I'll look into it, but it's not really clear to me what the 'right' behavior is, since some kind of automatic contrast adjustment can be necessary to handle any kind of image with any kind of staining and any combination of stain vectors.

As far as I recall (although it is a long time since I look at that part of the code...) this is what QuPath tries to do. In your screenshots I personally preferred the 'strange' appearance :)

Note that the 'Auto' and 'Reset' buttons in the Brightness/Contrast window try to make it straightforward to adjust to a consistent appearance (either scaled with a specified saturation percentage, or using the minimum/maximum values).

The 'Auto Brightness/Contrast saturation %' can be adjusted in the user preferences.

**Comment by petebankhead** [comment] 2020-05-01 05:02
I forgot to add: the display in the viewer is only for visualization and doesn't affect the analysis.

I've looked at setting the stain vectors with a few images, and I couldn't find anything wrong or inconsistent.

@cfmoro can you give any exact sequence of steps that can show any bug / inconsistent behavior?

@melvingelbard and I now use GitHub Issues for planning our work, so we need a clear definition of something definitely wrong that we can fix :) Without this I'd like to close the issue - discussions are better at http://forum.image.sc/tag/qupath

**Comment by Svidro** [comment] 2020-05-01 05:22
I don't recall anything ever being wrong with this, though the results can sometimes seem weird to the user when they start doing things like messing with the stain vectors or background settings. These will have an impact on what you see in the channel views, which is expected behavior. The default values chosen may not reflect those changes.

**Comment by cfmoro** [comment] 2020-05-01 10:09
Thank you for the feedback. Unfortunately it cannot be consistently reproduced. True, I am messing with the stain vectors, working with 2-plex brightfield IHC. Knowing it is just a matter of visualization and brightness/contrast and that does not affect analysis sounds safe to close this issue.

Best wishes,
Carlos

**Comment by petebankhead** [comment] 2020-05-01 10:15
Thanks, feel free to reopen in the future if this changes.

The longer term plan is to revise how the brightness/contrast works and computes image histograms, so the issue might change...

(Specifically, the histogram used to determine contrast settings is currently generated from a lower-resolution image. But the min/max values calculated at a lower resolution don't necessarily match with the 'true' min/max values in the image. They might also be thwarted by compression artifacts. So I'd like to improve this behavior generally in a later version with a smarter histogram calculation, and only fix things in the current implementation that are clearly broken.)

**Closed by petebankhead** 2020-05-01 10:15 UTC
Labels: bug
